### ISSUE TITLE
Must templates begin with a @tag?

### ISSUE THREAD

**Issue by alandipert** [r-lib/roxygen2#1001]
Based on some testing with roxygen2 7.0.1, it appears that templates must begin with a tag. I encountered this when I made a template that contained only a `\describe{...}` that documents a data frame's columns, with the assumption that templates could be used to splice in arbitrary text.

The template looks like this: https://gist.github.com/alandipert/9e665a2d9ccebb65e991c79ff0765e17

`devtools::document()` ran without error, but the template did not appear in the `.Rd`.

Is this a bug, or expected behavior? I'm happy to contribute clarifying documentation if it doesn't exist.

## Additional context

The ability to return arbitrary chunks of text from templates is appealing to me because it would allow me to write a function-specific `@return` or `@format` by hand, but then use `@template` immediately beneath to splice in the `\describe{}`.

Without the ability to splice in arbitrary text with templates, I must further parameterize my template and use several additional `@templateVar` tags, which I feel impedes source readability.

**Comment by alandipert** [comment]
Quick update on this: I ended up not using `@template` at all, and instead use `@eval` for everything: https://github.com/rstudio/shinyloadtest/blob/50580093d38bd8e3b2fda4b8a59b1c1a0d768a66/R/data.R

**Comment by gdkrmr** [comment]
I just made the same observations, templates that do not start with a tag do not get inserted in the documentation.
