### ISSUE TITLE
'R CMD Rd2pdf <package>' produces a pdf-document but gives a lot of warnings.

### ISSUE THREAD

**Issue by BenEngbers** [r-lib/roxygen2#1006]
'R CMD Rd2pdf <package>' produces a pdf-document but also 
 a lot of warnings, most of them
come from pdfTeX. Is that expected?

Ben

[pdftxt.log](https://github.com/r-lib/roxygen2/files/3951696/pdftxt.log)

**Comment by gaborcsardi** [comment]
You probably have an error in the roxygen / Rd code. Does the output look bad?

**Comment by BenEngbers** [comment]
The output looks normal to me.

A few days ago, I have updated Rstudio (from the version that was installed from the Fedora repository to version 1.2.5019). Upon that I have updated all the installed packages.
When I want a new pdf, I first update the Rd-files (Ctrl-Shift-D in Rstudio). I then switch to the console and execute 'R CMD Rd2pdf RBaseX'.

Do you need more information?

Ben

**Comment by gaborcsardi** [comment]
> Do you need more information?

Yes, a link to your package.

**Comment by BenEngbers** [comment]
Hi,

The package has been submitted to Cran only yesterday.
Shall I mail you the tar.gz-file?

Ben

**Comment by gaborcsardi** [comment]
Seems like this is an R6 bug. We always use internal `\href{}` links, but the targets are only defined in HTML, hence the warnings for the PDF. Thanks for spotting this! Luckily the warning seems harmless, the only small issue is that the internal links in the document do not work.

```
\section{Methods}{
\subsection{Public methods}{
\itemize{
\item \href{#method-new}{\code{QueryClass$new()}}
\item \href{#method-Next}{\code{QueryClass$Next()}}
...
```

```
\if{html}{\out{<a id="method-new"></a>}}
\subsection{Method \code{new()}}{
Initialize a new instance from QueryClass
...
```

Hopefully LaTeX has a way to put in the link targets, I'll take a look in a sec.

**Comment by gaborcsardi** [comment]
Indeed, for this link:
```
\item \href{#method-new}{\code{QueryClass$new()}}
```
we can add this target:
```
\if{latex}{\out{\hypertarget{method-new}{}}}
```
and then the link works and the warning is gone. Awesome.

**Comment by BenEngbers** [comment]
Nice!

In my first mail to Hadley, I also mentioned that the output from
\dontrun{} was not rendered in the wright way (see below).

Does this have the same cause?

Ben

-------

When using the @description-, @detail- and @param-tags, the output is as
expected. But using '\dontrun{<code>}' does not return the correct output.
Instead of
## Not run:
<code>

## End(not run)

I get
\dontrun{
code
}

I have one final question on R6.
I have developed a client for the BaseX XML-database. The client
consists of 2 classes. 'BasexClient' creates a connection to the server.
And once that the connection is established, a public method is called
to create a query-object from class 'QueryClass'.
There is no other way to create a query-object so the 'initialize'-code
for the QueryClass should be private.

Is there a way to hide Querclass$new()?

Thanks,
Ben Engbers


Op 12-12-2019 om 22:15 schreef Gábor Csárdi:

**Comment by gaborcsardi** [comment]
>  the output from \dontrun{} was not rendered in the wright way (see below).

No, that's different, please open another issue. Currently you cannot really use `\dontrun{}` for method examples. You can use it for the whole class, though.
