### ISSUE TITLE
roxygen2 reported error after upgrade from 6.1.1 to 7.0.2

### ISSUE THREAD

**Issue by genomaths** [r-lib/roxygen2#1008]
Hi there 
    I have been using roxygen2 6.1.1 for all my R packages. Now after upgrade roxygen2 to version 7.0.2, I got the following error:

 Error in if (self$has_section(type) && !overwrite) { : missing value where TRUE/FALSE needed

   I reinstalled the old version 6.1.1 to keep updating the projects. 
Since I focus my attention on the maths and not in the documentation, perhaps I am missing some important detail.
 
You can check the project https://github.com/genomaths/MethylIT/tree/MethylIT_0.3.2_beta (roxygen2 6.1.1)

Would you please give me some tip on how to solve this problem?

Best,
Robersy

**Comment by gaborcsardi** [comment]
Hi, this is because you have 
```
#' @description NULL
```
here: https://github.com/genomaths/MethylIT/blob/ddec3eb401b31820ffd31dd9eb469781611da3f7/R/ggamma.R#L74 and also elsewhere. roxygen2 should give a better error message though. 

What are you trying to achieve by setting the description tag to `NULL`?

**Comment by gaborcsardi** [comment]
Actually if there is another `@description` tag, then roxygen2 should just merge them and not error. Let me fix this.

**Comment by gaborcsardi** [comment]
Here is a small reprex:

``` r
roxygen2::roc_proc_text(roxygen2::rd_roclet(), "
  #' Title
  #'
  #' @description desc1
  #' @description NULL
  foo <- function() NULL
  ")[[1]]
#> Error in if (self$has_section(type) && !overwrite) {: missing value where TRUE/FALSE needed
```

<sup>Created on 2019-12-13 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by gaborcsardi** [comment]
But actually, even this fails:

``` r
roxygen2::roc_proc_text(roxygen2::rd_roclet(), "
  #' Title
  #'
  #' @description NULL
  foo <- function() NULL
  ")[[1]]
#> Error in if (self$has_section(type) && !overwrite) {: missing value where TRUE/FALSE needed
```

<sup>Created on 2019-12-13 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by gaborcsardi** [comment]
@hadley it seems that having `NULL` for `@description` or `@details` will trigger this error. What should roxygen2 do if either of these are `NULL`?
- not generate that section at all? This will be an `R CMD check` error I guess, but if that's what the user wants, let them have it.
- generate a default `\description{}` section, as if the topic had no (explicit or implicit) description at all? I.e. use the title? (`\details{}` is not compulsory AFAIR, so that should be fine.)
- give and error that there `\description` section is empty and that's not allowed?

**Comment by hadley** [comment]
I think warn and drop the tag so you get the default behaviour?

**Comment by gaborcsardi** [comment]
Yeah, that makes sense. I'll submit a PR.

**Comment by gaborcsardi** [comment]
OK, so there is actually a case when suppressing `\description{}` makes sense, for package level manual pages. From WRE:

> This is mandatory except for package-overview files.

So for these we should not warn, and should not drop either, I guess, because `@description NULL` is good for suppressing the auto-generated section?

**Comment by hadley** [comment]
@gaborcsardi supporting that seems relatively low priority to me.

**Comment by genomaths** [comment]
Hi guys 

Thank you very much for your answers. I really appreciate it.

    In the case of ggamma probability distribution function, where I just write down the four statistical functions dggamma, pggamma, rggamma, and qggamma in the same file, it does not makes sense to me the repetition of the content for \description and  \details sections four times. I mean, if I must do it to prevent the error, then I will do it. However, as @gaborcsardi suggests, if you can introduce the flexibility to go with the option NULL or something similar, then that will be great. This is the application of "Minimum writing code principle", the code version of "Ockham's razor principle" :-)

Please let me know if @gaborcsardi  pull request went through.

Best,
Robersy

**Comment by gaborcsardi** [comment]
>  it does not makes sense to me the repetition of the content for \description and \details sections four times.

roxygen2 will not repeat a section just because the page documents multiple sections. You can just remove the `@description NULL` and `@details NULL` lines.

**Comment by genomaths** [comment]
I do remember  when I wrote the first version of the ggamma function (using old version of roxygen2), I was forced to introduce these sections and to write NULL solved the problem. Perhaps, I did something wrong at that time that force me to do it.   Anyway, I will follow your suggestion.

Thank you very much for your support
