### ISSUE TITLE
Allow user-defined tags from external packages, have a way to load an external package in `roxygenize()`

### ISSUE THREAD

**Issue by hadley** [r-lib/roxygen2#1013]
Before:

```yaml
Roxygen: { library(roxygenlabs); list(markdown = TRUE,
    roclets = c("collate", "namespace", "roxygenlabs_rd")) }
```

After:

```yaml
Roxygen: list(
      markdown = TRUE,
      roclets = c("collate", "namespace", "roxygenlabs::roxygenlabs_rd")
    )
```

**Comment by hadley** [comment]
This already seems to work, as far I can tell.

**Comment by gaborcsardi** [comment]
Wow.

**Comment by gaborcsardi** [comment]
Actually, one issue is defining new tags without defining new roclets. E.g. roxygenlabs has 

```r
roxy_tag_parse.roxy_tag_examplesIf <- function(x) {
   ...
}

roxy_tag_rd.roxy_tag_examplesIf <- function(x, base_path, env) {
  rd_section("examples", x$val)
}
```

which adds a new `@examplesIf` tag. But this only works if the roxygenlabs package is loaded when `roxygenize()` is called. So it would be nice if we had a way for loading it at the beginning of `roxygenize()`. E.g. processx currently has this in `DESCRIPTION` as a workaround:

```
Roxygen: { library(roxygenlabs); list(markdown = TRUE) }
```

Which is not terrible, but it would be cleaner to write 

```
Roxygen: list(markdown = TRUE, roxy_packages = "roxygenlabs")
```

**Comment by gaborcsardi** [comment]
One solution would be to load `roxy_packages` when the options are loaded, at the beginning of `roxygenize()`. And we would give a warning if they are not available.
