### ISSUE TITLE
R6 class without source references

### ISSUE THREAD

**Issue by stefanfritsch** [r-lib/roxygen2#1014]
Hi,

I get the following error with Roxygen2 7.0.2; google only finds source code in this repository:

```
Error in .f(.x[[i]], ...) : R6 class without source references
```

* No hint what it means
* No hint which file
* No hint which R6 class is responsible
* No hint what to do

Could you please make the error a bit more informative?

In my case it was due to a method that was generated by a generating function and that threw off `utils::getSrcref()`. I don't know if there's a solution apart from disabling R6 support.

Thanks
Stefan

**Comment by hadley** [comment]
Can you please provide a reprex?

**Comment by hadley** [comment]
I've closed this issue due to lack of requested reprex. If you still care about this bug, please open a new issue with a reprex.

**Comment by jcubic** [comment]
I have the same issue, I have no idea how to create reprex, it started to happen after I've removed one file with R6Class.

**Comment by jcubic** [comment]
Latest version also suggest to use `--with-keep.source` but I build my package from source. It seems that this have nothing to do with my recent changes it just giving this errors for unknown reason, without any helpful message. I have function in Package that return new R6Class that have full documentation that I've recently added, another package export instances of those classes.

**Comment by gaborcsardi** [comment]
> I have function in Package that return new R6Class that have full documentation that I've recently added, another package export instances of those classes.

This situation is not currently supported by Roxygen.

**Comment by jcubic** [comment]
I'm not sure if this was added recently but it seems that you can't export from one package R6 class defined in other pages where both packages are not installed with install.packages because they both are your own packages.

So you can't create package that create R6Class components because roxygen will not find source refs for methods from your package. Your forcing everyone that want to document his package to install my package from source.

**Comment by jcubic** [comment]
But it was working correctly before, does it mean that you need to use old roxygen if you want to use this feature? I have this setup for months. I've added docs for my component package but I've installed master branch that don't have all that, and it give the same error. Note error not warning.

**Comment by jcubic** [comment]
I have package with components I export function component and I just use:

```R
#' @export
x <- pkg::component(...)
```

without documentation, I just want to get rid of error, this should be warning.

**Comment by gaborcsardi** [comment]
> To turn off the special handling of R6 classes and go back to the roxygen2 6.x.x behavior, use the r6 = FALSE option in DESCRIPTION, in the Roxygen entry: Roxygen: list(r6 = FALSE).

https://roxygen2.r-lib.org/articles/rd.html#r6
