### ISSUE TITLE
Usage for function with two different interfaces

### ISSUE THREAD

**Issue by ntguardian** [r-lib/roxygen2#1020]
Consider the `names()` function. In the R documentation, usage for both `names(x)` and `names(x) <- value` is listed. But this does not occur with the following functions:

```r
#' Get/Set Second
#'
#' Get/set the second item in a list
#' 
#' @param x The list
#' @param value The new second item
#' @return The second item in \code{x}
#' @export
#' @examples
#' l <- as.list(1:2)
#' second(l)
#' second(l) <- 10
#' print(l)
second <- function(x) {
  x[[2]]
}

#' @export
`second<-` <- function(x, value) {
  x[[2]] <- value
  x
}
```

Am I missing something? Is there a way for both forms of usage of `second()` to appear in the same documentation file, without manually setting via `@usage`?

**Comment by gaborcsardi** [comment]
You can supply your own Usage section if you don't like the auto-generated one:

```r
#' @usage
#' names(x) 
#' names(x) <- value 
```

**Comment by ntguardian** [comment]
> You can supply your own Usage section if you don't like the auto-generated one:
> 
> ```r
> #' @usage
> #' names(x) 
> #' names(x) <- value 
> ```

True. Supposedly though the `@usage` tag should be avoided and Hadley Wickham suggests filing a bug report if it's needed: see https://stackoverflow.com/questions/8873514/documenting-setter-functions-with-roxygen

**Comment by gaborcsardi** [comment]
Well, in the simple case where the auto-generated usage sections are just merged, you can just tell roxygen to merge them:

```r
#' @export
#' @rdname second

`second<-` <- function(x, value) {
  x[[2]] <- value
  x
}
```

**Comment by ntguardian** [comment]
> ```r
> 
> #' @rdname second
> ```

Okay, I like that solution. Thank you!
