### ISSUE TITLE
@evalNamespace fails with warning

### ISSUE THREAD

**Issue by hughjonesd** [r-lib/roxygen2#1022]
In hello.R:

```
#' @evalNamespace "export(foo)"
NULL
```

If I run `roxygen2::roxygenize()` using version 6.1.1, this creates a NAMESPACE file containing the line 

export(foo)

as expected. However, using version 7.0.2, I get a warning:

```
Warning: [/Users/david/packagefileprob/R/hello.R:1] @evalNamespace failed with error:
invalid 'envir' argument of type 'closure'
```

and the line is not written in NAMESPACE.

The error appears to be that in `roxy_tag_eval`, `env` is not being passed, and is instead being taken to be `rlang::env`. The original cause seems to be this line in `roclet_preprocess.roclet_namespace`:

```
  lines <- blocks_to_ns(blocks, env, import_only = TRUE)
```
which refers to a not locally defined `env` variable.

**Comment by hadley** [comment]
Looks like the problem was introduced here: https://github.com/r-lib/roxygen2/commit/8c82a079e8d333ed62ecadabfc6b726b8947baf0#diff-85658d9a5cecb42c8e8957560ab6d7abL54-L65

**Comment by hadley** [comment]
Fixed now — would you mind sharing what you're using `@evalNamespace` for?

**Comment by hughjonesd** [comment]
It's for autogeneration of a lot of namespace entries, see here:
https://github.com/hughjonesd/huxtable/blob/master/R/properties.R
