### ISSUE TITLE
[R6] Cannot document active bindings

### ISSUE THREAD

**Issue by pat-s** [r-lib/roxygen2#1030]
Is documenting active bindings support currently?

When doing so,  I get 

```r
Warning: [/Users/pjs/git/mlr-org/mlr3spatiotempcv/R/ResamplingRepeatedSpCVCoords.R:93] @description Cannot find matching R6 method
Warning: [/Users/pjs/git/mlr-org/mlr3spatiotempcv/R/ResamplingRepeatedSpCVCoords.R:33] undocumented R6 active binding: `iters`
```

Source:

```r
  active = list(

    #' @description
    #' Return the number of resampling iterations, depending on the
    #' values stored in the `param_set`.
    iters = function() {
      pv = self$param_set$values
      as.integer(pv$repeats) * as.integer(pv$folds)
    }
  ),
```

relates to #1016

**Comment by gaborcsardi** [comment]
See https://roxygen2.r-lib.org/articles/rd.html#r6

> R6 fields and active bindings can make use of the @field tag. Their documentation should also be in-line.

**Comment by pat-s** [comment]
Ah sorry, it has to be 

  active = list(

    #' @field
    #' Return the number of resampling iterations, depending on the
    #' values stored in the `param_set`.
    iters = function() {
      pv = self$param_set$values
      as.integer(pv$repeats) * as.integer(pv$folds)
    }
  ),
