### ISSUE TITLE
Dont modify DESCRIPTION if package does not use roxygen2?

### ISSUE THREAD

**Issue by zachary-foster** [r-lib/roxygen2#1035]
This is a minor edge-case issue, but I thought I might be worth mentioning.

I have my RStudio build options set to run roxygen2 when I hit `Ctrl + Shift + B`, which I like for developing my packages, which always use roxygen2. However, I occasionally contribute to packages that do not use roxygen2 and when I build those, roxygen2 says:

```
Warning: The existing 'NAMESPACE' file was not generated by roxygen2, and will not be overwritten.
```

and does not seem to touch the documentation, which is great. However, it also does:

```
First time using roxygen2. Upgrading automatically...
Updating roxygen version in /path/to/pacakge/DESCRIPTION
```

and modifies the description, adding:

`RoxygenNote: 7.0.2.9000`

which does not need to be there. It seems to me that if `roxygen2` detects that a package is using only hand-written documentation, and therefore does not change anything, it should not add this to the DESCRIPTION.

If you are interested, I could look into it and submit a PR.

**Comment by Hong-Revo** [comment]
Well, generating the NAMESPACE file is a distinct operation to processing Roxygen blocks. You can have blocks for unexported objects; these will generate a Rd file but won't touch the NAMESPACE.
