### ISSUE TITLE
Implement a better syntax for double dispatch

### ISSUE THREAD

**Issue by krlmlr** [r-lib/roxygen2#1036]
## Double dispatch methods

```r
#' @method vec_cast.binned double
#' @export
vec_cast.binned.double <- function(x, y, ...) {
}
```

should become

```r
#' @export
vec_cast.binned.double <- function(x, y, ...) {
}
```

roxygen2 takes the *last* dot as the default separator for the method. A few downstream packages might need fixing.

## First-level dispatch

```r
#' @method vec_cast vctrs_percent
#' @export
#' @export vec_cast.vctrs_percent
vec_cast.vctrs_percent <- function(x, to, ...) {
} 
```

should become perhaps

```r
#' @ddexport
vec_cast.vctrs_percent <- function(x, to, ...) {
}
```

## Reference

https://vctrs.r-lib.org/articles/s3-vector.html#appendix-namespace-declarations

**Comment by hadley** [comment]
I think we're unlikely to invest in this now (since R7 is in the works).
