### ISSUE TITLE
Back-quoted S4-method signature breaks package check in R-devel

### ISSUE THREAD

**Issue by kingaa** [r-lib/roxygen2#1037]
In my package [**pomp**](https://github.com/kingaa/pomp), all documentation is produced by **roxygen2**.  I have the following S4 method declaration ([here](https://github.com/kingaa/pomp/blob/master/R/parameter_trans.R), lines 158ff).

```
##' @name parameter_trans-function,function
##' @aliases parameter_trans,function,function-method
##' @rdname parameter_trans
##' @export
setMethod(
  "parameter_trans",
  signature=signature(toEst="function",fromEst="function"),
  definition=function(toEst, fromEst, ...) {
    new("partransPlugin",has=TRUE,to=toEst,from=fromEst)
  }
)
```

`devtools::document` produces the following corresponding help-page snippet ([here](https://github.com/kingaa/pomp/blob/master/man/parameter_trans.Rd), line 27).

```
\S4method{parameter_trans}{`function`,`function`}(toEst, fromEst, ...)
```

Using the current R-devel, this breaks `R CMD check`, complaining about an inability to typeset the back-quotes around `function` in the above.  Specifically, if I edit the `.Rd` file by hand, removing the back-quotes to get
```
\S4method{parameter_trans}{function,function}(toEst, fromEst, ...)
```
Then the code passes muster with ` R CMD check`.

I assume there is some need to quote `function`, as distinct from any other possible signature class.  However, unless this is resolved somehow, it appears that any package using S4 classes and **roxygen2** has a good chance of suddenly failing to be compatible with **R** version 3.7.

**Comment by hadley** [comment]
Quoting was added here: https://github.com/r-lib/roxygen2/commit/f952d350d3b8c60788d50700e13b680a833c1204

**Comment by hadley** [comment]
But I can't reproduce this failure: https://github.com/r-lib/roxygen2/pull/1057

**Comment by kingaa** [comment]
I could not reproduce it on my own system either.  Only when I submitted the package to CRAN, so that the checks under one particular flavor of R-devel were performed, did the problem arise, and only for that flavor.  I believe it was r-devel-linux-x86_64-debian-clang or r-devel-linux-x86_64-fedora-clang.  An issue with building the PDF documentation.

P.S. In the immediately preceding comment, did you mean to reference #1037 (this issue)?

**Comment by hadley** [comment]
@kingaa If you can create a minimal reprex, I'm happy to look at this again, but my tests suggest the current approach is fine.
