### ISSUE TITLE
How to document passing arguments with ellipsis

### ISSUE THREAD

**Issue by TomKellyGenetics** [r-lib/roxygen2#1038]
The following line returns a WARNING in the development version of R (it has not before).

`##' @param ... 	Arguments to be passed to methods`

https://bugs.r-project.org/bugzilla/show_bug.cgi?id=16223

```
checking Rd \usage sections ... WARNING
Documented arguments not in \usage in documentation object 'leiden':
  ‘...’

Functions with \usage entries need to have the appropriate \alias
entries, and all their arguments documented.
The \usage entries must correspond to syntactically valid R code.
See chapter ‘Writing R documentation files’ in the ‘Writing R
Extensions’ manual.
```

**Comment by gaborcsardi** [comment]
Can you please create a reproducible example? See https://github.com/r-lib/roxygen2/blob/master/.github/SUPPORT.md#getting-help-with-roxygen2 Thanks!

**Comment by TomKellyGenetics** [comment]
Please see here for details on a package that produced this error: https://cran.r-project.org/web/checks/check_results_leiden.html

source: https://github.com/TomKellyGenetics/leiden/blob/master/R/leiden.R

**Comment by TomKellyGenetics** [comment]
Is there are recommended way to document an ellipsis? I've found a package with functions to handle them but this doesn't cover documentation. https://github.com/r-lib/ellipsis

**Comment by gaborcsardi** [comment]
You documented `...` for a function that does not have that argument: https://github.com/TomKellyGenetics/leiden/blob/f0e443d2f4055550ba2d6d891b05471ff0e558bc/R/leiden.R#L10
https://github.com/TomKellyGenetics/leiden/blob/f0e443d2f4055550ba2d6d891b05471ff0e558bc/R/leiden.R#L75

**Comment by TomKellyGenetics** [comment]
Thanks, I've removed it and Travis builds with the development version of R. https://travis-ci.org/TomKellyGenetics/leiden/builds/645750090

So for a function that has an `...` argument these checks should still pass.
