### ISSUE TITLE
roxygen2 should not assume ORCIDs are "bare"

### ISSUE THREAD

**Issue by cboettig** [r-lib/roxygen2#1040]
Roxygen is incorrectly assuming that ORCIDs in the DESCRIPTION are always entered without the `https://`, see 

https://github.com/r-lib/roxygen2/blob/c15f2651d58f69928d7e5159702b128857035886/R/object-package.R#L51

ORCID guidelines say that the ID should *always* display the URI format, https://orcid.org/content/journal-article-display-guidelines, and so I always include the `https://orcid.org/` part in my DESCRIPTION (a URI is much more robust / useful than a bare identifier).  I think roxygen should at least check for `http[s]` first before it goes and appends it.   

Note that it looks like CRAN does not make this assumption, and registers the ORCID link correctly on the CRAN webpage when the developer already has the full URI.  (However I think pkgdown sites use the URIs generated here, and so are also creating invalid links in this case).  

Thanks much!!  Really appreciate the support for ORCID across the R community!

**Comment by hadley** [comment]
Would you be interested in doing a PR to fix this?
