### ISSUE TITLE
Extra { around inherited ifelse tags

### ISSUE THREAD

**Issue by akersting** [r-lib/roxygen2#1062]
Using `@inheritParams` produces "bad markup" if the Rd inherited from contains `\ifelse` as e.g. the case for `parallel::mclapply`.

This is very similar to #778 (fixed in e1d3930ecf92ea4a46512776e2b6509f3c619f52). Also here extra `{}` are added. Hence, adding `"\\ifelse"` to the vector `TWOARG` of `as_character_rd` should fix the issue.

**Comment by hadley** [comment]
Would you be interested in contributing a PR?
