### ISSUE TITLE
Can't tell where to put @useDynLib

### ISSUE THREAD

**Issue by dfrankow** [r-lib/roxygen2#1063]
I want to automate generating NAMESPACE using Roxygen. I also want useDynLib() in it.

I found [this stackoverflow question](https://stackoverflow.com/q/8407615/34935) and [this issue](https://github.com/r-lib/roxygen2/issues/124) about useDynLib. Together, they explain enough that I think I know I want

```
@useDynLib mypackage .registration=TRUE
```

But which file should I put that directive in? [The docs](https://cran.r-project.org/web/packages/roxygen2/vignettes/namespace.html) don't say, and I've been combing through github looking for examples.

**Comment by dfrankow** [comment]
I think I should put it maybe in [package-level documentation](https://r-pkgs.org/man.html#man-packages). However, now when I put that line in my package-level docs, I get

```
Error in getNativeSymbolInfo(symNames, dll, unlist = FALSE, withRegistrationInfo = TRUE) : 
  must pass a package name, “DLLInfo” or “DllInfoReference” object
```

also referenced [here](https://community.rstudio.com/t/import-c-function-from-another-package/54834) without answer.

**Comment by dfrankow** [comment]
[This page](https://www.rdocumentation.org/packages/roxygen3/versions/0.1/topics/UseDynLibTag-class) shows some examples under "Tag Usage", but they don't work for me.

**Comment by dfrankow** [comment]
I am using roxygen2 version 7.1.0, and those examples are for roxygen3 version 0.1. Maybe useDynLib works differently in the two?

**Comment by dfrankow** [comment]
Gods, never mind, it worked to put it in the package-level file. I had to delete NAMESPACE.

**Comment by JosiahParry** [comment]
I am running into this issue currently. Are you able to share your solution?

**Comment by dfrankow** [comment]
https://stackoverflow.com/a/60750351
