### ISSUE TITLE
No way to document R6Class without return value and parameters

### ISSUE THREAD

**Issue by jcubic** [r-lib/roxygen2#1064]
I have method:
```R
    ## ---------------------------------------------------------------
    #' Method remove all observers created for this component
    ## ---------------------------------------------------------------
    destroy = function() {

   }
```
If there are no at rules it show warning that it's not documented. Adding:

```R
    #' @examples
    #' \code{component$destroy()}
```

fix the issue, it should be a way to add documentation to method like this, without hacks.
Same happen with `finalize`, not sure if you can document it differently.

**And additional question**:
Are there any documentaion for how to write documentation for R6Class, or do you need to find it from GitHub issues and StackOveflow questions?

**Comment by gaborcsardi** [comment]
> If there are no at rules it show warning that it's not documented 

If you are fine with an undocumented method, then you can just ignore the warning. We might have some notation in the future to ignore methods.

> Are there any documentaion for how to write documentation for R6Class, or do you need to find it from GitHub issues and StackOveflow questions?

Yes, it is in the manual: https://roxygen2.r-lib.org/articles/rd.html#r6

**Comment by jcubic** [comment]
Thanks.

**Comment by jcubic** [comment]
Closed by mistake, the answer was to additional question, the issue is sill there, it's hard to document functions with just side effects without arguments and return values, which is problematic for R6Class that may modify object state.

**Comment by gaborcsardi** [comment]
You need to start the documentation of a method with `@details` or `@description`, e.g.

```r
  #' @description Remove all observers created for this component.
  destroy = function() {
  }
```
