### ISSUE TITLE
Add missing @subsection tag

### ISSUE THREAD

**Issue by klmr** [r-lib/roxygen2#1079]
It seems that #28 got orphaned and a `@subsection` tag was never implemented. The [documentation](https://roxygen2.r-lib.org/articles/rd.html#sections) only describes how to generate subsections using rmarkdown. For now the workaround seems to be to use raw Rd format.

Semi-relatedly, there does not seem to be an authoritative, documented list of supported roxygen2 tags. In previous versions, we could at least get a list in code using `names(roclet_tags(rd_roclet()))` but this is now defunct. The closest equivalent now seems to be `sub('.*\\.roxy_tag_', '', as.character(methods('roxy_tag_parse')))[-1L]`, which somewhat hinders discoverability. I’m guessing [the “rd” vignette](https://roxygen2.r-lib.org/articles/rd.html) is meant to be exhaustive but it is missing a few tags, and it does not provide an overview list.

**Comment by gaborcsardi** [comment]
Do you have a use case that needs `@subsection`? Roxygen does not support nested tags currently, and it would be hard/messy to implement a `@subsection` tag with nesting semantics.

Yes, the rd vignette is the authoritative source. Do you know which tags are missing from there? I remember that some deprecated ones were left out on purpose.

**Comment by klmr** [comment]
I do have a use-case but since that’s rather specific I was going to show you uses from the R core source tree. But it turns out that there are *no* uses (except in `gnuwin32/CHANGES.Rd`) … so that’s a pretty good argument *against* using subsections in general.

For what it’s worth my use has different subsections under `@note`. There are quite a few base R functions that use the ‘Details’ and ‘Note’ sections extensively *without* using subsections, and the result is rather messy for readers (e.g. [`?connections`](https://stat.ethz.ch/R-manual/R-devel/library/base/html/connections.html)), especially when multiple functions are documented together.

That said, I will just use proper sections instead.

> Yes, the rd vignette is the authoritative source. Do you know which tags are missing from there?

I just grepped the list of existing `roxy_tag_parse` methods against the vignette and came up with this:

* `@author`
* `@docType`
* `@encoding`
* `@evalNamespace`
* `@exportClass`
* `@exportMethod`
* `@exportPattern`
* `@exportS3Method`
* `@import`
* `@importClassesFrom`
* `@importFrom`
* `@importMethodsFrom`
* `@include`
* `@inheritDotParams`
* `@md`
* `@noMd`
* `@noRd`
* `@note`
* `@rawNamespace`
* `@rawRd`
* `@returns`
* `@usage`
* `@useDynLib`

Some of these are directives that may not need to be documented in that vignette. Still, having a prominently-placed list with all of them and links to their respective place in the documentation would be nice.

**Comment by gaborcsardi** [comment]
I am not arguing against having subsections in general. But I am not sure if there is a case where you cannot use either markdown or `\subsection{}`, usually you can use both.

Note that `\subsection` is not no special in that it does not have an equivalent roxygen tag. Every Rd tag tag is supposed to be embedded into another one is like that. Roxygen pretty much only has tags for the top-level Rd tags, plus some special ones.

**Comment by klmr** [comment]
@gaborcsardi I entirely agree, the current situation isn’t actually a problem.

Your initial reply made me pivot from “there is a missing tag” to “we need better documentation of what roxygen2 tags exist”. Should the issue be renamed or a new issue opened? Or is this not worth an issue at all?

**Comment by gaborcsardi** [comment]
Maybe a new issue is better, so people won't get distracted by the subsection discussion. 

We discussed having a vignette or a table of all roxygen tags, but decided to focus on other parts of the docs instead. You are not the first one asking about it, so it is probably time to discuss it again.
