### ISSUE TITLE
Create a list of the supported @tags

### ISSUE THREAD

**Issue by klmr** [r-lib/roxygen2#1080]
As per the discussion in #1079, the roxygen2 documentation is currently missing a comprehensive overview list of the supported `@tags`. Most (but not all!) tags are currently [documented in the “rd” vignette](https://roxygen2.r-lib.org/articles/rd.html). However, that vignette also does not include a list overview of the supported tags, and searching for a suitable tag is not always trivial if the user does not know its exact name.

I suggest either having a separate page or a “table of contents” like list at the beginning of the “rd” vignette, which lists all supported tags with hyperlinks to the documents/sections where they are explained.

For reference, here is a list of the tags that seem to be currently undocumented.

<details>
<summary>Undocumented <code>@tags</code></summary>

* `@author`
* `@docType`
* `@encoding`
* `@evalNamespace`
* `@exportClass`
* `@exportMethod`
* `@exportPattern`
* `@exportS3Method`
* `@import`
* `@importClassesFrom`
* `@importFrom`
* `@importMethodsFrom`
* `@include`
* `@inheritDotParams`
* `@md`
* `@noMd`
* `@noRd`
* `@note`
* `@rawNamespace`
* `@rawRd`
* `@returns`
* `@usage`
* `@useDynLib`

</details>

<details>
<summary>Code to generate the list</summary>

```r
tags = sub('.*\\.roxy_tag_', '', as.character(methods('roxy_tag_parse')))[-1L]
vignette_file = system.file(file.path('doc', vignette('rd')$PDF), package = 'roxygen2')
vignette = paste(readLines(vignette_file), collapse = '')
missing = vapply(paste0('@', tags, '\\b'), Negate(grepl), logical(1L), vignette)
tags[missing]
```

</details>

**Comment by gaborcsardi** [comment]
Most (all?) namespace related tags are listed in the NAMESPACE vignette.

**Comment by hadley** [comment]
I think this is the list of missing Rd tags:

* `@author`
* `@docType`
* `@encoding`
* `@inheritDotParams`
* `@noRd`
* `@note`
* `@rawRd`
* `@returns`
* `@usage`

Documenting these in the vignette would be a great way to contribute to roxygen2!

**Comment by maelle** [comment]
a big table with links to the relevant vignette section would still be useful IMHO. Not the same but I like https://rstudio.github.io/bslib/articles/bs4-variables.html
