### ISSUE TITLE
Clarify version needed for dynamic R code

### ISSUE THREAD

**Issue by ramiromagno** [r-lib/roxygen2#1081]
## Introduction

I am trying to use for the first time markdown inline code markup to evaluate R code and insert its output into the manual page, as described here: https://roxygen2.r-lib.org/articles/rd-formatting.html#dynamic-r-code.

The real context is in a package but I am putting here a minimal working example as requested in the support guidelines, i.e., using reprex and `roc_proc_text()`.

So the problem is that the inline R code does not evaluate. In my package I have added the line `Roxygen: list(markdown = TRUE)` to `DESCRIPTION`.

## MWE
``` r
doc <- "
#' dummy
#'
#' Roxygen created this manual page on `r Sys.Date()` using R version
#' `r getRversion()`.
#'
#' # Custom section
#' ## Custom subsection
#' The `iris` data set has `r ncol(iris)` columns:
#' `r paste0('``', colnames(iris), '``', collapse = ', ')`.
#'
#' @name dummy
#'
NULL
"

library(roxygen2)
roc_proc_text(rd_roclet(), doc)
#> $dummy.Rd
#> % Generated by roxygen2: do not edit by hand
#> % Please edit documentation in ./<text>
#> \name{dummy}
#> \alias{dummy}
#> \title{dummy}
#> \description{
#> Roxygen created this manual page on `r Sys.Date()` using R version
#> `r getRversion()`.
#> }
#> \details{
#> # Custom section
#> ## Custom subsection
#> The `iris` data set has `r ncol(iris)` columns:
#> `r paste0('``', colnames(iris), '``', collapse = ', ')`.
#> }
packageVersion('roxygen2')
#> [1] '7.0.2'
R.version.string
#> [1] "R version 3.6.0 (2019-04-26)"
```

<sup>Created on 2020-04-24 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by gaborcsardi** [comment]
You need roxygen2 7.1.0 for this.

**Comment by ramiromagno** [comment]
Thank you for answering so quickly.

Because the docs refer version 6.0.0 [here](https://roxygen2.r-lib.org/articles/rd-formatting.html#turning-on-markdown-support) I did not look further...

**Comment by gaborcsardi** [comment]
Oh, right, 6.0.0 is for the initial markdown support, but yeah, it is confusing, we should clarify this in the docs. I'll keep this issue open for a reminder.

**Comment by hadley** [comment]
Given that 7.1 has been out for >2 years now, I think we can probably skip this change.
