### ISSUE TITLE
Links to function [func()] not generated?

### ISSUE THREAD

**Issue by okhoma** [r-lib/roxygen2#1082]
I am unable to generate links to functions in the same package when referenced using `[func()]` syntax. According to https://roxygen2.r-lib.org/articles/rd-formatting.html#links it should generate `\code{\link[=func]{func()}}`, but it just leaves `[func()]`

```r
#' Sample Function 1
fun1 <- function() { }

#' Sample function 2
#'
#' It uses [fun1()] internally
fun2 <- function() { }
```
The generates Rd file:

```
% Generated by roxygen2: do not edit by hand
% Please edit documentation in R/test.R
\name{fun2}
\alias{fun2}
\title{Sample function 2}
\usage{
fun2()
}
\description{
It uses [fun1()] internall
}
```

What am I missing? 

roxygen2 7.1.0

**Comment by gaborcsardi** [comment]
Did you turn on markdown support? https://roxygen2.r-lib.org/articles/rd-formatting.html#turning-on-markdown-support

**Comment by okhoma** [comment]
No, thanks, I kind of assumed it is a default behavior. Works after turning it on.
