### ISSUE TITLE
@param in @rdname silently overwrites @param originally defined

### ISSUE THREAD

**Issue by billdenney** [r-lib/roxygen2#1084]
When a parameter is defined in an `@rdname` function, it silently overwrites the same parameter defined in the original function.  In the example below, the parameters `x` is defined as "bar" when I would have expected either some form of concatenation (my preference) or an error telling me that I need to somehow fix it.

```r
#' foo
#' 
#' @param x foo
#' @return `x`
#' @export
foo <- function(x) {
  x
}

#' @rdname foo
#' @param x bar
#' @export
bar <- function(x) {
  x
}
```

**Comment by gaborcsardi** [comment]
You cannot have `@param` in `@rdname`, the tags are not embedded. 

If you want to document two functions on the same manual page, that have the same argument (`x`), but this argument needs different documentation for the two functions, then you'll need to reconcile these into a single `@param`. Or document them in two separate manual pages.

**Comment by billdenney** [comment]
@gaborcsardi, I'm totally with you that reconciling the difference is the way to go.  It just took me a while to find the problem because my real example was more complicated than the one above.

The request in the issue is to make the above into an error (or at least a warning) to help find issues like this.

**Comment by gaborcsardi** [comment]
Yeah, I think a warning is probably appropriate here.

**Comment by hadley** [comment]
@billdenney can you please create a reprex following the advice at https://github.com/r-lib/roxygen2/blob/master/.github/SUPPORT.md#making-a-reprex ?

**Comment by billdenney** [comment]
@hadley, thanks for the pointer.  I didn't know how to make a reprex for roxygen.

The expected result is a warning.

``` r
library(roxygen2)
roc_proc_text(rd_roclet(), "
#' foo
#' 
#' @param x foo
#' @return `x`
#' @export
foo <- function(x) {
  x
}

#' @rdname foo
#' @param x bar
#' @export
bar <- function(x) {
  x
}"
)
#> $foo.Rd
#> % Generated by roxygen2: do not edit by hand
#> % Please edit documentation in ./<text>
#> \name{foo}
#> \alias{foo}
#> \alias{bar}
#> \title{foo}
#> \usage{
#> foo(x)
#> 
#> bar(x)
#> }
#> \arguments{
#> \item{x}{bar}
#> }
#> \value{
#> `x`
#> }
#> \description{
#> foo
#> }
```

<sup>Created on 2020-05-01 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hadley** [comment]
Looking at the code comments, it seems we're doing this deliberately, so I think changing this behaviour is likely to create more problems than it solves.

**Comment by billdenney** [comment]
@hadley , I fully understand that the behavior is desired and expected.  But, I think that it is commonly an error on the programmer's part when it occurs. So, does a warning make sense to let them know that a parameter was overwritten?

**Comment by hadley** [comment]
I don't think so, because based on my reading of the code, it will cause warnings which are false positives.

**Comment by billdenney** [comment]
Ah.  That makes sense.  Thanks for the clarification.
