### ISSUE TITLE
@exportS3Method fails when package not imported or already in global namespace

### ISSUE THREAD

**Issue by NikNakk** [r-lib/roxygen2#1085]
With the move to R 4.0.0, I've come across an issue with one of my packages where I wanted to include S3 methods without introducing a dependency on the package that defines the generic. I'd previously done this by `@export`ing the function without an `@importFrom`, which meant that an `export` rather than `S3method` directive was written to NAMESPACE. However, now that R 4.0.0 doesn't look in the global namespace for S3 methods, this no longer worked.

As per duckmayr's answer to my [StackOverflow question](https://stackoverflow.com/questions/61482561/whats-the-preferred-means-for-defining-an-s3-method-in-an-r-package-without-int), the answer comes from using `@exportS3Method package::generic_function` without an `@importFrom`. However, this fails unless the relevant package has already been loaded into the global namespace before a call to `roxygen2::roxygenise`. Within RStudio, this means that the Document option in the Build pane fails. Is there any chance of modifying the check that leads to the error `@exportS3Method` and `@exportS3Method generic` must be used with an S3 method' and therefore fails to include the relevant lines in NAMESPACE?

**Comment by hadley** [comment]
Can you please provide a reprex following the advice in https://github.com/r-lib/roxygen2/blob/master/.github/SUPPORT.md#making-a-reprex?

**Comment by NikNakk** [comment]
Thanks @hadley. I couldn't make this work using `roc_proc_text` so I've created a minimal package which is [here on GitHub](https://github.com/NikNakk/s3example).

There is only a single R file which has the contents:

```
#' @exportS3Method knitr::knit_print
knit_print.s3example <- function(x, ...) {
}
```

There are three workarounds. Firstly, if the second (optional) parameter is provided to `@exportS3Method`, i.e. `@exportS3Method knitr::knit_print s3example`, then it seems to work ok. Secondly, if the package is in the global namespace and `devtools::document()` is called from within that R session (rather than through the RStudio build tab), then it works fine. Thirdly, if the package is added to the 'Imports' section of DESCRIPTION and the `@importFrom' directive is used, then it also works (but in the process creates a dependency on the package providing the generic).

It may be that the best option for now is to direct package authors to use the two parameter form of `@exportS3Method` when they don't want to import the generic package. However, I would have thought it should be possible for `roxygen2` to work out the correct `S3method` directive for NAMESPACE without needing to have the package loaded.

**Comment by hadley** [comment]
(Note to self: when fixing this, also make sure to update namespace vignette with use of `exportS3method`)

**Comment by hadley** [comment]
Minimal reprex:

``` r
library(roxygen2)
roc_proc_text(namespace_roclet(), "
  #' @exportS3Method knitr::knit_print
  knit_print.s3example <- function(x, ...) {
  }
")
#> Warning: [<text>:2] @exportS3Method `@exportS3Method` and `@exportS3Method
#> generic` must be used with an S3 method
#> character(0)
```

<sup>Created on 2022-04-06 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
