### ISSUE TITLE
roclet definition

### ISSUE THREAD

**Issue by ramiromagno** [r-lib/roxygen2#1086]
Hi

I apologise if this is a silly question. But is the concept of a **roclet** defined anywhere in user-level documentation?

Roclet is mentioned everywhere in docs, but I could not find what it means... Is it the block of roxygen comments that lead to an .Rd file? Is it the function `rd_roclet()`? (because it's description reads: *This roclet is the workhorse of roxygen (...)*)

**Comment by hadley** [comment]
A roclet is the object that is responsible for generating a specific type of output like the `NAMESPACE` file or all the `.Rd` files.
