### ISSUE TITLE
How to create new tag for customising the existing section Description?

### ISSUE THREAD

**Issue by ramiromagno** [r-lib/roxygen2#1087]
Here is an example of what I am trying to achieve.

Here is a snippet of an roxygen comment block:

```
#' Rf_mkCharLenCE
#'
#' @description
#'
#' \Sexpr[results=rd, stage=render]{c3po:::badge('fnp')} \Sexpr[results=rd, stage=render]{c3po:::badge('c2r')} \Sexpr[results=rd, stage=render]{c3po:::badge('prot')}
#'
#' TODO
#'
#' @section Declaration:
#' ```
#' SEXP Rf_mkCharLenCE(const char *name, int len, cetype_t enc);
#' ```
```

Now, you see those three `\Sexpr` commands? They are analogous to those used, e.g., in rlang:

https://github.com/r-lib/rlang/blob/a90b04b9d6a17f1aabadaed357784efc22116d2a/R/eval-tidy.R#L1-L6

I use them to generate nice looking svg badges in my documentation.

![snap](https://user-images.githubusercontent.com/19862384/80589337-e2100800-8a11-11ea-9ae2-d8e8856cc612.png)

My question is: would it be possible to generate a new tag, say, `@badge` that accepts keywords and acts on them by generating the corresponding code described above? I mean something like:

```
#' @badge fnp c2r prot
```

in context:

```
#' Rf_mkCharLenCE
#'
#' @description
#'
#' @badge fnp c2r prot
#'
#' TODO
#'
#' @section Declaration:
#' ```
#' SEXP Rf_mkCharLenCE(const char *name, int len, cetype_t enc);
#' ```
```

From what I have read from the docs, creating a new tag creates a new section, so it would not apply to my case here because I need to edit an existing section, i.e., Description. So it seems to me that creating a new roclet is the way to go but I am not sure still if I can use that approach to change an existing section such as Description... I am sorry if I sound confusing, it could be because I am confused :) See also my other question about what is a roclet: https://github.com/r-lib/roxygen2/issues/1086.

**Comment by hadley** [comment]
You could use [inline R code](https://roxygen2.r-lib.org/articles/rd-formatting.html#inline-code).
