### ISSUE TITLE
Better errors for `@includeRmd`

### ISSUE THREAD

**Issue by lionel-** [r-lib/roxygen2#1089]
I'm debugging errors that occur during `#' @includeRmd`. The NAMESPACE file is emptied at each error, and I need to reset it manually. Would it make sense to restore it to its original contents in case of error?

**Comment by gaborcsardi** [comment]
Interesting. I think it would be even better not to touch it when the Rd roclet is running.

**Comment by lionel-** [comment]
```r
#' Stop
#' @includeRmd "R/stop.Rmd"
#' @name stop
NULL
```

With stop.Rmd:

````md
```{r}
stop("foo")
```
````

Another case where that comes up is when I interrupt `document()` after it has emptied the NAMESPACE.

**Comment by lionel-** [comment]
By the way it might be less confusing to output "Emptying NAMESPACE" the first time, rather than "Writing NAMESPACE" twice.

**Comment by hadley** [comment]
I think the `@includeRmd` code probably needs a tryCatch?

**Comment by lionel-** [comment]
We'd want `document()` to fail if the Rmd fails unexpectedly though?

**Comment by hadley** [comment]
I think it would emit a warning, like how other tags "fail"

**Comment by gaborcsardi** [comment]
IDK, this is a bit different, though, no? I _think_ I usually want an error when the dynamic code fails.

**Comment by hadley** [comment]
Maaaaybe, but I think it's better to be consistent.

**Comment by hadley** [comment]
It's more clear now that this should fail with a warning since that's what child documents do.
