### ISSUE TITLE
Set width before evaluating Rmd chunks

### ISSUE THREAD

**Issue by lionel-** [r-lib/roxygen2#1091]
And maybe other output-affecting options like `digits`. This way all developers use the same settings.

**Comment by gaborcsardi** [comment]
Maybe we could add an `options` config parameter, with some reasonable defaults?

**Comment by lionel-** [comment]
Maybe we should display 4 rows of tibble by default. This is less distracting in examples since the data is rarely relevant, most of the time you want to show the structure of the output. Also more examples fit on one screen this way.

**Comment by lionel-** [comment]
May also want to set common knitr options:

```
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

**Comment by hadley** [comment]
Looks like this is now implemented.
