### ISSUE TITLE
include is_roxygen2()

### ISSUE THREAD

**Issue by maxheld83** [r-lib/roxygen2#1095]
Now that {roxygen2} includes amazing things like `@includeRmd`, I sometimes want to run different code depending on whether it is run from inside {roxygen2}.
(For a far-fetched example, I need to avoid `>` block quotes in some `knit_print()` method whenever it is called inside roxygen2, because roxygen2 / `*.Rd` does not support block quotes).

It'd be nice to easily capture this kind of stuff with a `is_roxygen2()`.

This is different from `\dontrun`, which only applies to `@examples`.

**Comment by gaborcsardi** [comment]
Sounds good. It could be like `pkgdown::in_pkgdown()`:

```r
    identical(Sys.getenv("IN_PKGDOWN"), "true")

```
