### ISSUE TITLE
Update table summarizing when examples are run?

### ISSUE THREAD

**Issue by maelle** [r-lib/roxygen2#1096]
Should [this handy table](https://roxygen2.r-lib.org/articles/rd.html#functions) be updated?

Cf https://github.com/r-lib/devtools/issues/2216#issuecomment-619707307 (h/t https://community.rstudio.com/t/r-cmd-check-r-4-0-0-now-runs-donttest-how-to-proceed-with-long-running-examples/64493)

**Comment by gaborcsardi** [comment]
Maybe that table should have a column for CRAN incoming tests?
