### ISSUE TITLE
What if I don't want a function being identified as S3 method

### ISSUE THREAD

**Issue by zhenglei-gao** [r-lib/roxygen2#1098]
I have wrote a package containing function names like `plot.modList`, which was identified as S3 method functions automatically. How can I make it just a simple function? Do I have to rename them? 

```
S3method(plot,edList)
S3method(plot,modList)
````

**Comment by gaborcsardi** [comment]
I assume these are exported functions. You can do this:

```r
#' @export plot.edList
#' @export plot.modList
```

This said, I suggest that you change the dots to underscores, to avoid ambiguities, unless the renaming breaks existing code.

**Comment by zhenglei-gao** [comment]
@gaborcsardi  Thanks. Suggestions taken, I used too many times before putting them into a package.
