### ISSUE TITLE
Bug: Files with 'install_' in filename do not get exported

### ISSUE THREAD

**Issue by richelbilderbeek** [r-lib/roxygen2#1101]
I discovered that function with `install_` in the name do not get exported anymore, since an update approx 5 hours ago (approx 7:00 Amsterdam time).

It can be shown by [this commit](https://github.com/richelbilderbeek/mhcnuggetsr/commit/44cd746168623cc515f2a507bdda1012546951bf), where I rename functions ending with `install_` to `installl_` (with triple-l). Suddenly, they get exported as well!

Good luck fixing this :+1: 

Here is an example function from my code:

```{r}
#' Something
#' @export
installl_mhcnuggets <- function() {
  # ...
}
```

**Comment by gaborcsardi** [comment]
Wow! It seems that the function names do not matter, but the file names do. As a workaround I suggest you use dashes in the file names, instead of underscores: `R/install-mhcnuggets.R`. Dashes are better practice than underscores, anyway.

**Comment by richelbilderbeek** [comment]
Well spotted: title should be 'Filenames with 'install_' are not exported'. Thanks :+1:

**Comment by gaborcsardi** [comment]
It happens because you are ignoring these files: https://github.com/richelbilderbeek/mhcnuggetsr/blob/develop/.Rbuildignore#L11
You probably want to add a `^` prefix and a `$` suffix, when specifying file names there.

**Comment by richelbilderbeek** [comment]
@gaborcsardi well spotted, thanks for the help and sorry for the noise :+1:

**Comment by gaborcsardi** [comment]
No problem, it happens. :)
