### ISSUE TITLE
S4 methods roxygen2

### ISSUE THREAD

**Issue by ejosymart** [r-lib/roxygen2#1105]
I just finished some minor updates to an R package I've had on CRAN for a few years (haven't had to update in a month). My package passes Check on my local machine, but it just bounced back from CRAN with the message

"S4 exports specified in 'NAMESPACE' but not defined in package..."

I use roxygen2 to build my package NAMESPACE and don't have any S4 exports that I'm aware of.

Perhaps this might be related to changes in R version 4.0.0 or in related to roxygen2?

Thanks

**Comment by gaborcsardi** [comment]
Answered on the mailing list: https://www.mail-archive.com/r-package-devel@r-project.org/msg05436.html
