### ISSUE TITLE
Markdown links need to link to the file instead of the topic now

### ISSUE THREAD

**Issue by gaborcsardi** [r-lib/roxygen2#1108]
Following the change in https://github.com/wch/r-source/commit/f27cbf1a52a31cd9b9676340394946a22041a4ae

This was discussed in #707, but the situation is different now, with the check added.

**Comment by markfairbanks** [comment]
Is there a workaround for this in the meantime?

**Comment by gaborcsardi** [comment]
> Is there a workaround for this in the meantime?

#1109
