### ISSUE TITLE
template warning "unvollständige letzte Zeile" / "incomplete final line"

### ISSUE THREAD

**Issue by JanaJarecki** [r-lib/roxygen2#1110]
Hi,

I am using a template and get a warning about an incomplete last line when I run `devtools::document()`.

    1: In readLines(icon, 1) :                                                               
      unvollstõndige letzte Zeile in 'C:\Users......./man-roxygen/my_template.R' gefunden

The content of my template is nothing special:
    
    #' @param test A string.

*But* I am using the `Roxygen: list(markdown = TRUE)` option in my description.

Roxygen2 v 7.1.0

    R version 3.6.3 (2020-02-29)                                                             
    Platform: x86_64-w64-mingw32/x64 (64-bit)                                                
    Running under: Windows 10 x64 (build 18363)                                              
                                                                                             
    Matrix products: default                                                                 
                                                                                             
    locale:                                                                                  
    [1] LC_COLLATE=German_Switzerland.1252  LC_CTYPE=German_Switzerland.1252                 
    [3] LC_MONETARY=German_Switzerland.1252 LC_NUMERIC=C                                     
    [5] LC_TIME=German_Switzerland.1252                                                      
                                                                                             
    attached base packages:                                                                  
    [1] stats     graphics  grDevices utils     datasets  methods   base                     
                                                                                             
    other attached packages:                                                                 
    [1] cognitivemodels_0.0.9 devtools_2.3.0        usethis_1.6.1                            
    [4] testthat_2.3.2

**Comment by gaborcsardi** [comment]
Don't you just need a final newline character at the end of the `my_template.R` file?

**Comment by JanaJarecki** [comment]
Perfect, issue solved :D
