### ISSUE TITLE
Failures with inline R code in multiline @param tags

### ISSUE THREAD

**Issue by salim-b** [r-lib/roxygen2#1112]
Consider the following `@param` tag:

```r
#' @param some_param Some dynamically generated parameter documentation whose last 2 static
#'   chars are swallowed and instead contains a spurious ")'" at the end: 12`r paste0("test")`
```

When roxygen2 (latest 7.1.1.9001) renders this to `.Rd`, it **swallows the last two "static" characters** (`12`) **and outputs two additional characters** (``)` ``) at the end of the parsed inline R code which shouldn't be there:

```rd
\item{some_param}{Some dynamically generated parameter documentation whose last 2 static
chars are swallowed and instead contains a spurious ")'" at the end: test)`}
```

Instead, it should actually produce this `.Rd`:

```rd
\item{some_param}{Some dynamically generated parameter documentation whose last 2 static
chars are swallowed and instead contains a spurious ")'" at the end: 12test}
```

The underlying issue looks like some "off-by-two"-error. The inline R code

```
... at the end: 12`r paste0("test")`
```

should be parsed to:

```
... at the end: 12test
```

but wrongly becomes:

```
... at the end: test)`
```

<sub>
<em>I simplified the inline R code in the above example as much as possible, thus it doesn't make much sense. What I was originally trying to do is auto-generate some doc in <a href="https://gitlab.com/salim_b/r/pkgs/pkgsnip">pkgsnip</a> like this:</em>

```r
#' @param snippet The name of a snippet. Possible values include:
#'   `r paste0('- ``"', ls_file_snips()$name, '"``')`
```
</sub>

**Comment by gaborcsardi** [comment]
Reprex:

``` r
roxygen2::roc_proc_text(roxygen2::rd_roclet(), "
  #' Title
  #' 
  #' @param some_param Foo 
  #'   bar 12`r paste0(\"test\")`
  #' @md
  foo <- function(some_param) {}
")
#> $foo.Rd
#> % Generated by roxygen2: do not edit by hand
#> % Please edit documentation in ./<text>
#> \name{foo}
#> \alias{foo}
#> \title{Title}
#> \usage{
#> foo(some_param)
#> }
#> \arguments{
#> \item{some_param}{Foo
#> bar test)`}
#> }
#> \description{
#> Title
#> }
```

<sup>Created on 2020-06-14 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by salim-b** [comment]
Update: I just realized that the **indentation** of the second line is central to the bug.

No indentation, no problem:

``` r
roxygen2::roc_proc_text(roxygen2::rd_roclet(), "
  #' Title
  #' 
  #' @param some_param Foo 
  #' bar 12`r paste0(\"test\")`
  #' @md
  foo <- function(some_param) {}
")
#> $foo.Rd
#> % Generated by roxygen2: do not edit by hand
#> % Please edit documentation in ./<text>
#> \name{foo}
#> \alias{foo}
#> \title{Title}
#> \usage{
#> foo(some_param)
#> }
#> \arguments{
#> \item{some_param}{Foo
#> bar 12test}
#> }
#> \description{
#> Title
#> }
```

<sup>Created on 2021-09-09 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

OTOH, we can escalate the problem with *more* indentation:

``` r
roxygen2::roc_proc_text(roxygen2::rd_roclet(), "
  #' Title
  #' 
  #' @param some_param Foo 
  #'                      bar 12`r paste0(\"test\")`
  #' @md
  foo <- function(some_param) {}
")
#> $foo.Rd
#> % Generated by roxygen2: do not edit by hand
#> % Please edit documentation in ./<text>
#> \name{foo}
#> \alias{foo}
#> \title{Title}
#> \usage{
#> foo(some_param)
#> }
#> \arguments{
#> \item{some_param}{Foo
#> test     bar 12\verb{r "test"}}
#> }
#> \description{
#> Title
#> }
```

<sup>Created on 2021-09-09 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Appears to me there's some erroneous whitespace stripping or the like involved when inline code is replaced with the evaluated strings.
