### ISSUE TITLE
roxygen doesn't recognize tag

### ISSUE THREAD

**Issue by kurt-o-sys** [r-lib/roxygen2#1117]
I have plumber (dev) installed and when I'm running `devtools::check()` or `devtools::document()`, I ge t a warning, which seems roxygen related:

```
Warning: [...R:15] @serializer unknown tag
```

Other tags are not a problem, but this one is. The tag is functioning well, so it's not that it doesn't exist... Am I missing something?

**Comment by gaborcsardi** [comment]
`@serializer` is not a roxygen2 tag, as far as I know. Is that something plumber specific?

**Comment by kurt-o-sys** [comment]
probably, and it's up to plumber to expose those tags to devtools? (It's not so that roxygen tries to identify all existing tags of all packages?)

**Comment by gaborcsardi** [comment]
Maybe you just need to use `#*` instead of `#'`, like in the examples, e.g. https://github.com/rstudio/plumber/blob/095b5377812d60664e6cc955b1417c4cf46d44c2/inst/examples/09-content-type/plumber.R#L1

**Comment by kurt-o-sys** [comment]
Right, sorry. That seems to work fine. My bad.

**Comment by gaborcsardi** [comment]
No worries, it happens.
