### ISSUE TITLE
Three multicrispr functions are no longer getting exported

### ISSUE THREAD

**Issue by bhagwataditya** [r-lib/roxygen2#1118]
The functions `add_context`, `add_efficiency`, and `filter_efficient` in [multicrispr](https://gitlab.gwdg.de/loosolab/software/multicrispr) are no longer being exported after running devtools::document()
![image](https://user-images.githubusercontent.com/5953568/84901672-1ae06b00-b0ac-11ea-8440-35dacf0e87bf.png)

I don't understand why, because neither source code nor documentation changed. I am using R 4.0.1. on windows and roxygen7.1.0. Does this provide you sufficient information to reproduce? Would you like to do any other steps to make it easier to reproduce from your side?

![image](https://user-images.githubusercontent.com/5953568/84901927-685cd800-b0ac-11ea-89ef-6ac0a9ffff55.png)

Many thanks for your help - I off course use roxygen2 and devtools all the time, and am very grateful for it being around!

**Comment by gaborcsardi** [comment]
> Does this provide you sufficient information to reproduce?

It does not, but https://github.com/loosolab/multicrispr/ does.

You told R to ignore all files that match the `.ci` regular expression: https://github.com/loosolab/multicrispr/blob/d59c07c89db8fb1aac155c3c6564e9b605883e4a/.Rbuildignore#L3

So roxygen will also ignore the `08_add_efficiency.R` file when building the documentation.

**Comment by gaborcsardi** [comment]
This is a good catch, `.Rbuildignore` has regular expressions and not shell globs. You can use `glob2rx()` to get a regular expression that does the same. E.g. in your case you probably wanted one of these?

```r
> glob2rx(".ci")
[1] "^\\.ci$"

> glob2rx("*.ci")
[1] "^.*\\.ci$"
```

**Comment by bhagwataditya** [comment]
Ooh....thankyou Gabor, you're a genius! And you prevented me from going grazy :-D.
Will close this issue now :-)
