### ISSUE TITLE
dontshow and if statements

### ISSUE THREAD

**Issue by jwijffels** [r-lib/roxygen2#1119]
I have this documentation chunk where I'm trying to hide with dontshow the require statement.
If I do this nothing is shown in the documentation.
How do I specify this correctly

```
#' \dontshow{
#' if(require(BTM)){
#' }
#'
#' library(BTM)
#' data(example_btm, package = 'textplot')
#' example_btm
#' str(example_btm)
#'
#' \dontshow{
#' }
#' }
```

As this gives

```
\examples{
\dontshow{
if(require(BTM)){
}

library(BTM)
data(example_btm, package = 'textplot')
example_btm
str(example_btm)

\dontshow{
}
}
}

```

Indicating the dontshow accounts for all code

**Comment by gaborcsardi** [comment]
This is not a roxygen2 issue, roxygen2 just puts that text into the Rd file. The `if(require(BTM)){` statement is closed in the next line. You need to escape the opening brace of the `if`: 
```r
\dontshow{if (require(BTM)) \{}
```
and similarly for the other one. Reprex below.

You might also want to use `withAutoprint()`. Here is an example:
https://github.com/r-hub/pkgsearch/blob/5267f095b0986357e5713795ad16e674be09e896/man/cran_package.Rd#L22
generated by
https://github.com/gaborcsardi/roxygenlabs#conditional-examples

``` r
roxygen2::roc_proc_text(roxygen2::rd_roclet(), "
#' @name foo
#' @title Title
#' @examples
#' \\dontshow{
#' if(require(BTM))\\{
#' }
#'
#' library(BTM)
#' data(example_btm, package = 'textplot')
#' example_btm
#' str(example_btm)
#'
#' \\dontshow{
#' \\}
#' }
NULL
")
#> $foo.Rd
#> % Generated by roxygen2: do not edit by hand
#> % Please edit documentation in ./<text>
#> \name{foo}
#> \alias{foo}
#> \title{Title}
#> \description{
#> Title
#> }
#> \examples{
#> \dontshow{
#> if(require(BTM))\{
#> }
#> 
#> library(BTM)
#> data(example_btm, package = 'textplot')
#> example_btm
#> str(example_btm)
#> 
#> \dontshow{
#> \}
#> }
#> }
```

<sup>Created on 2020-06-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by jwijffels** [comment]
Right! Thanks for help! Perfect solution. Sorry to have bothered asking here.

**Comment by gaborcsardi** [comment]
No worries. The (non-)escaping of roxygen + Rd is far from trivial. I need to re-understand it every time I start working on roxygen...

**Comment by jwijffels** [comment]
Thanks again. Don't want to bug you with some more questions but do you happen to know if there is a similar statement as \dontrun which you can incorporate in Sweave-style vignettes. Such that I can do \dontshow{if (require(BTM)) \{} in a Sweave code chunk? If not, either way thanks already for the help.

**Comment by gaborcsardi** [comment]
I haven't used Sweave for a while. In knitr you can have a chunk option for this, e.g. 
````
```{r eval = requireNamespace("BTM", quietly = TRUE)}
blah
```
````

IFAIR Sweave also has an `eval` chunk option, so you can probably do the same.

**Comment by jwijffels** [comment]
Yes, was aware of that for knitr but for Sweave thought it was non-dynamic. 
Anyhow many thanks for the inputs. Really helpfull! Have a nice day.
