### ISSUE TITLE
Cannot document S3 method for `{` class

### ISSUE THREAD

**Issue by billdenney** [r-lib/roxygen2#1127]
I was trying to document an S3 method for the `{` class, and when I tried to load the documentation, it failed due to what I think was the fact that the `{` was not escaped.

Specifically, I think that this line is the problem:

```
#> \method{foo}{`{`}()
```

and I think it should be escaped as

```
#> \method{foo}{`\\{`}()
```

``` r
library(roxygen2)
roc_proc_text(rd_roclet(), "
  #' Title
  #' @export
  foo <- function() {UseMethod('foo')}
  #' @describeIn foo bar
  `foo.{` <- function() {}
"
)
#> $foo.Rd
#> % Generated by roxygen2: do not edit by hand
#> % Please edit documentation in ./<text>
#> \name{foo}
#> \alias{foo}
#> \alias{foo.{}
#> \title{Title}
#> \usage{
#> foo()
#> 
#> \method{foo}{`{`}()
#> }
#> \description{
#> Title
#> }
#> \section{Methods (by class)}{
#> \itemize{
#> \item \code{{}: bar
#> }}
```

<sup>Created on 2020-06-26 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Related to nlmixrdevelopment/nlmixr#334

**Comment by billdenney** [comment]
As an addition, this line is also likely to be problematic due to an un-escaped `{`: `\item \code{{}: bar`

**Comment by hadley** [comment]
Thanks for filing this issue! Unfortunately, I think it's unlikely to ever rise to the top of our to do list due to the extreme rarity of non-syntactic S3 class names. Even though I'm closing this issue, I really appreciate the feedback, and hope you'll continue to contribute in the future 😄
