### ISSUE TITLE
Custom Tag - Access to function call

### ISSUE THREAD

**Issue by Salatbesteck** [r-lib/roxygen2#1129]
I was checking the vignette for extending roxygen with a custom tag. 
Is there a way to access the *package name* and the *function name* inside the tag parser method (see below).
I would like to use this for generating parts of the content automatically.

```{r}
roxy_tag_parse.roxy_tag_mytag <- function(x) {
  parsed <- strsplit(x$raw, split = '|', fixed = TRUE)
  
  x$val <- list(
    fun = "functionObject",
    pkg = "PackageName"
    text = parsed
  )
  x
}
```
Can that be achieved by modifying the tag parser, or is a new rocelt required?

**Comment by gaborcsardi** [comment]
The package name is in

```r
roxy_meta_get("current_package")
```

The function name is a bit trickier, because a manual page may document several functions, and a piece of the documentation can be copied to several pages using roxygen2's inheritance mechanism. What would you do in these cases? 

If you want to modify the generated Rd files, then it is best to do this without another roclet. If you want to generate some additional files, then a new roclet is better I think.

**Comment by Salatbesteck** [comment]
Thanks for the quick help. 

The plan is to modify the generated Rd files. At the moment I am only interested in the object followed by the block and it would be sufficient to ignore contributions to this manual page by other blocks. The best would be of course to get all object names (function/data), which are contributing to this specific manual page.

Any recommendations on how to implement this kind of functionality in the parser?

**Comment by mstr3336** [comment]
Hi there! 
I'm interested in doing something similar in one of my projects, and I'm curious to know how you got on in your efforts to accomplish this. 

A potential cludge to give your tag the calling function name may be to simply allow the documenting function name to be given directly to your tag, as in

(I'm also learning how this functionality works, so bear with me if I have messed up the API)

```r
#' foo is a function
#' @roxy_tag_mytag foo bar|baz
#' @export
foo <- function()
```

```r
roxy_tag_parse.roxy_tag_mytag <- function(x) {
name_pat <- "^\w\s+"
function_name <- stringr::str_subset(x$raw, name_pat)

parsed <- stringr::str_subset(x$raw, name_pat, invert = T)
parsed <- strsplit(parsed, split = '|', fixed = TRUE)
  
  x$val <- list(
    fun = function_name,
    pkg = roxy_meta_get("current_package"),
    text = parsed
  )
  x
}
```

I haven't tested this, and it is a cludge that introduces some maintenece burden in ensuring your `my_tag` name is synchronized with the function name, should you change the function name, but I think as far as documentation burdens go that's fairly light.

I'm curious to know what you are trying to achieve? 

Presently, I'd like to use custom tags on my functions to help centralize the documentation of my output columns to a single file, or potentially a collection of files,  as long as it's relatively easy to index. 

My project involves a package that generates / runs a [drake](https://github.com/ropensci/drake/) plan, and I'm working on a way to document the dataset as well as the functions.

**Comment by hadley** [comment]
Unfortunately we just don't have the time to help explain the roxygen2 internals, mostly because they are only ever briefly loaded up into my head, when I'm actually working on roxygen2.
