### ISSUE TITLE
Document an argument that is not explicitly specified in a function

### ISSUE THREAD

**Issue by Jiefei-Wang** [r-lib/roxygen2#1133]
Hi, 

I am wondering how to correctly document an argument that is not shown in a function. For example

```
test <- function(x, ...){
    args <- list(...)
    args$A
}
```
The function `test` has an optional argument `A`, but if I directly document it using `@param`, R check warns me `Documented arguments not in \usage in documentation object 'test'`. If I manually add the usage via `@usage test(x, A, ...)`, I get `Argument names in docs not in code`. Is there any way to solve the warning via a tag in roxygen?

Best,
Jiefei

**Comment by gaborcsardi** [comment]
This is not up to roxygen2. `R CMD check` does not allow it AFAIK. The signature of the function and the documentation must match exactly.

I suggest you write something like this instead:

```r
test <- function(x, A = NULL, ...){
  if (!is.null(A)) {
    ...
  }
  ...
}
```

**Comment by Jiefei-Wang** [comment]
Thanks for the quick response! Glad to know R's restriction on it. I will follow your suggestions and change the code.

Best,
Jiefei
