### ISSUE TITLE
NAMESPACE rewrite fails after fixing mistaken @import/@importFrom entry

### ISSUE THREAD

**Issue by BroVic** [r-lib/roxygen2#1137]
Hi, 

I made a mistake in my roxygen2 comments where I first removed the second argument for `importFrom()` alone, when I actually wanted to change it to `import()`. When I fixed the problem, NAMESPACE could only be rewritten manually--even after a session restart. 

Here's the code: If you change `#' @importFrom stats setNames` to `#' @importFrom stats` you rightly get this warning:
```r
devtools::document()

## Warning: [C:\Users\Admn\blah\R\blah-blah.R:58] 
## @importFrom  needs at least 2 words
```
When you fix the comment i.e. change it to `#' @import stats`, writing to NAMESPACE fails
```r
devtools::document()
## Error in asChar(ivars) : 
##  empty name in directive 'importFrom' in 'NAMESPACE' file
```
and can only be fixed by manually deleting this line
```
importFrom(stats,)
```

I'm using roxygen2 v7.1.1 and R 4.0.2 on Windows 10.

**Comment by gaborcsardi** [comment]
Yes, I think this is "normal". If you mess up something and `NAMESPACE` is corrupted, then just remove it and roxygen2 will re-create it.

Maybe we could catch the failure and tell people to do that.

**Comment by BroVic** [comment]
Yeah good idea. Thanks.
