### ISSUE TITLE
@noRd tag has no effect in presence of the @rdname tag in documenting internal functions

### ISSUE THREAD

**Issue by phargarten2** [r-lib/roxygen2#1141]
This is a duplicate of the question posted on StackOverflow. It is pasted below for convenience. 
(https://stackoverflow.com/questions/62943917/roxygen2-nord-tag-has-no-effect-in-presence-of-the-rdname-tag-in-documenting)

**Comment by phargarten2** [comment]
I am using **roxygen2** package to document my package. [As suggested by Hadley Wickham in section 7.8](https://style.tidyverse.org/documentation.html), 
> Internal functions should be documented with `#'` comments as per usual. Use the @noRd tag to prevent `Rd` files from being generated.

Often, I have internal functions in one R file and thus use the @rdname tag. Yet if I use the @noRd tag it has no effect. 

For instance, if you `roxygenize()` this file called "iloveAnimals", inside a package:

```{r}
#' @title Cats
#' @name iloveAnimals
#'
#' @description The following logical functions check if you love animals
#'
#' @param loveCats Logical; TRUE if you love Cats
#' @details
#'  loveCats: do you love cats
#' @rdname iloveAnimals
ilovecats <- function(loveCats){
  if(loveCats){
    print("you love cats")
  } else{
      print("you hate cats")
    }
}

#' @param loveBirds logical; TRUE if you love birds.
#' @details
#'  loveBirds: Do you love birds?
#' @rdname iloveAnimals
ilovebirds  <- function(loveBirds){
  if(loveBirds){
    print("you love birds")
  } else{
    print("you hate birds")
  }
}

#' @noRd
```
yields, within a package, 

```
roxygen2::roxygenize()
Writing NAMESPACE
Writing NAMESPACE
Writing iloveAnimals.Rd
```
This is surprising as the `Rd` file should not be written. The `Rd` file is written as if the @noRd tag has no effect. If @rdname is not used, the @noRd tag works and the `Rd` file is not written. There are two easy solutions: 
 1. Comment out the internal functions or 
 2. have one internal function per file to avoid using @rdname tag. 

However, these solutions violate the spirit of **roxygen2**.

**Comment by gaborcsardi** [comment]
Maybe I am missing something, but can't you just delete the `@rdname` tag? What is the point of it, if no file is generated, anyway?

**Comment by phargarten2** [comment]
If I understand correctly, I should document internal functions similarly to those exported. So, if I have multiple functions in one file, I should use the `@rdname` tag. I thought that the intent of the `@noRd` tag was to use one tag to prevent the generation of an `Rd` file.

**Comment by gaborcsardi** [comment]
@noRd means that you don't want an Rd file. @rdname specifies the name of
the Rd file to use. Which is useless if you don't want one. So I think you
can just delete the @rdname tags.

**Comment by phargarten2** [comment]
An R file that excludes the `@rdname` and `@name` tags still write the `Rd` file.  The `Rd` file is not written if I add `NULL` on the last line of the `R` file. Perhaps, the issue is not `@rdname` tag, but the `@name` tag is included.

**Comment by phargarten2** [comment]
@gaborcsardi, thank you.  I understand that `@rdname` (and `@name`) makes no sense in light of the functionality of `@noRd`.  I got confused from the Hadley Wickham's tidy-verse style guide that it should be included:  "Internal functions should be documented with #' comments as per usual".   Also, the style guide doesn't mention including `NULL` either.

**Comment by gaborcsardi** [comment]
> The Rd file is not written if I add NULL on the last line of the R file.

I am not sure what you mean, I am afraid that you have to show an example. If a `@noRd` block creates an `.Rd` file, then that is a bug.

**Comment by phargarten2** [comment]
For instance, if you `roxygenize()` this file called "iloveAnimals", inside a package:

```{r}
#' @title Cats
#' @name iloveAnimals
#'
#' @description The following logical functions check if you love animals
#'
#' @param loveCats Logical; TRUE if you love Cats
#' @details
#'  loveCats: do you love cats
#' @rdname iloveAnimals
ilovecats <- function(loveCats){
  if(loveCats){
    print("you love cats")
  } else{
      print("you hate cats")
    }
}

#' @noRd
```
yields, within a package, 

```
roxygen2::roxygenize()
Writing NAMESPACE
Writing NAMESPACE
Writing iloveAnimals.Rd
```

Removing the `@name` tag still creates a `Rd` file. 
```{r}
#' @title Cats
# #' @name iloveAnimals
#'
#' @description The following logical functions check if you love animals
#'
#' @param loveCats Logical; TRUE if you love Cats
#' @details
#'  loveCats: do you love cats
#' @rdname iloveAnimals
ilovecats <- function(loveCats){
  if(loveCats){
    print("you love cats")
  } else{
      print("you hate cats")
    }
}

#' @noRd
```
yields, within a package, 

```
roxygen2::roxygenize()
Writing NAMESPACE
Writing NAMESPACE
Writing iloveAnimals.Rd
```

Removing the `@name` tag still creates a `Rd` file.  But, if you add `NULL` as the last line, the `Rd` file is not created.
```{r}
#' @title Cats
# #' @name iloveAnimals
#'
#' @description The following logical functions check if you love animals
#'
#' @param loveCats Logical; TRUE if you love Cats
#' @details
#'  loveCats: do you love cats
#' @rdname iloveAnimals
ilovecats <- function(loveCats){
  if(loveCats){
    print("you love cats")
  } else{
      print("you hate cats")
    }
}

#' @noRd
NULL
```
yields, within a package, 

```
roxygen2::roxygenize()
Writing NAMESPACE
Writing NAMESPACE
```

**Comment by gaborcsardi** [comment]
Roxygen blocks and roxygen tags apply to the expression _after_ them, so you'll need to put the `@noRd` in front of the expression you don't want the `.Rd` file for. Maybe you'll also have to remove `@rdname`, I don't know, but it us useless with `@noRd`, anyway:

```r
#' @title Cats
#' @name iloveAnimals
#'
#' @description The following logical functions check if you love animals
#'
#' @param loveCats Logical; TRUE if you love Cats
#' @details
#'  loveCats: do you love cats
#' @noRd

ilovecats <- function(loveCats){
  if(loveCats){
    print("you love cats")
  } else{
      print("you hate cats")
    }
}
```

See this for an alternative that only leaves the internal function out of the index: https://blog.r-hub.io/2019/12/12/internal-functions/#how-to-document-internal-functions

**Comment by phargarten2** [comment]
From a comment made in the equatiomatic issue above, here is another source to indicate the importance of documenting internal functions: 
https://blog.r-hub.io/2019/12/12/internal-functions/#how-to-document-internal-functions
