### ISSUE TITLE
Latex support in help page

### ISSUE THREAD

**Issue by chrk623** [r-lib/roxygen2#1142]
Are there any roxgen way to write equations in the help page? `\eqn` does not seem to support all latex commands.

```r
#' Hi
#' @description
#' \eqn{\frac{1}{2}}
#' 
#' \eqn{w_j}

hi = function() {
  return(1)
}
```

**Comment by gaborcsardi** [comment]
Use the two-argument form of `\eqn`, see the docs here: https://cran.r-project.org/doc/manuals/R-exts.html#Mathematics

**Comment by chrk623** [comment]
So it is able to display some latex commands like symbols but not the actual fraction?

![image](https://user-images.githubusercontent.com/31636428/87871836-045d6480-ca08-11ea-94df-4422778a652a.png)

**Comment by gaborcsardi** [comment]
In the PDF manual? In `\eqn{}{}` the first argument is processed by LaTex. So you would write something like 

```r
#' ... \eqn{\frac12}{1/2} ...
```

and the PDF will have the proper fraction and the HTML will have `1/2`.

**Comment by chrk623** [comment]
Thanks
