### ISSUE TITLE
Documenting private R6 fields ends up in the Public fields section

### ISSUE THREAD

**Issue by CGMossa** [r-lib/roxygen2#1145]
While attempting to document my R6 classes, I encountered this:
When documenting private fields, the field name suddenly appears in the public field's section of 
the documentation.

Here's an example

```r
#' An example
#'
#' Class only made to showcase an issue with R6 roxygen documentation
ClassWithPrivateFields <- R6::R6Class(
  classname = "ClassWithPrivateFields",
  private = list(
    #' @field .a_private_field that should be mostly hidden honestly
    .a_private_field = NA
  )
)

```

And the resulting `.Rd` file:

```rd
% Generated by roxygen2: do not edit by hand
% Please edit documentation in R/ClassWithPrivateFields.R
\name{ClassWithPrivateFields}
\alias{ClassWithPrivateFields}
\title{An example}
\description{
Class only made to showcase an issue with R6 roxygen documentation
}
\section{Public fields}{
\if{html}{\out{<div class="r6-fields">}}
\describe{
\item{\code{.a_private_field}}{that should be mostly hidden honestly}
}
\if{html}{\out{</div>}}
}
\section{Active bindings}{
\if{html}{\out{<div class="r6-active-bindings">}}
\describe{
\item{\code{.a_private_field}}{that should be mostly hidden honestly}
}
\if{html}{\out{</div>}}
}
\section{Methods}{
\subsection{Public methods}{
\itemize{
\item \href{#method-clone}{\code{ClassWithPrivateFields$clone()}}
}
}
\if{html}{\out{<hr>}}
\if{html}{\out{<a id="method-clone"></a>}}
\if{latex}{\out{\hypertarget{method-clone}{}}}
\subsection{Method \code{clone()}}{
The objects of this class are cloneable with this method.
\subsection{Usage}{
\if{html}{\out{<div class="r">}}\preformatted{ClassWithPrivateFields$clone(deep = FALSE)}\if{html}{\out{</div>}}
}

\subsection{Arguments}{
\if{html}{\out{<div class="arguments">}}
\describe{
\item{\code{deep}}{Whether to make a deep clone.}
}
\if{html}{\out{</div>}}
}
}
}
```

The above seem hard to understand, here's a screenshot:

![image](https://user-images.githubusercontent.com/1063624/89227278-afac1300-d5dd-11ea-98b0-53554c2c3a2b.png)

**Comment by gaborcsardi** [comment]
Where do you want the documentation of the private fields go?

**Comment by CGMossa** [comment]
Honestly, I think `Private Fields` as a section would be fine. It doesn't need to be more elaborate than this.
Or they shouldn't appear shouldn't appear at all. 
Maybe `Internal fields` sounds more poignant and not easy to confuse with public fields.
Also, I saw that I also got a warning that these private fields are not known. So there's that..

**Comment by gaborcsardi** [comment]
Putting the documentation of private fields in the manual is not currently supported. The manual is for the end user, and the end user has no access to these fields, they are not part of the public API of the class.

**Comment by CGMossa** [comment]
That's fine. Then they should not be included anyways. 
It would still be nice to keep these annotations, if someone ever makes a language serverfor R, that then can handle showing the documentation on the fly when someone jams in `private$.`.

**Comment by greg-minshall** [comment]
currently (roxygen2 7.1.1) i get errors (or warnings, or notices, ...) when writing documentation for things in R6 private fields.  i like using roxygen2 as a template for writing consistent documentation, for public/exported as well as private/non-exported functions/fields.

for me, it would be great to parse and complain about syntax errors, and otherwise ignore private/non-exported.

(so, this applies to non-R6 documentation of non-exported functions from my package, say -- i don't think there is a notice, but i do think they end up being available for `> ?nonExportedFunctionFoo`, which doesn't seem right.)

thanks for it!

**Comment by hadley** [comment]
Thanks for filing this issue! Unfortunately, I don't think it's a good fit for this package: developing good software requires relentless focus, which means that we have to say no to many good ideas. Even though I'm closing this issue, I really appreciate the feedback, and hope you'll continue to contribute in the future 😄
