### ISSUE TITLE
Enable non-R knitr engines

### ISSUE THREAD

**Issue by nbenn** [r-lib/roxygen2#1149]
I'm trying to include a TikZ image in the docs of a package of mine. While looking at my options, i was delighted to see that `roxygen2` supports `knitr` code chunks. Combined with the `tikz` engine support of `knitr` I thought I had all I needed to make this work. Unfortunately, currently there is a quite restrictive check in place for what is considered a `knitr` code chunk

https://github.com/r-lib/roxygen2/blob/c73def498f29783044fe50865f22c2482f80942d/R/markdown.R#L73-L77

Playing around with this a bit, I was seamlessly able to generate my TikZ image from code simply by relaxing this check a bit by including other `knitr` engines as reported by `knitr::knit_engines$get()`.

```r
markdown_engine_regexp <- function() {
  opts <- c("r", names(knitr::knit_engines$get()))
  paste0("^\\{(", paste(opts, collapse = "|"), ")[, \\}]")
}

is_markdown_code_node <- function(x) {
  info <- xml_attr(x, "info")
  regx <- markdown_engine_regexp()
  str_sub(xml_text(x), 1, 2) == "r " ||
    (!is.na(info) && grepl(regx, info))
}
```
See also: https://github.com/r-lib/roxygen2/compare/master...nbenn:master

While I realize that `knitr` support in `roxygen2` is a new and somewhat experimental addition, I was wondering whether you are open to expanding this powerful feature by allowing non-R language engines to be run. I'm happy to submit a PR if this is the case.

**Comment by hadley** [comment]
@nbenn just to be clear, you're suggesting that we just need to relax our restriction a little and more knitr engines should work?

**Comment by nbenn** [comment]
Yes, that was precisely my suggestion. Currently knitr chunks are identified by checking whether some first 3 characters are in `c("{r ", "{r}", "{r,")`, thereby only allowing the `"r"` knitr engine. I think this could be relaxed to further knitr engines (maybe even all available), making possible for example the inclusion of a TikZ figure in roxygen2 generated docs (which I personally would find an awesome feature).

**Comment by gaborcsardi** [comment]
I think it is fine to allow other engines as well for code fences. Inline code is more problematic, though.

**Comment by gadenbuie** [comment]
Sorry, I've since realized the missing code I'm seeing is actually #1350

**Comment by gadenbuie** [comment]
Still, `verbatim` could be useful since it would allow you to store the Rmd snippet somewhere and then include it via the `file` chunk

````
#' ```{verbatim file="man/fragments/example.Rmd"}
#' ```
````

````
<!-- man/fragments/example.Rmd -->
```{r}
# comment
this <- 10
is <- this + 10
good <- this + is
```
````

**Comment by cderv** [comment]
@gadenbuie the `embed` engine would be a good fit here too - same as `verbatim` but adds a highlighting language to the chunk 

````r
```{embed}
man/fragments/example.Rmd
```
````

would produce 
`````markdown
````md
```{r}
# comment
this <- 10
is <- this + 10
good <- this + is
```
````

but maybe highlighting is not supported for Markdown in rogygen2 though
