### ISSUE TITLE
Feature request: inherit fun return to allow 'cherry-picking' items

### ISSUE THREAD

**Issue by ajabadi** [r-lib/roxygen2#1156]
It is really great that with `@inheritParams` you can inherit function parameters but then tailor some parameters to the specific function. I was wondering if that is a possibility with return (I tried but it failed). For instance, we have a range of `pca` functions (`pca`, `spca`, `ipca` etc.) and they all share a set of return items and only differ in a few. This goes for many other function families as well. It would eliminate a lot of manual work if I could just inherit from `pca` but change a few items in other functions in the family.

For instance, with the main function being:
```
#' @return \code{pca} returns a list with class \code{"pca"} containing the
#' following components:
#' \describe{
#' \item{ncomp}{the number of components to keep in the
#' calculation.} 
#' \item{explained_variance}{the percentage of variance
#' explained for each component.} 
#' \item{cum.var}{the cumulative percentage of variances
#' explained.}
#' \item{iter}{the number of iterations needed to reach convergence
#' for each component.} 
#' \item{rotation}{the matrix containing the sparse
#' loading vectors.} 
#' \item{x}{the matrix containing the principal components.}
#' }

pca <- function(){}
```
going from this for a family function:
```
#' @return \code{spca} returns a list with class \code{"spca"} containing the
#' following components:
#' \describe{
#' \item{ncomp}{the number of components to keep in the
#' calculation.} 
#' \item{explained_variance}{the percentage of variance
#' explained for each component.} 
#' \item{cum.var}{the cumulative percentage of variances
#' explained.}
#' \item{keepX}{the number of variables kept in each loading
#' vector.} 
#' \item{iter}{the number of iterations needed to reach convergence
#' for each component.} 
#' \item{rotation}{the matrix containing the sparse
#' loading vectors.} 
#' \item{x}{the matrix containing the principal components.}
#' }

spca <- function(){}
```
to this:
```
#' @return \code{spca} returns a list with class \code{"spca"} containing the
#' following components:
#' @inherit return pca
#' \describe{
#' \item{keepX}{the number of variables kept in each loading
#' vector.} 

spca <- function(){}
```

**Comment by gaborcsardi** [comment]
You can use roxygen's new inline code execution feature to generate the appropriate docs:

```
#' `r return_values(c("foo", "bar", "etc"))`
```

You create an internal `return_values()` function in your package, that can returns the appropriate code docs.

Alternatively you can also use templates to do this. AFAIR the plyr package is a good example for roxygen templates.

**Comment by ajabadi** [comment]
So I take it that it's too complicated to be implemented universally. Thanks for the tips, I'll certainly try that.

**Comment by ajabadi** [comment]
@gaborcsardi I could not find such an example in `plyr` repo. I was wondering if `@template` work within `@return` as well.
