### ISSUE TITLE
Consider adding 'LazyData: true' to DESCRIPTION if needed

### ISSUE THREAD

**Issue by hongooi73** [r-lib/roxygen2#1157]
R 4.0 introduced a stricter check on dataset documentation formatting. Now, when you have datasets in your package and you document them using the [recommended approach](https://roxygen2.r-lib.org/articles/rd.html#datasets), R CMD check will throw a warning:

```
> checking for code/documentation mismatches ... WARNING
  Variables with usage in documentation object 'foo' but not in code:
    'foo'
```

The reason is because roxygen2 generates Rd code that implicitly assumes `LazyData: true`, even though it might be absent from the DESCRIPTION file. In R 3.x the check ignored this, but R 4.0 picks it up. The result is questions like [here](https://stackoverflow.com/questions/57396392/warning-variables-with-usage-in-documentation-object-fang-but-not-in-code) and [here](https://community.rstudio.com/t/getting-check-warnings-with-dataset-documentation/83511).

The fix is easy: just add `LazyData: true` to DESCRIPTION. But it would be nice if roxygen could detect that a dataset object is being documented, and do this automatically if needed.

**Comment by sritchie73** [comment]
Just ran into this as well with a package already on CRAN that is now generating warnings. I ended up modifing the .Rd file manually and deleting the roxygen documentation as a work around to avoid LazyData: true.

**Comment by hadley** [comment]
`usethis::use_data()` does this in the dev version; I think it's more clearly the responsibility of usethis than roxygen2 since it's something that only needs to be done once.
