### ISSUE TITLE
roxygen2 is not populating Collate field anymore

### ISSUE THREAD

**Issue by FelixErnst** [r-lib/roxygen2#1161]
Hi,

I am not sure why and since when, but roxygen2 doesn't seam to populate or change the collate field anymore.

It is bit difficult to prepare an example using `reprex` so I hope you can follow the example below.

1. Creation of a new package:
```
devtools::create("new")
#> √ Creating 'new/'
#> √ Setting active project to '.../new'
#> √ Creating 'R/'
#> √ Writing 'DESCRIPTION'
#> Package: new
#> Title: What the Package Does (One Line, Title Case)
#> Version: 0.0.0.9000
#> Authors@R (parsed):
#>     * First Last <first.last@example.com> [aut, cre] (YOUR-ORCID-ID)
#> Description: What the package does (one paragraph).
#> License: `use_mit_license()`, `use_gpl3_license()` or friends to pick a
#>     license
#> Encoding: UTF-8
#> LazyData: true
#> Roxygen: list(markdown = TRUE)
#> RoxygenNote: 7.1.1
#> √ Writing 'NAMESPACE'
```

2. creating a `hello.R` with the following content in the `R` folder of the `new` packege:
```
#' some function
#'
#' this is a test.
#'
#' @export
some_function <- function(){
     "test"
}
```

3. Running roxygen
```
> roxygen2::roxygenize(roclets = c("collate", "namespace", "rd"))
First time using roxygen2. Upgrading automatically...
Loading new
Writing NAMESPACE
Writing NAMESPACE
Writing some_function.Rd
```

The result is that no collate entry is created in the DESCRIPTION file.

4. Adding the collate entry manually and adding another file

The DESCRIPTION file looks like this now:

```
Package: new
Title: What the Package Does (One Line, Title Case)
Version: 0.0.0.9000
Authors@R: 
    person(given = "First",
           family = "Last",
           role = c("aut", "cre"),
           email = "first.last@example.com",
           comment = c(ORCID = "YOUR-ORCID-ID"))
Description: What the package does (one paragraph).
License: `use_mit_license()`, `use_gpl3_license()` or friends to
    pick a license
Encoding: UTF-8
LazyData: true
Collate:
    'hello.R'
Roxygen: list(markdown = TRUE)
RoxygenNote: 7.1.1
```

and the new `hello2.R` file has the following contents:

```
#' some other function
#'
#' this is a test.
#'
#' @export
some_other_function <- function(){
    "test"
}
```

```
> roxygen2::roxygenize(roclets = c("collate", "namespace", "rd"))
Loading new
Adding files missing in collate: hello2.R
Writing NAMESPACE
Writing NAMESPACE
Writing some_other_function.Rd
```

However, the `hello2.R` entry is not written to the DESCRIPTION file.

Thanks for any advice.

Felix

<details><summary>SessionInfo</summary>
<pre>
> sessioninfo::session_info()
- Session info -------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 4.0.2 (2020-06-22)
 os       Windows 10 x64              
 system   x86_64, mingw32             
 ui       RStudio                     
 language en                          
 collate  German_Germany.1252         
 ctype    German_Germany.1252         
 tz       Europe/Berlin               
 date     2020-10-18                  

- Packages -----------------------------------------------------------------------------------------------------------------
 ! package     * version    date       lib source        
   assertthat    0.2.1      2019-03-21 [1] CRAN (R 4.0.2)
   backports     1.1.10     2020-09-15 [1] CRAN (R 4.0.2)
   callr         3.5.1      2020-10-13 [1] CRAN (R 4.0.3)
   cli           2.1.0      2020-10-12 [1] CRAN (R 4.0.3)
   commonmark    1.7        2018-12-01 [1] CRAN (R 4.0.2)
   crayon        1.3.4      2017-09-16 [1] CRAN (R 4.0.2)
   desc          1.2.0      2018-05-01 [1] CRAN (R 4.0.2)
   digest        0.6.25     2020-02-23 [1] CRAN (R 4.0.2)
   fansi         0.4.1      2020-01-08 [1] CRAN (R 4.0.2)
   glue          1.4.2      2020-08-27 [1] CRAN (R 4.0.2)
   knitr         1.30       2020-09-22 [1] CRAN (R 4.0.2)
   magrittr      1.5        2014-11-22 [1] CRAN (R 4.0.2)
 R new         * 0.0.0.9000 <NA>       [?] <NA>          
   pkgbuild      1.1.0      2020-07-13 [1] CRAN (R 4.0.2)
   pkgload       1.1.0      2020-05-29 [1] CRAN (R 4.0.2)
   prettyunits   1.1.1      2020-01-24 [1] CRAN (R 4.0.2)
   processx      3.4.4      2020-09-03 [1] CRAN (R 4.0.2)
   ps            1.4.0      2020-10-07 [1] CRAN (R 4.0.2)
   purrr         0.3.4      2020-04-17 [1] CRAN (R 4.0.2)
   R6            2.4.1      2019-11-12 [1] CRAN (R 4.0.2)
   Rcpp          1.0.5      2020-07-06 [1] CRAN (R 4.0.2)
   rlang         0.4.8      2020-10-08 [1] CRAN (R 4.0.3)
   roxygen2      7.1.1      2020-06-27 [1] CRAN (R 4.0.2)
   rprojroot     1.3-2      2018-01-03 [1] CRAN (R 4.0.2)
   rstudioapi    0.11       2020-02-07 [1] CRAN (R 4.0.2)
   sessioninfo   1.1.1      2018-11-05 [1] CRAN (R 4.0.2)
   stringi       1.5.3      2020-09-09 [1] CRAN (R 4.0.2)
   stringr       1.4.0      2019-02-10 [1] CRAN (R 4.0.2)
   testthat      2.3.2      2020-03-02 [1] CRAN (R 4.0.2)
   withr         2.3.0      2020-09-22 [1] CRAN (R 4.0.2)
   xfun          0.18       2020-09-29 [1] CRAN (R 4.0.2)
   xml2          1.3.2      2020-04-23 [1] CRAN (R 4.0.2)
</pre>
</details>

**Comment by gaborcsardi** [comment]
If you don't have an `@include` tag, then roxygen2 will not create a `Collate` field. Also, most packages don't need a Collate field, are you sure that you need one.

**Comment by FelixErnst** [comment]
Damn. I missed that... Thanks for this. I need it since R CMD check returns otherwise an error, if a collate field exists.

However, the message `Adding files missing in collate: hello2.R` is quite misleading. Any chance that might be changed in order to cover this case? In the situation described above, the DESCRIPTION file is incorrect and roxygen claims that it will correct it, but doesn't

**Comment by gaborcsardi** [comment]
The message might be misleading indeed, OTOH it is only misleading when you have an invalid `Collate` field that you created manually, and the package does not have any `@include` fields. So I would say that it is fairly rarely.

**Comment by FelixErnst** [comment]
Fair point and now I also found the man page in `?update_collate` describing this behavior. I removed the last `@include` tag and some time later R CMD check acted up, because I added some files. Well thats sorted now. Thanks again!

**Comment by halldc** [comment]
@gaborcsardi - I started encountering this situation after I accidentally removed the `@include` tag. It took me quite a while to find this GitHub issue and identify what had gone wrong. A more descriptive message would've definitely helped 🤞 😅
