### ISSUE TITLE
Export requests for extending packages: :::made_by, :::markdown :::markdown_if_active

### ISSUE THREAD

**Issue by matthewstrasiotto** [r-lib/roxygen2#1162]
It's pretty much in the title - I've implemented an extension package, & I've made use of these helpers because... they're useful

Unfortunately, however, this means that I'm never going to get my package to pass CRAN checks. 

Would you be open to exporting these?

**Comment by gaborcsardi** [comment]
`made_by` is literally a `paste0()` call, do you really need it? If you think that the message might change, that's true, OTOH if you need it, than maybe it could be "made by your extension", depending on how you want to use it?

Re the markdown ones, I am not sure if these are necessarily appropriate to export as is, but I agree that it would certainly make sense to provide some markdown formatting API to extensions.

**Comment by matthewstrasiotto** [comment]
yes, I just implemented my own made_by with a comment that it was intended to replicate roxygen2:::made_by 

Regarding the other 2, I understand what you mean, their names aren't as explicit as I might expect an API export, but I'd really appreciate some kind of exported markdown handler. 

For now, I'm okay with not using CRAN for my package, but hopefully I can publish it there eventually.

**Comment by hadley** [comment]
I think for now we'd prefer to keep this implementation internal; I don't think we want to lock ourselves into an exported interface.
