### ISSUE TITLE
Maintain the complete list of roxygen tags as Rd topics

### ISSUE THREAD

**Issue by lionel-** [r-lib/roxygen2#1165]
So they are included in the reference index:

![Screenshot 2020-11-05 at 13 41 03](https://user-images.githubusercontent.com/4465050/98244187-4d153b00-1f6f-11eb-94c6-edcfccbeea7d.png)

I often have trouble finding my way in the roxygen documentation. Having a list of clickable links for each tag would be very helpful I think.

Here is how the index above is implemented, with contents shared in both Rd topics and vignettes: https://github.com/lionel-/roxygen/commit/eb6f82a3

It requires a solution to that issue so that aliases starting with `@` are included in the reference index: https://github.com/r-lib/pkgdown/issues/1436

**Comment by maelle** [comment]
related: #1080
