### ISSUE TITLE
Italics in titles of functions docstrings

### ISSUE THREAD

**Issue by johanneswerner** [r-lib/roxygen2#1166]
I am currently developing an R package and I think I noticed something that might be a bug (or at least not intended as it occurs now). 

In some of my docstrings, I use italics in the first line with `\emph{...}`. 

If I check the function documentation with `?function_name`, they get rendered correctly, however if I look at all functions in the package and their description with `help(package = packagename)`, it appears like this

```
Documentation for package ‘packagename’ 

Help Pages

function_name     This is _the description_ of my function.
(...)
```

It looks to me like it is correctly translated to markdown but not translated on this page. Maybe this is not directly related to `roxygen2`, but I was not sure where else to mention it.

**Comment by gaborcsardi** [comment]
> If I check the function documentation with ?function_name, they get rendered correctly

I suppose this is in a web browser, or the RStudio help pane? Yes, that's a web page, so you can have proper italic text.

> however if I look at all functions in the package and their description with help(package = packagename)

I suppose this is in the terminal or the RStudio console? That is how `help()` renders `\emph{}` in a terminal. Terminals are much more limited than web pages.

> Maybe this is not directly related to roxygen2

That's correct, it has nothing to do with roxygen2. :) 

And there is also no good way to fix it, except writing a replacement to `utils::help()` that supports ANSI highlighting in real terminals (and RStudio). The rdoc package does that for help pages, but not for the list of functions AFAICT.
