### ISSUE TITLE
Does @exportS3Method have a confusing name?

### ISSUE THREAD

**Issue by MilesMcBain** [r-lib/roxygen2#1173]
From https://developer.r-project.org/Blog/public/2019/08/19/s3-method-lookup/:

> Using S3method(GEN, CLS) or S3method(GEN, CLS, FUN) registers function named, respectively, GEN.CLS or FUN for dispatch without the need for exporting it.

The name of this tag suggests the method is exported which is not true. It is registered and available for dispatch internally within the package namespace.

should it really be something more like @registerS3Method ?

**Comment by gaborcsardi** [comment]
Well, plain `@export` on an S3 method also generates `S3method()` in `NAMESPACE`, and we definitely don't want to change that, I think it is fine to call it `@exportS3method`, which does the same. 

Changing the name is a breaking change, btw. and keeping it and adding a new name seems overkill, considering that you very rarely need this function.
