### ISSUE TITLE
Should roxygen warn when S3 methods are not tagged with `@export`?

### ISSUE THREAD

**Issue by lionel-** [r-lib/roxygen2#1175]
It seems like it would help people with internal generics where it is not clear why you need to register. Cf r-lib/devtools#2293.

**Comment by hadley** [comment]
I think the biggest question is who's responsibility this is. Should it be roxygen2, devtools, or (maybe) usethis? I guess roxygen2 already has all the machinery to figure out if a function is a S3 method, so it probably makes the most sense here. It could be part of the namespace roclet that would just warn if it spotted unexported methods.
