### ISSUE TITLE
Brackets multiple lines apart can match each other

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/roxygen2#1195]
With the following chunk of documentation, the `[` seems to be matching the `]` a few lines down, resulting in garbled output

```r
#' My docs
#'
#' @description
#' Hello `[closed, open)`.
#'
#' Hello again `(open, closed]`.
#'
#' @name interval
NULL
```

<img width="691" alt="Screen Shot 2021-01-29 at 1 48 09 PM" src="https://user-images.githubusercontent.com/19150088/106315033-a3c1a680-6238-11eb-87fe-aac0be9c1f83.png">

The generated man file:

```
% Generated by roxygen2: do not edit by hand
% Please edit documentation in R/time-point.R
\name{interval}
\alias{interval}
\title{My docs}
\description{
Hello \verb{[closed, open)}.

Hello again \verb{(open, closed]}.

[closed, open)`.

Hello again `(open, closed]: R:closed,\%20open)\%60.\%0A\%0AHello\%20again\%20\%60(open,\%20closed
}
```

**Comment by DavisVaughan** [comment]
Possibly related to https://github.com/r-lib/roxygen2/issues/720?

I was just able to "fix" it with:

```
#' My docs
#'
#' @description
#' Hello \[closed, open).
#'
#' Hello again (open, closed].
#'
#' @name interval
NULL
```

**Comment by gaborcsardi** [comment]
It is best to write these kind of strings in non-markdown mode. Otherwise the markdown parser with interpret the brackets.

**Comment by DavisVaughan** [comment]
How do I turn off markdown mode to just write that string?

**Comment by DavisVaughan** [comment]
Oh maybe this? It seems to work for me

```r
#' My docs
#'
#' @description
#' Hello \code{[closed, open)}.
#'
#' Hello again \code{(open, closed]}.
#'
#' @name interval
NULL
```

**Comment by gaborcsardi** [comment]
Yeah, `\code{}` is perfect for a short piece of text, or `@noMd` turns it off for a chunk.

**Comment by DavisVaughan** [comment]
Thanks!
