### ISSUE TITLE
Think about methods for generics in suggested packages

### ISSUE THREAD

**Issue by hadley** [r-lib/roxygen2#1202]
e.g. https://dbplyr.tidyverse.org/reference/pivot_longer.tbl_lazy.html — the tidyr methods look different to the others because (as far as roxygen2 knows), they're not actually methods.

**Comment by hadley** [comment]
Need to standardise and/or document hack to load packages before `roxygenise()` is run: https://github.com/tidyverse/dtplyr/blob/master/DESCRIPTION#L42

**Comment by gaborcsardi** [comment]
There is
```
Roxygen: list(packages = "foobar")
```
now. Isn't that good?

**Comment by hadley** [comment]
I know I tried that for dtplyr and I'm pretty sure it didn't work.

**Comment by gaborcsardi** [comment]
Is that because you need to attach the package? I am fairly sure that the loading works.

**Comment by hadley** [comment]
Yeah, that's it.

**Comment by gaborcsardi** [comment]
We can attach `packages` then maybe?

**Comment by hadley** [comment]
Yeah, that should be relatively harmless I'd think.

**Comment by hadley** [comment]
The original goal of the packages field was to load packages that provided other roclets, but it doesn't seem like attaching these packages will cause harm and creating another field seems like overkill.
