### ISSUE TITLE
Links with URL encoded spaces

### ISSUE THREAD

**Issue by mikkmart** [r-lib/roxygen2#1209]
I'm not sure how to make a reprex for **roxygen2**, but here's an example file to reproduce the problem:

``` r
#' Test docs
#'
#' [link text](https://foo.bar/link%20target)
#'
#' @name test
NULL
```

When `rozygenize()`ing this file, I get a warning citing `@description mismatched braces or quotes` and the description block is not rendered. Replacing the URL encoded space (%20) in the link with a real space fixes the rendering but breaks the markdown so that it's no longer recognized as a link.

**Comment by mikkmart** [comment]
Acutally, `\href{https://foo.bar/link%20target}{link text}` works so I guess it's something to do with the markdown?

**Comment by gaborcsardi** [comment]
Yeah, it seems that you need to escape `%` in link targets currently:
```
#' [link text](https://foo.bar/link\%20target)
```
I would consider this a bug.
