### ISSUE TITLE
Consider relaxing digest::digest errormode to warn?

### ISSUE THREAD

**Issue by boshek** [r-lib/roxygen2#1211]
👋 . Thank you for this package. It has saved me countless hours over the years. 

On some windows machines with network drives, `digest::digest` errors because an R issue with `file.access`. The issue is described in this `digest` issue: https://github.com/eddelbuettel/digest/issues/49

One consequence of this is that `devtools::document` fails because it `digest::digest` is called in `roxygen2:::same_contents` with the error:
```
Error: The specified file is not readable: [path to package]\NAMESPACE
```
Would you consider a PR [here](https://github.com/r-lib/roxygen2/blob/c73def498f29783044fe50865f22c2482f80942d/R/utils.R#L101) to change that `digest` call to be `digest::digest(file = path, errormode = 'warn')`?

**Comment by hadley** [comment]
This feels out of scope for roxygen2, however we'll eventually switch to `rlang::hash_file()` once https://github.com/r-lib/rlang/issues/1134 has been implemented.
