### ISSUE TITLE
Mismatch between @name and \name

### ISSUE THREAD

**Issue by maelle** [r-lib/roxygen2#1212]
I hope I didn't miss another issue on the subject, "name" being a bad keyword to look for...

In usethis https://github.com/r-lib/usethis/blob/master/man/tidyverse.Rd I'd expect the `\name` of the Rd file to be tidyverse

```
\name{use_tidy_github_actions}
\alias{use_tidy_github_actions}
\alias{tidyverse}
```

but it's not, because `R/github-actions.R` is processed first I suppose, and only has `@rdname tidyverse`, not `@name tidyverse`. Is this the expected behavior?

Related https://github.com/r-lib/pkgdown/issues/1576 https://github.com/r-lib/usethis/issues/1392

**Comment by hadley** [comment]
Not sure there's anything we can do about this, but should definitely look into when we're next working on roxygen2.

**Comment by hadley** [comment]
I think this is expected, because the first block determines the name. But you can now use `@order` to override
