### ISSUE TITLE
Cannot create documentation for PackageC which depends on PackageB which calls a method from PackageA onLoad

### ISSUE THREAD

**Issue by PavelBal** [r-lib/roxygen2#1224]
Please excuse the weird title. I am having troubles building documentation with roxygen2 when my package depends on another package that depends... consider the following example.

## PackageA
- Has a function `helloA()` which prints `"Hello, world, this is package A!"`
- Does `print("Hello, its package A")` in it's `.onLoad()`

## PackageB
- Depends on `PackageA`
- Does `print("Hello, its package B")` in it's `.onLoad()`
- Calls `helloA()` in it's `.onLoad()`

Creating documentation using roxygen2 for this package yields

```
==> devtools::document(roclets = c('rd', 'collate', 'namespace'))

i Updating PackageB documentation
i Loading PackageB
[1] "Hello, its package A"
[1] "Hello, its package B"
[1] "Hello, world, this is package A!"
Documentation completed
```

## PackageC
- Depends on `PackageB`
- Does `print("Hello, its package C")` in it's `.onLoad()`

Creating documentation using roxygen2 for this package fails:

```
==> devtools::document(roclets = c('rd', 'collate', 'namespace'))

i Updating PackageC documentation
[1] "Hello, its package B"
i Loading PackageC
Error: Dependency package(s) 'PackageB' not available.
Backtrace:
    x
 1. +-base::suppressPackageStartupMessages(...)
 2. | \-base::withCallingHandlers(expr, packageStartupMessage = function(c) tryInvokeRestart("muffleMessage"))
 3. \-devtools::document(roclets = c("rd", "collate", "namespace"))
 4.   \-roxygen2::roxygenise(pkg$path, roclets)
 5.     \-roxygen2:::load_code(base_path)
 6.       \-pkgload::load_all(path, helpers = FALSE, attach_testthat = FALSE)
 7.         \-pkgload:::load_depends(path)
 8.           \-pkgload:::abort_for_missing_packages(res, depends$package)
Warning message:
In (function (dep_name, dep_ver = "*")  :
  Dependency package 'PackageB' not available.
Execution halted

Exited with status 1.
```

So it first attaches packageB without attaching packageA, therefore, calling `helloA()` in `.onLoad()` of packageB fails. If I remove `helloA()` from the `.onLoad()` of packageB, the output is:

```
==> devtools::document(roclets = c('rd', 'collate', 'namespace'))

i Updating PackageC documentation
i Loading PackageC
[1] "Hello, its package B"
[1] "Hello, its package A"
[1] "Hello, its package C"
Documentation completed
```

We clearly see that packageA is loaded **after** packageB.
- Adding packageA to the Depends of PackageC does not help
```
Depends:
    PackageA,
    PackageB
```

At the same time, building documentation without roxygen works:

```
> devtools::document()
i Updating PackageC documentation
i Loading PackageC
[1] "Hello, its package C"
```

**Comment by gaborcsardi** [comment]
Did you install packageB before calling `document()` in packageC? It seems to me that packageB is simple not installed.

**Comment by PavelBal** [comment]
Yes, packages A and B are installed prior to building package C. Building (and loading) package C without documentation works

```
==> Rcmd.exe INSTALL --no-multiarch --with-keep.source PackageC

* installing to library 'D:/Documents/R/win-library/4.0'
* installing *source* package 'PackageC' ...
** using staged installation
** R
** byte-compile and prepare package for lazy loading
[1] "Hello, its package A"
[1] "Hello, its package B"
[1] "Hello, world, this is package A!"
** help
*** installing help indices
  converting help for package 'PackageC'
    hello                                   html  
    finding HTML links ... done
** building package indices
** testing if installed package can be loaded from temporary location
[1] "Hello, its package A"
[1] "Hello, its package B"
[1] "Hello, world, this is package A!"
[1] "Hello, its package C"
** testing if installed package can be loaded from final location
[1] "Hello, its package A"
[1] "Hello, its package B"
[1] "Hello, world, this is package A!"
[1] "Hello, its package C"
** testing if installed package keeps a record of temporary installation path
* DONE (PackageC)
```

**Comment by gaborcsardi** [comment]
Can you give us a link to these packages?

**Comment by PavelBal** [comment]
These are the packages:
https://github.com/PavelBal/PackageA
https://github.com/PavelBal/PackageB
https://github.com/PavelBal/PackageC

Thank you for looking into this.

**Comment by gaborcsardi** [comment]
Thanks, seems to be a bug in pkgload, after cloning all three repos, and `R CMD INSTALL`-ing all of them:

```r
❯ pkgload::load_all()
ℹ Loading PackageC
[1] "Hello, its package B"
Error: Dependency package(s) 'PackageB' not available.
Run `rlang::last_error()` to see where the error occurred.
In addition: Warning message:
In (function (dep_name, dep_ver = "*")  :
  Dependency package 'PackageB' not available.

❯ rlang::last_error()
<error/rlang_error>
Dependency package(s) 'PackageB' not available.
Backtrace:
 1. pkgload::load_all()
 2. pkgload:::load_depends(path)
 3. pkgload:::abort_for_missing_packages(res, depends$package)
Run `rlang::last_trace()` to see the full context.

❯ pkgload:::load_depends(".")
[1] "Hello, its package B"
Error: Dependency package(s) 'PackageB' not available.
Run `rlang::last_error()` to see where the error occurred.
In addition: Warning message:
In (function (dep_name, dep_ver = "*")  :
  Dependency package 'PackageB' not available.
```

**Comment by gaborcsardi** [comment]
A workaround is to add this to `DESCRIPTION`:
```
Roxygen: list(load = "installed")
```
But then you always have to install the package before running `document()`.

**Comment by PavelBal** [comment]
@gaborcsardi Thanks a lot, that helps!

**Comment by gaborcsardi** [comment]
Here is a better workaround, that does not require installing `PackageC` before documenting it. Put this in `DESCRRIPTION` instead:
```r
Roxygen: { library(PackageB) ; list() }
```

**Comment by gaborcsardi** [comment]
Btw. note that PackageB does not work with `requireNamespace()`, either: 
```r
❯ requireNamespace("PackageB")
Loading required namespace: PackageB
[1] "Hello, its package B"
Failed with error:  ‘.onLoad failed in loadNamespace() for 'PackageB', details:
  call: helloA()
  error: could not find function "helloA"’
```

To work around this, you could replace the call to `helloA()` with `PackageA::helloA()`. Then both `requireNamespace()` and `document()` work properly. It is usually not good practice to create a package that cannot be loaded without attaching it. 

FWIW `Imports` is usually a better choice than `Depends`.

**Comment by gaborcsardi** [comment]
The conclusion at the linked issue is that PackageB is broken. You can still use the workarounds if you want to keep it like it is.

**Comment by PavelBal** [comment]
Thank you for pointing to the right direction! It was Package A (which is a third-party package) that did call an R-function from .NET (R <-> bridge) that was without the `packageA::`-prefix, that's why we couldn't find it, even if all calls in Package B were either importing or using `packageA::`.
