### ISSUE TITLE
devtools::check Undocumented S4 classes

### ISSUE THREAD

**Issue by rvernica** [r-lib/roxygen2#1225]
I have a reference class that I document and I'm getting a warning from `devtools::check` if I use the `@name` annotation. If I don't use it, I don't get the warning but I don't get the man page for the class either.

Here is what I do:
```
#'
#' Foo
#'
#' Foo bar
#'
#' @name foo
#' @field bar taz
foo <- setRefClass(
  "foo",
  fields = c(
```
This is the warning I get from `devtools::check`:
```
> checking for missing documentation entries ... WARNING
  Undocumented S4 classes:
    ‘foo’
  All user-level objects in a package (including S4 classes and methods)
  should have documentation entries.
  See chapter ‘Writing R documentation files’ in the ‘Writing R
  Extensions’ manual.
```
Something similar was reported in #770 but it is not clear what the resolution is since code examples are missing. I tried using `@export` and `@exportClass` but that did not help.

**Comment by hadley** [comment]
Can you please make a minimal reprex package that illustrates that problem and host it on github somewhere?

**Comment by hadley** [comment]
I've closed this issue due to lack of requested reprex. If you still care about this bug, please open a new issue with a reprex.
