### ISSUE TITLE
Add tags  to automatically add links to S4-methods,S4-generics,S4-superclasses and S4-subclasses

### ISSUE THREAD

**Issue by mamueller** [r-lib/roxygen2#1227]
Given an S4-generic function, it is possible to find the methods a package provides for it. 
Similarly, subclasses and superclasses of an S4 class can be found automatically by introspection. 
It is even possible to find out if a given class appears in a given s4-method implemented by the package.

Imagine the following  hypothetical tags:
- @s4methods 
  - in the documentation of a generic function it would trigger the creation of
    - a page for every S4-method of this generic provided in the package.
    - a section in the documentation of the generic with links to all the methods.
  - In the documentation of an S4-class it would trigger links to methods that have an argument of this class in their signature

- @s4generics
 - in the documentation of an S4-method it would trigger the creation of a link to the documentation of the generic. 
 - In the documentation of an S4-class it would trigger the creation of a section of links to generics that provide methods with the  
   class in their signature. 

- @s4subclasses
  In the documentation of an S4-class, this would create a section of links to all subclasses.

- @s4superclasses 
  In the documentation of an S4-class, this would create a section of links to all superclasses.
  
I have implemented all these tags and found them very useful to make this information automatically visible in the documentation.
While developing, automatically collecting and linking methods and subclasses makes it much easier to get/keep an overview of what methods are already available. I found myself using the creation of this linked documentation almost like a compile step and progress report.

Hadley closed the pull request https://github.com/r-lib/roxygen2/pull/1146 because it adds too much code at once and suggested starting with an issue to allow a discussion about the proposed changes. 
I hope for this discussion not least because I used this functionality to document a rather big package and in the long run do not want to maintain a separate branch of roxygen just to update the documentation ...
So comments are very welcome and useful.

**Comment by hadley** [comment]
I think the place to being would be a package that can generate the needed Rd. There's a decent amount of work to be done to figure out exactly what the links should be, and there's no need for that to live in roxygen2. Then once that package exists you could propose a lightweight PR to roxygen2.

I do think this would be very useful and a lot of people would appreciate, but my experiences with implementing this sort of code is that it's a lot of work and it's likely to take some time to work out all the bugs. That code can evolve much faster if its not part of roxygen2.
