### ISSUE TITLE
Avoid listing imported but not reexported functions in reexports.Rd

### ISSUE THREAD

**Issue by krlmlr** [r-lib/roxygen2#1239]
`pillar::dim_desc()` is imported but not reexported in this branch: https://github.com/tidyverse/tibble/blob/693829997f0a713b00619baf375f45dab1a1007c/man/reexports.Rd#L13 .

**Comment by gaborcsardi** [comment]
Isn't this a re-export?

https://github.com/tidyverse/tibble/blob/693829997f0a713b00619baf375f45dab1a1007c/NAMESPACE#L41

**Comment by krlmlr** [comment]
Yeah, but not in tidyverse/tibble@b273f1a. This commit removes the reexport, but it remains in the `.Rd` file.

**Comment by hadley** [comment]
I think you can just delete `pillar::dim_desc` here.

**Comment by krlmlr** [comment]
Good catch, fixed in https://github.com/tidyverse/tibble/commit/67acdd66e9b594d594fd276ae02d184c157f5a9f.
