### ISSUE TITLE
useDynLib(x, .registration = TRUE)

### ISSUE THREAD

**Issue by kenahoo** [r-lib/roxygen2#124]
Using `roxygen2`, how do I specify `.registration = TRUE` for `@useDynLib`?  I tried:

```
@useDynLib rmongodb .registration=TRUE
```

but then I end up with 

```
useDynLib(rmongodb,".registration=TRUE")
```

in the `NAMESPACE` file, i.e. it quotes the input to make it a single argument.

Alternatively, is there some way to just add some raw text to `NAMESPACE` when it's being managed by `roxygen`?

**Comment by tfjaeger** [comment]
Perhaps this could be stated somewhere more prominently in roxygen's documentation? I read various short and extended guides, but didn't find this until now (perhaps I just got unlucky, or had potatoes on my eyes =)). It's an issue that will come for anyone working on libraries that involve stan/rstan, for example.

**Comment by gaborcsardi** [comment]
FWIW it is in the manual, here: https://roxygen2.r-lib.org/articles/namespace.html#imports

In general it is often useful to search how other packages do it, e.g. https://github.com/search?q=org%3Acran+useDynLib+registration&type=Code

**Comment by tfjaeger** [comment]
Thank you - I think I must have read an older manual. My mistake!
