### ISSUE TITLE
`@template` should listen to all `@templateVar`s until the next `@template`

### ISSUE THREAD

**Issue by schloerke** [r-lib/roxygen2#1241]
Reprex:

```r
# Within roxygen2 repo
withr::with_dir(testthat::test_path(""), {
    out <- roc_proc_text(rd_roclet(), "
    #' @template values
    #' @templateVar x a
    #' @templateVar y b
    #' @templateVar z c
    #' @template values
    #' @templateVar x A
    #' @templateVar y B
    #' @templateVar z C
    x <- 10")[[1]]
})

out
```

```
% Generated by roxygen2: do not edit by hand
% Please edit documentation in ./<text>
\docType{data}
\name{x}
\alias{x}
\title{A}
\format{
An object of class \code{numeric} of length 1.
}
\usage{
x
}
\arguments{
\item{B}{C}
}
\description{
A

A
}
\keyword{datasets}
```

I'm expecting to have two arguments. Ex:

```
\arguments{
\item{b}{c}
\item{B}{C}
}

```

Currently, only the last template variables are used for both templates.  

It does look like the template was rendered twice, as the description has `A\n\nA`. But again, only the last variable value was used for both templates.

**Comment by hadley** [comment]
Yeah, unfortunately this isn't how templates were designed, and I think it's going to be extremely difficult to add now. I'd recommend using a different (more modern) mechanism to reduce doc duplication.
