### ISSUE TITLE
Support for multi-line `@examplesIf`?

### ISSUE THREAD

**Issue by jonkeane** [r-lib/roxygen2#1242]
When using `@examplesIf` I sometimes have conditions that are longer than can naturally fit on one line. It looks like [`@examplesIf` currently takes only the first line](https://github.com/r-lib/roxygen2/blob/6c1e42f061e9435a14bd3a0e01c7f08fc7aa9160/R/rd-examples.R#L9) and then disregards the rest of the lines, which leads to a malformed condition.

A (toy) example is:

```
#' @examplesIf {
#'   requireNamespace("dplyr", quietly = TRUE) &&
#'   requireNamespace("duckdb", quietly = TRUE) &&
#'   packageVersion("duckdb") > "0.2.7"
#' }
```

Which errors with `Warning: [{file path}] @examplesIf failed to parse condition of @examplesIf`

Would supporting multi-line `@examplesIf` conditions be something useful? I'm happy to look into this and submit a PR if it is.

**Comment by gaborcsardi** [comment]
If you have something like this, then you can have a helper function inside the package, and write 

```r
#' @examplesIf mypackage:::should_run_example()
```

**Comment by maelle** [comment]
Just saw multiline is actually supposed to work now: https://github.com/r-lib/roxygen2/commit/9652d15221109917d46768e836eaf55e33c21633
