### ISSUE TITLE
NAMESPACE does not contain imports for RcppProgress

### ISSUE THREAD

**Issue by elcortegano** [r-lib/roxygen2#1244]
When the package I'm developing is built, a NOTE is returned for some OS (e.g. fedora-gcc-devel) indicating that:

>Namespace in Imports field not imported from: ‘RcppProgress’
  All declared Imports should be used.

Just recently I found out testing with  `rhub::check(platform = "fedora-gcc-devel")` that this can be fixed simply by including `import(RcppProgress)` in the `NAMESPACE`. However, this is a `NAMESPACE` file generated with `devtools::document()` (a wrapper of `roxygen2::roxygenize()`), and it is meant to not be modified *by hand*.

This makes my wonder why `RcppProgress` was not included automatically in the `NAMESPACE`. Is this a bug? 

Calls to `RcppProgress` in the package are not made in .R files, buy .cpp files, e.g.

```
// [[Rcpp::depends(RcppProgress)]]
#include <progress.hpp>
#include <progress_bar.hpp>
type my_function (args) {
    ...
}
```

**Comment by gaborcsardi** [comment]
You need to explicitly import it from the R code: 
```
#' @import RcppProgress
NULL
```
