### ISSUE TITLE
rd_roclet does not respect exports in hand-written NAMESPACE

### ISSUE THREAD

**Issue by p00ya** [r-lib/roxygen2#1245]
When `NAMESPACE` is generated by hand, `rd_roclet` (and hence`roxygen2::roxygenise`, `devtools::document` etc.) generate documentation for functions that are not exported.

To reproduce, `mkdir rot ; cd rot ; R`:

```
> packageVersion("roxygen2")
[1] ‘7.1.1’
> usethis::create_package(".")
```

Add `R/foo.R` with the contents:

```R
#' This is an internal function and shouldn't be exported or documented.
.Foo <- function() {}

#' This function should be exported.
#' @export
Bar <- function() {}
```

From R:

```
devtools::document()
ℹ Updating rot documentation
ℹ Loading rot
Writing NAMESPACE
Writing NAMESPACE
Writing Bar.Rd
```

This is working as expected so far.  However, now lets provide a custom NAMESPACE:

```
# Generated by hand.  Stay away, roxygen2.
export(Bar)
```

Clear out old things: `rm -rf man`, then

```
> roxygen2::roxygenise()
First time using roxygen2. Upgrading automatically...
ℹ Loading rot
Warning: The existing 'NAMESPACE' file was not generated by roxygen2, and will not be overwritten.
Writing dot-Foo.Rd
Writing Bar.Rd
```

roxygen2 should not generate `dot-Foo.Rd`, because `.Foo` was not explicitly exported.

**Comment by gaborcsardi** [comment]
> roxygen2 should not generate dot-Foo.Rd, because .Foo was not explicitly exported.

Roxygen creates `.Rd` files for functions that the user documents, not the ones that are exported. This is to be able to document internal functions. If you don't want documentation for a function, then either do not document it, or use `@noRd` to disable the `.Rd` file.

**Comment by p00ya** [comment]
> > roxygen2 should not generate dot-Foo.Rd, because .Foo was not explicitly exported.
> 
> Roxygen creates `.Rd` files for functions that the user documents, not the ones that are exported. This is to be able to document internal functions. If you don't want documentation for a function, then either do not document it, or use `@noRd` to disable the `.Rd` file.

If that's true, then why does roxygen not create create the `dot-Foo.Rd` file when the NAMESPACE is being generated by roxygen?  This seems inconsistent to me.

**Comment by gaborcsardi** [comment]
> then why does roxygen not create create the dot-Foo.Rd file when the NAMESPACE is being generated by roxygen? 

It does create it for me:

```
❯ R --vanilla -q -e 'devtools::document()'
> devtools::document()
ℹ Updating foo documentation
ℹ Loading foo
Writing NAMESPACE
Writing dot-Foo.Rd
Writing Bar.Rd
>
>

~/foo
❯ cat NAMESPACE
# Generated by roxygen2: do not edit by hand

export(Bar)

~/foo
❯ ls man
Bar.Rd		dot-Foo.Rd
```

**Comment by p00ya** [comment]
Hmm, I must have missed an `rm -rf man` somewhere.  Sorry for the noise, I'll use `@noRd`.
