### ISSUE TITLE
More precise error messages from `topo_apply`

### ISSUE THREAD

**Issue by yogat3ch** [r-lib/roxygen2#1250]
Hi roxygen2 team,
I ran into an obtuse error using `devtools::document`:

`Error in dirname(file) : a character vector argument expected`

It took a bit to debug from the top level of `document` down into `roxygen2` to find that the error was occurring while [`topo_apply`ing over inherited params with `inherit_params`](https://github.com/r-lib/roxygen2/blob/6c1e42f061e9435a14bd3a0e01c7f08fc7aa9160/R/rd-inherit.R#L116). I used `browser` to examine the environment of the failed iteration and found the first argument is the documentation on which it occurred.

Is it possible to have `topo_apply` wrap the iteration function in a `tryCatch` and report the documentation (the first input argument) on which it errors in the error message?
It sure would make it a lot easier to identify where errors in documentation are occurring! 

_Update 2021-09-08T12:42:47-04:00_: It looks like the error itself was due to the package from which I was attempting to inherit being loaded via `devtools::load_all`. I guess internally `inherit_params` is somehow using the loaded namespace? Just wanted to post this update just in case anyone else encounters this issue.

**Comment by hadley** [comment]
Can you provide a reprex? Without it, it's going to be very hard for me to tickle this code too see how it could  be improved.

**Comment by yogat3ch** [comment]
Ok, this one is tricky to replicate because it involves some setup but here goes. The code below can be copy pasted into a package. Then load the package you wish to inherit from with `devtools::load_all`. 
In this example, `sheets_random` has documentation for a function I would like to inherit. When I document the local package, the error mentioned above is thrown.
```
#' This documentation fails because the package `googlesheets4` in a sibling directory is loaded via `devtools::load_all`
#' @inheritParams googlesheets4::sheets_random

thefun <- function(n) {
  n + 1
}
```
Due to the nature of the error message, this one was quite tricky to track down the source of. I posted the initial portion where I had located the function where the error was occurring after about an hour of stepping slowly down into the roxygen package one `debug` call at a time. After about 15 more minutes I somehow managed to figure out that it had to do with the namespace being loaded via `load_all`. 

Hope this helps! Thanks for looking into this!

**Comment by hadley** [comment]
@yogat3ch could you please make a minimal package and host it on github?

**Comment by hadley** [comment]
I've closed this issue due to lack of requested reprex. If you still care about this bug, please open a new issue with a reprex.
