### ISSUE TITLE
Code blocks with no language specified have `class="NA"` in generated HTML

### ISSUE THREAD

**Issue by wch** [r-lib/roxygen2#1251]
For example:

```
#' ```
#' r <- reactive({ compute(bigdata()) } %>%
#'   bindCache({ extract_most_recent_time(bigdata()) })
#' ```
```

https://github.com/rstudio/shiny/blob/6f46b847e2efb74a0cb82edee4d1c60658d8c9e1/R/bind-cache.R#L60-L63

turns into:

```
\if{html}{\out{<div class="sourceCode NA">}}\preformatted{r <- reactive(\{ compute(bigdata()) \} \%>\%
  bindCache(\{ extract_most_recent_time(bigdata()) \})
}\if{html}{\out{</div>}}
```

https://github.com/rstudio/shiny/blob/6f46b847e2efb74a0cb82edee4d1c60658d8c9e1/man/bindCache.Rd#L66-L68

(Note that in the linked code above, it was generated with roxygen2 7.1.1 and does not have the `sourceCode` class, but the `NA` issue is still present.)

If `` ```R `` is used to open the code block, then it (correctly) turns into `class="sourceCode R"`.

Update: Are curly braces (like `` ```{r, eval=FALSE} ``) needed for syntax highlighting?

**Comment by gaborcsardi** [comment]
Would you prefer dropping the NA or using R instead?

**Comment by wch** [comment]
I'm conflicted -- I think in most cases, people would want `R`, but there are many cases where you might want to display non-R text (like tabular data), and then how would you do that? I suppose you could use something like `txt`, but that's very non-obvious to users.

**Comment by maelle** [comment]
FWIW pkgdown will assume code blocks with no language specified are R blocks. (or maybe it shouldn't, then :slightly_smiling_face: ) https://github.com/r-lib/pkgdown/pull/1724

**Comment by hadley** [comment]
I think we should drop the `class = "NA"` and not imply R. 

pkgdown can continue guessing that all unmarked code blocks are R because it will try to parse them, and if they're not valid R code they don't get R syntax highlighting.

**Comment by hadley** [comment]
Ok, this problem was more subtle than I thought. It only appears if the first character in the code is "r":

``` r
library(roxygen2)

out <- roc_proc_text(rd_roclet(), "
#' Title
#'
#' ```
#' r <- 1:10
#' ```
#' @md
foo <- function() {}")[[1]]
out$get_section("description")
#> \description{
#> \if{html}{\out{<div class="sourceCode NA">}}\preformatted{r <- 1:10
#> }\if{html}{\out{</div>}}
#> }
```

<sup>Created on 2022-07-10 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
vs

``` r
library(roxygen2)

out <- roc_proc_text(rd_roclet(), "
#' Title
#'
#' ```
#' x <- 1:10
#' ```
#' @md
foo <- function() {}")[[1]]
out$get_section("description")
#> \description{
#> \if{html}{\out{<div class="sourceCode">}}\preformatted{x <- 1:10
#> }\if{html}{\out{</div>}}
#> }
```

<sup>Created on 2022-07-10 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
