### ISSUE TITLE
\cr directive as the only element of a parameter's description creates .Rd code that leads to invalid TeX code

### ISSUE THREAD

**Issue by kpagacz** [r-lib/roxygen2#1253]
Environment:
![image](https://user-images.githubusercontent.com/24480246/135074198-651dfd55-38ae-419b-a210-2277cd754d45.png)

Reprex:
```r
#' This is a test function
#' @param test \cr
#' @export
test_function <- function(test) {
  test
}
```

The .Rd is this:
```
% Generated by roxygen2: do not edit by hand
% Please edit documentation in R/test.R
\name{test_function}
\alias{test_function}
\title{This is a test function}
\usage{
test_function(test)
}
\arguments{
\item{test}{\cr}
}
\description{
This is a test function
}
```

When running R CMD Rd2pdf on a package containing such a function I get
![image](https://user-images.githubusercontent.com/24480246/135074348-651e59a4-0f15-4e83-a76b-2ebbeb3200f9.png)

The TeX code is this:
```tex
\begin{Arguments}
\begin{ldescription}
\item[\code{test}] \\{}
\end{ldescription}
\end{Arguments}
```

The line `\item[\code{test}] \\{}` is not valid TeX code.

Is there anything we can do to make roxygen2 not return this invalid code despite correctly interpreting the \cr directive?

**Comment by gaborcsardi** [comment]
roxygen2 does not return invalid code, it does not actually create TeX code, base R does that. The Rd output of roxygen2 is IMO correct. 

You will need to put some text before the `\cr` to make R generate valid TeX code. If you don't want to put any real text there, then put a dummy space there, e.g.

```
#' @param test \code{ }\cr
```

should do.

**Comment by kpagacz** [comment]
Sure, it doesn't produce any TeX, but does produce .Rd, which leads to invalid TeX in the building process. 

roxygen2 warns about an empty parameter description:
![image](https://user-images.githubusercontent.com/24480246/135078102-59c24d63-ccfd-4a42-8e7a-fb8a009a4d16.png)

if the parameter description is missing:
```r
#' This is a test function
#' @param test
#' @export
test_function <- function(test) {
  test
}
```
I would love to see a similar warning for a description, which only contains a directive resulting in empty bracers. This is what Rd2latex translates \cr to: 
https://github.com/SurajGupta/r-source/blob/a28e609e72ed7c47f6ddfbb86c85279a0750f0b7/src/library/tools/R/Rd2latex.R#L534

It's the same as having no description, so why not warn about it?

**Comment by gaborcsardi** [comment]
Roxygen does not know what `\cr` is. It cannot easily decide if an Rd command will generate some text or not. 

In this case the `\cr` in Rd did generate some text, actually, but it turned out to be invalid TeX. Roxygen does not know if TeX code is invalid or not.

**Comment by kpagacz** [comment]
Do you have any proposition on how to safeguard against such a misuse of roxygen?

**Comment by gaborcsardi** [comment]
No, I don't, sorry. It is pretty easy to write Rd code that creates invalid TeX, but pretty much the only way to tell if the generated TeX is valid or not is to actually run TeX on it.

**Comment by kpagacz** [comment]
Thanks.
