### ISSUE TITLE
Comments in Rmd chunks get interpreted as sections

### ISSUE THREAD

**Issue by lionel-** [r-lib/roxygen2#1255]
```r
#' Foo
#'
#' ```{r}
#' # Comment A
#' 1
#'
#' # Comment B
#' 2
#' ```
#'
#' @name foo
NULL
```

This expands to:

```Rd
% Generated by roxygen2: do not edit by hand
% Please edit documentation in R/nse-defuse.R
\name{foo}
\alias{foo}
\title{Foo}
\description{
\if{html}{\out{<div class="sourceCode r">}}\preformatted{# Comment A
1
}\if{html}{\out{</div>}}\preformatted{## [1] 1
}
}
\section{Comment B}{
2\preformatted{}
}
```

**Comment by gaborcsardi** [comment]
I am not sure if we can fix this. The current rule is that if `@description` is missing, then the first un-tagged paragraph is the `@description` and similarly for `@details`. This separation happens without the real parsing.

An easy fix is to mark your `@description` and `@details` explicitly. Or in this case, it is enough to include some `@description`, with or without marking it, the rest will be `@details`.

```r
#' Foo
#'
#' Bar
#' 
#' ```{r}
#' ## Comment A
#' 1
#' 
#' ## Comment B
#' 2
#' ```
#'
#' @name foo
NULL
```

**Comment by lionel-** [comment]
Ah got it, thanks for the workaround.
