### ISSUE TITLE
Suggestion: Tag to include source code in documentation

### ISSUE THREAD

**Issue by wurli** [r-lib/roxygen2#1268]
Working on analytical packages in a business-context, I make pretty heavy use of `roxygen2`/`pkgdown` to document the projects I work on. As such I find that sometimes it's handy to include the source-code for a function (including comments) in its own documentation, particularly as `pkgdown` will then autolink to other functions that get called in the function body. My suggestion is to include a tag that will do this automatically, e.g. `@source_code function_name`. I'd be happy to submit a PR if you'd be willing to include such a feature in the package, though I understand it may be somewhat out of scope.

NB, the utility function I currently use to do this works like this:
```
#' `r include_source_code(fun = "name_of_current_function", file = "name_of_current_file")`
```
Thanks for all the hard work on this fantastic package :)

**Comment by hadley** [comment]
Yeah, unfortunately I think this out of scope for roxygen2.
