### ISSUE TITLE
Can some line breaks between usage lines be omitted?

### ISSUE THREAD

**Issue by karoliskoncevicius** [r-lib/roxygen2#1272]
I am using `roxygen2` for generating .Rd files. Multiple functions share the same documentation and each has their usage line described therein. However, `roxygen2` automatically adds new lines in between all the functions.

Here is an example of how the functions are defined in the R file with `roxygen2` comment tags:

```r
#' @rdname name
#' @export
fun1 <- function(x, y) {
  ...
}

#' @rdname name
#' @export
fun2 <- function(x, y) {
  ...
}

#' @rdname name
#' @export
fun3 <- function(x, y) {
  ...
}

#' @rdname name
#' @export
fun4 <- function(x, y) {
  ...
}
```

And here is the usage section from the generated Rd:

    \usage{
    fun1(x, y)

    fun2(x, y)

    fun3(x, y)

    fun4(x, y)
    }

Ideally I would like to generate the following:

    \usage{
    fun1(x, y)
    fun2(x, y)

    fun3(x, y)
    fun4(x, y)
    }

Does `roxygen2` allow to specify this somehow, or should it be done manually?

P.S. this issue was first posted verbatim on StackOverflow, but attracted no attention [LINK](https://stackoverflow.com/q/70047774/1953718).

**Comment by hadley** [comment]
I think you'd need to do this manually sorry, I didn't see any obvious way we could specific this in roxygen2 comments.
