### ISSUE TITLE
Request: inheritParams with different names

### ISSUE THREAD

**Issue by DanChaltiel** [r-lib/roxygen2#1273]
Hi devs,

In some specific cases, it makes sense to name a parameter differently in two functions although the parameter serves the same purpose.

In these cases, `@inheritParams` will not work and this may cause code duplication.

A `key=value` syntax would be a nice workaround for this limitation, would that be manageable?

```r
#' Foo
#' @param a This is the first argument
foo <- function(a) a + 10

#' Bar
#' @param b This is the second argument
#' @inheritParams foo bar_a=a
bar <- function(bar_a, b) {
    foo(a=bar_a) * 10
}
```

**Comment by bschilder** [comment]
I agree, this  would be very helpful in a number of situations.

**Comment by hadley** [comment]
`@inheritParams` is already rather complicated, and I'd prefer not to add more complexity, sorry.
