### ISSUE TITLE
Support regex in except clause 

### ISSUE THREAD

**Issue by Nelson-Gon** [r-lib/roxygen2#1276]
Hi, 

Awesome package. Based on #617 I am wondering if it could be possibe to support regex based [exclusion](https://stackoverflow.com/questions/70523074/selectively-import-functions-using-regex). 

For example

```
#' My fancy function
#' @rawNamespace import(dplyr, except = filter)
```

I would be able to do:

```
#' My fancy function
#' @rawNamespace import(dplyr, except = filter_*)
```

In the above all `filter_` functions would be excluded in the import. I would like to avoid loading the entire package as I would like to only get like 10 or so functions (via `include`). 

Thank you

**Comment by hadley** [comment]
`@rawNamespace` allows you to put any text in `NAMESPACE`, which is then interpreted by R (https://cran.rstudio.com/doc/manuals/r-devel/R-exts.html#Specifying-imports-and-exports). So this is out of scope for roxygen2.
