### ISSUE TITLE
Not supporting UTF-8 characters in file paths when generating documentation

### ISSUE THREAD

**Issue by JantekM** [r-lib/roxygen2#1277]
When making a custom template I noticed that after adding a custom format for the template I couldn't generate roxygen documentation with `devtools::document()` from RStudio which gave this error:

    > devtools::document()
    i Updating JantoTools documentation
    Error: Failed to open G:\MĂłj dysk\Zdalne\Dokumenty zdalne\Statystyka\JantoTools/R/templates.R

Which, after some digging, led me to this piece of code throwing the error:
`
roxygen2::roxygenise("G:/Mój dysk/Zdalne/Dokumenty zdalne/Statystyka/JantoTools", NULL)
`

Note the change in the file path from `G:/Mój dysk/...` to `G:\MĂłj dysk\...`

Running the whole thing from another location with no `ó` in file path succeeded with no errors.

I tried (or checked if it is set) with no effect:

- setting global default encoding to UTF-8
- same with project settings
- reopening the file with UTF-8 encoding
- `options(encoding = "UTF-8")`
- using `Sys.setlocale()`

The whole code is available [here](https://github.com/JantekM/JantoTools/tree/roxygen-error).

**Comment by kleinbub** [comment]
I have exactly the same issue (on windows 10). I'm forced by my institution to work in a path that has a "Università" with a unicode letter in the path. I used to be able to overcome this using symbolic links in older versions. But now I get
"Error: Failed to open C:\Users\Kleinbub\OneDrive - UniversitÃ  degli Studi di Padova\" (note the conversion from UTF8 'à' to ANSI 'Ã' )
I have pinpointed the issue up to the update_collate() function. Indeed when I run roxygenize without the "collets" roclets it runs with no error.

**Comment by jacobmaugoust** [comment]
Hello,
Same issue here. It works fine with the 7.1.1 version but not with the 7.1.2 one; I changed absolutely nothing in the path or project enconding options. Had to roll back to the 7.1.1 version.
I tried to run the code of the roxygenize function; no particular errors, but at the end, the various `lapply`'s on the `blocks` object lead to empty things, so maybe it's somewhere there...
Hope this issue will be solved, good luck with that!

**Comment by hadley** [comment]
Looks like readxl had the same problem: https://github.com/tidyverse/readxl/blob/330805693a0be798458dc3a919effa744429abea/src/XlsWorkBook.h#L29-L34

**Comment by kleinbub** [comment]
Is this what you need @hadley?
It should be noted that the correct path would be ...Università... not ...UniversitÃ... as reported in the error.
Also, if relevant, this is a windows 10 system.

```
Error: Failed to open A:\OneDrive - UniversitÃ  degli Studi di Padova\rMEA development\rMEA/R/rMEA_IO.R 

9.
FUN(X[[i]], ...) 
8.
lapply(paths, find_includes) 
7.
generate_collate(file.path(base_path, "R")) 
6.
update_collate(base_path) 
5.
roxygen2::roxygenise(pkg$path, roclets) 
4.
devtools::document(roclets = c("rd", "collate", "namespace")) 
3.
.is.positive.intlike(x) 
2.
.traceback(x, max.lines = max.lines) 
1.
traceback({
    devtools::document(roclets = c("rd", "collate", "namespace"))
})
```
