### ISSUE TITLE
Em dash not rendered in website

### ISSUE THREAD

**Issue by ramiromagno** [r-lib/roxygen2#1278]
Hi,

I have three dashes in my roxygen2 documentation:

https://github.com/maialab/grantham/blob/4f259f9d170a2f3263c6e9efd32ed7ea1c1c15ff/R/grantham_distance.R#L23-L25

In RStudio help pane the three dashes are correctly converted to an em dash:

![snap](https://user-images.githubusercontent.com/19862384/147252852-50dd395f-d473-4b48-9bd6-8d8c214b3881.png)

but not in the website generated by pkgdown:

![snap](https://user-images.githubusercontent.com/19862384/147252998-ca37ee73-3652-4f6b-88e6-2666bcd58a12.png)

Website page: https://maialab.org/grantham/reference/grantham_equation.html

**Comment by maelle** [comment]
FWIW I think the Cmark option would be "smart typography".

**Comment by jeroen** [comment]
You would have to add `smart = TRUE` here: https://github.com/r-lib/roxygen2/blob/7b706c9f7f2e4227c98928a67c5dcb51d88ec15d/R/markdown.R#L160. But I think it was a deliberate choice to avoid fancy quotes.

**Comment by hadley** [comment]
Hmmmm, I think UTF-8 characters are usually ok in `.Rd`? I guess the problem the main potential is errors from latex when generating the manual. 

Generally, I'd prefer to default to having these on, if possible.

**Comment by gaborcsardi** [comment]
> Hmmmm, I think UTF-8 characters are usually ok in .Rd?

Sadly, generally they are not. Only a few of them are allow, pre-defined maybe in the Rd style file. Apparently the em dash is not one of them.

**Comment by hadley** [comment]
Ok, then I think we'll need to leave this as is.
