### ISSUE TITLE
Move {brew} to `Suggests:`

### ISSUE THREAD

**Issue by lorenzwalthert** [r-lib/roxygen2#1279]
I am not aware that I have ever used {brew} through {roxygen2}. I suggest to make {brew} a suggested dependency as the majority of users don't rely on it I assume. I am currently looking into reducing the dependency graph of {precommit} dependencies as outlined in https://github.com/lorenzwalthert/precommit/issues/356, which is why I file this issue. It seems as {brew} is only used [once](https://github.com/r-lib/roxygen2/search?q=brew) in the source code of {roxygen2}.

**Comment by hadley** [comment]
brew doesn't have any dependencies so this doesn't seem like it would make much of a difference to me.
