### ISSUE TITLE
inheritParams breaking on Windows

### ISSUE THREAD

**Issue by BenWiseman** [r-lib/roxygen2#1285]
adding inheritParams causes roxygen to break resulting in messed up formatting and a bunch of warnings. in the .Rd you get junk like this:
`\item{file}{A \link[base]{connection}, or a character string naming the file
    to print to.  If \code{""} (the default), \code{cat} prints to the
    standard output connection, the console unless redirected by
    \code{\link[base]{sink}}.
#ifdef unix not active  }`

which causes a cascade of problems.

**Comment by gaborcsardi** [comment]
I am afraid that you'd need to show us what breaks exactly in a reproducible example:
https://github.com/r-lib/roxygen2/blob/main/.github/SUPPORT.md#making-a-reprex
Thanks!

**Comment by BenWiseman** [comment]
Just add

#' @inheritParams base::mean
#' @inheritParams base::sum

To your roxygen

**Comment by gaborcsardi** [comment]
That generates this for me on Windows:

```
\arguments{
\item{x}{An \R object.  Currently there are methods for
    numeric/logical vectors and \link[base:Dates]{date},
    \link[base]{date-time} and \link[base]{time interval} objects.  Complex vectors
    are allowed for \code{trim = 0}, only.}

\item{...}{further arguments passed to or from other methods.}

\item{na.rm}{a logical value indicating whether \code{NA}
    values should be stripped before the computation proceeds.}
}
```
which looks fine.

**Comment by BenWiseman** [comment]
Hmm, try these

#' @inheritParams base::paste
#' @inheritParams base::cat

**Comment by gaborcsardi** [comment]
Yes, those work as well. 

But this does not seem like a productive approach. Can you please 
1) Show your code, either in a reproducible example, or the source code of your package if it is open source?
2) Tell us about your platform, e.g. R version and roxygen2 version.
