### ISSUE TITLE
Function name starting with a dot cannot be used as an @rdname or @describeIn

### ISSUE THREAD

**Issue by billdenney** [r-lib/roxygen2#1286]
When generating documentation of internal functions for a package where I am a secondary contributor, some of the functions start with a period (e.g. `.myfun()`).

I think that there is a bug where you can't use `@rdname` or `@describeIn` where the function being referenced starts with a period.

I don't know the best way to make a reprex for roxygen2 with multiple functions.  The error I'm getting is:

```r
> devtools::document()
i Updating test documentation
i Loading test
Writing NAMESPACE
Writing NAMESPACE
Warning message:
.test2.Rd is missing name/title. Skipping 
```

And, the underlying issue is that `.test21()` and `.test22()` are not present though they should be in `?.test2`.

The pseudo-reprex is:

```r
devtools::create("test")
setwd("test")
# put the file below into the R/ directory
devtools::document()
```

The file to use (I named it test.R):

```r
#' Test1
#' @param x parameter
#' @export
test1 <- function(x) {
}

#' @rdname test1
#' @export
.test11 <- function(x) {
}

#' @describeIn test1 foo
#' @export
.test12 <- function(x) {
}

#' Test2
#' @param x parameter
#' @export
.test2 <- function(x) {
}

#' @rdname .test2
#' @export
.test21 <- function(x) {
}

#' @describeIn .test2 foo
#' @export
.test22 <- function(x) {
}
```

**Comment by billdenney** [comment]
I had an additional thought of what may be happening, and I think that this confirms the issue.  When I reference `dot-test2` after `@describeIn` (see `.test23` below), the help shows up correctly in `?.test2`.

New test file:

```r
#' Test1
#' @param x parameter
#' @export
test1 <- function(x) {
}

#' @rdname test1
#' @export
.test11 <- function(x) {
}

#' @describeIn test1 foo
#' @export
.test12 <- function(x) {
}

#' Test2
#' @param x parameter
#' @export
.test2 <- function(x) {
}

#' @rdname .test2
#' @export
.test21 <- function(x) {
}

#' @describeIn .test2 foo
#' @export
.test22 <- function(x) {
}

#' @describeIn dot-test2 foo
#' @export
.test23 <- function(x) {
}
```

**Comment by gaborcsardi** [comment]
FWIW the documentation says this:
> It overrides the default file name generated by roxygen and merges documentation for multiple objects into one file. 

But PRs to improve this are most welcome.

**Comment by hadley** [comment]
Technically, in `@rdname` and `@describeIn`, I'd say that you're specifying a "topic" name, which is directly mapped to the filename `man/{topic}.Rd`.
