### ISSUE TITLE
multiple lines latex equation

### ISSUE THREAD

**Issue by kongdd** [r-lib/roxygen2#1288]
I am writing R package document with Roxygen2. I want to insert the following multiple lines latex equation into R help mannual. However, it is not work.

$$
F(t)= \begin{cases}\alpha(t) f_{L}(t)+[1-\alpha(t)] f_{C}(t) & t_{L}<t<t_{C} \\ \beta(t) f_{C}(t)+[1-\beta(t)] f_{R}(t) & t_{C}
$$

```R
#' hello2
#'
#' @description
#' \deqn{
#' F(t)= \begin{cases}\alpha(t) f_{L}(t)+[1-\alpha(t)] f_{C}(t) & t_{L}<t<t_{C} \\ \beta(t) f_{C}(t)+[1-\beta(t)] f_{R}(t) & t_{C}<t<t_{R}\end{cases}
#' }
#' 
#' @export
hello2 <- function() {}
```
<https://stackoverflow.com/questions/71167883/r-help-mannual-with-multiple-lines-latex-equation>

**Comment by gaborcsardi** [comment]
AFAICT roxygen2 just copies this over into the Rd file, like it should, so this does not seem like a roxygen2 issue.

FWIW, I could not find any packages on CRAN using `\deqn{ ... \begin{cases}` but I did find a bunch that use the `array` environment, so maybe you can write your equation with that? 
https://github.com/search?q=org%3Acran+deqn+begin+array+extension%3A.Rd&type=Code

**Comment by kongdd** [comment]
@gaborcsardi Thanks for your suggestion.
