### ISSUE TITLE
FR: Allow for custom file header

### ISSUE THREAD

**Issue by mschilli87** [r-lib/roxygen2#1291]
This is essentially the same a https://github.com/r-lib/roxygen2/issues/817 but [I was asked to open a new issue](https://github.com/r-lib/roxygen2/issues/817#issuecomment-1046025700) after [I explained my issue there](https://github.com/r-lib/roxygen2/issues/817#issuecomment-1045972213).

Basically, I would like any `*.Rd` file generated from a source file licensed under a copyleft license to contain the appropriate copyright and license header comment. A good start to this end would be a way to define a custom header: I suggest for roxygen to copy the content of any existing file up to the 'Generated by roxygen2: do not edit by hand' line to the generated file.

I would be willing to work towards a PR if there is any interest.

**Comment by hadley** [comment]
roxygen2 doesn't read existing `.Rd` files; it creates them from the roxygen comments in `.R` files. So unfortunately I don't think your proposal is viable without an infeasible amount of work.

**Comment by mschilli87** [comment]
@hadley: Thank you for your feedback. I understand that my naïve implementation idea does not match how the package works. An alternative would be to allow the user to explicitly specifying a header comment to prefix the `.Rd` files with via a `roxyen2` comment in the corresponding `.R` file. Do you think this would be feasible?

**Comment by gaborcsardi** [comment]
`.Rd` files may have multiple corresponding `.R` files. It is a many to many relationship. roxygen2 blocks can also inherit tags from other manual pages. 

OTOH you can probably implement this for yourself with a custom roclet, that runs after roxygen2's rd roclet and adds the header to every Rd file that does not have one.

**Comment by mschilli87** [comment]
@gaborcsardi: Thank you for you input.

> .Rd files may have multiple corresponding .R files. It is a many to many relationship. roxygen2 blocks can also inherit tags from other manual pages.

If I could specify a single header, project-wide, used for all `.Rd` files, that would already solve my use case.

> OTOH you can probably implement this for yourself with a custom roclet, that runs after roxygen2's rd roclet and adds the header to every Rd file that does not have one.

So in this case reading the `.Rd` files would be fine?
Can you point me to some documentation and/or example regarding custom roclets? My experience with `roxygen2` boils down to running `roxygenize()`, or sometimes  `roxygenize(roclets = "rd")`/`roxygenize(roclets = "namespace")`. :wink:

**Comment by gaborcsardi** [comment]
> If I could specify a single header, project-wide, used for all .Rd files, that would already solve my use case.

Sure, if you are completely sure that you need the same copyright and license header for every single `.Rd` file of your package, then you are fine. But if you inherit code from somebody else's package, then the copyright header will be probably wrong. So this would be very fragile for a lot of people, and would possibly generate false copyright headers.

> Can you point me to some documentation and/or example regarding custom roclets?

roxygen2 home page -> Articles -> Extending roxygen2 -> Creating a new roclet

**Comment by mschilli87** [comment]
@gaborcsardi:

> Sure, if you are completely sure that you need the same copyright and license header for every single `.Rd` file of your package, then you are fine. But if you inherit code from somebody else's package, then the copyright header will be probably wrong. So this would be very fragile for a lot of people, and would possibly generate false copyright headers.

Absolutely. This would only be a very specific hack gor my particular package and not a generaal solution worthwhile including in the package. If you have an idea how to solve this properly, please let me know.


> roxygen2 home page -> Articles -> Extending roxygen2 -> Creating a new roclet

Thank you.
For furture reference: https://roxygen2.r-lib.org/articles/extending.html#creating-a-new-roclet
