### ISSUE TITLE
Backward compatible support for the base pipe

### ISSUE THREAD

**Issue by hadley** [r-lib/roxygen2#1295]
I have no idea how this would work, but in tidyverse packages (which need to support old versions of R), it would be nice to be able to use `|>` in examples and have it automatically converted to `%>%` for older versions of R.

**Comment by ShixiangWang** [comment]
I think it's also important to support in code. I cannot find a workaround.

**Comment by gaborcsardi** [comment]
@ShixiangWang this is not something that we can fix in roxygen2. In fact, AFAICT it is not something that we can fix in any package, unless we write a new R -> old R compiler that essentially rewrites the code of your package at build or install time.

**Comment by hadley** [comment]
You can copy the technique we use in purrr or httr2 if you want to use native pipe in examples but still support building/checking on older R.

**Comment by Bisaloo** [comment]
For reference, the details of how this is achieved in purrr are in this PR: https://github.com/tidyverse/purrr/pull/938. More specifically, it is done in these files:

https://github.com/tidyverse/purrr/blob/870696c7d9f3208298ea84a36d813ffd28e59e49/configure

https://github.com/tidyverse/purrr/blob/870696c7d9f3208298ea84a36d813ffd28e59e49/configure.win

https://github.com/tidyverse/purrr/blob/870696c7d9f3208298ea84a36d813ffd28e59e49/cleanup

https://github.com/tidyverse/purrr/blob/870696c7d9f3208298ea84a36d813ffd28e59e49/tools/examples.R

**Comment by gaborcsardi** [comment]
@Bisaloo you also need this:
https://github.com/tidyverse/purrr/blob/870696c7d9f3208298ea84a36d813ffd28e59e49/DESCRIPTION#L37
