### ISSUE TITLE
Report incorrectly exported S3 methods

### ISSUE THREAD

**Issue by dmurdoch** [r-lib/roxygen2#1298]
This SO question https://stackoverflow.com/a/71308978/2554330 asks about a couple of error messages from `R CMD check`:

```
N  checking S3 generic/method consistency (3.3s)
   Found the following apparent S3 methods exported but not registered:
     is.nan.data.frame
   See section 'Registering S3 methods' in the 'Writing R Extensions'
   manual.
...
   S3 methods shown with full name in documentation object 'is.nan.data.frame':
     'is.nan.data.frame'
   
   The \usage entries for S3 methods should use the \method markup and not
   their full name.
```

The asker used Roxygen to generate the Rd files and NAMESPACE file, so didn't understand what those messages were asking for.  A really nice enhancement to `devtools::check` that would require `roxygen2` support would be to edit the check output so that those messages were interpreted in terms of Roxygen markup, with links to the original lines in the .R files where the markup occurred.   The first error could have additional information explaining why `check` thinks `is.nan.data.frame` is a method and what needs to be done so that Roxygen will add the registration line to NAMESPACE.  The second one could point out what would make Roxygen generate the correct Usage entry.

**Comment by hadley** [comment]
Hmmmm, I suspect it would be easier to implement this from first principles so that if you `@export` something that looks like an S3 method, you get an error. (And then just document how to override this in the very rare cases that it's necessary, e.g. https://github.com/hadley/plyr/pull/303/files)

**Comment by hadley** [comment]
Given that this seems to be a rare problem, and we are now pretty clear that `@export` alone should be sufficient in most cases, I think this is unlikely to ever rise to the top of my to do list, so I'm going to close the issue.
