### ISSUE TITLE
bug: `@inheritDotParams` doesn't handle escaped characters well

### ISSUE THREAD

**Issue by pnacht** [r-lib/roxygen2#1301]
I'm writing a package which uses the `glue` package. One of the functions effectively wraps `glue::glue_data`, so it has an ellipsis for all the `glue_data` arguments which should be documented with `@inheritDotParams glue::glue_data`.

As a reprex, I simply compiled a package with this function:
```r
# foo.R

#' foo
#'
#' @inheritDotParams glue::glue_data
#' @export
f <- function(...) {
  print(1)
}
```

At a glance this seems to work well, with roxygen2 compiling the .Rd files without a hitch. However, when I build and check the package, I get an odd warning about an unexpected `\item`.

I've realized the problem is in `glue_data`'s `.open` and `.close` arguments.

These are defined as:

```r
# glue.R

#' @param .open \[`character(1)`: \sQuote{\\\{}]\cr The opening delimiter. Doubling the
#'   full delimiter escapes it.
#' @param .close \[`character(1)`: \sQuote{\\\}}]\cr The closing delimiter. Doubling the
#'   full delimiter escapes it.
```

which gets compiled as:

```latex
% glue.Rd

\item{.open}{[\code{character(1)}: \sQuote{\\\{}]\cr The opening delimiter. Doubling the
full delimiter escapes it.}

\item{.close}{[\code{character(1)}: \sQuote{\\\}}]\cr The closing delimiter. Doubling the
full delimiter escapes it.}
```

In both files, we get `\sQuote{\\\{}`, that's three backslashes (two to render a backslash and one to escape the bracket), so that the rendered output is `'\{'`.

However, when I run roxygen2 on `foo.R`, the generated .Rd file has the following definitions of `.open` and `.close`:

```latex
% foo.Rd

    \item{\code{.open}}{[\code{character(1)}: \sQuote{\\{}]\cr The opening delimiter. Doubling the
full delimiter escapes it.}
    \item{\code{.close}}{[\code{character(1)}: \sQuote{\\}}]\cr The closing delimiter. Doubling the
full delimiter escapes it.}
```

They both have `\sQuote{\\{}`, with only two backslashes! So we get a rendered backslash but then the bracket is interpreted as code, which messes the parser up and throws a warning when building and checking the package.

**Comment by hadley** [comment]
Minimal reprex:

``` r
x <- "\\sQuote{\\\\\\{}]"
cat(x)
#> \sQuote{\\\{}]
cat(roxygen2:::rd2text(roxygen2:::parse_rd(x)))
#> \sQuote{\\{}]
```

<sup>Created on 2022-04-08 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

These bugs tend to come from base R's `as.character.Rd` but I'll see what I can do.

**Comment by hadley** [comment]
Even more minimal reprex:

``` r
x <- "\\sQuote{\\\\\\{}]"
cat(x)
#> \sQuote{\\\{}]
con <- textConnection(x)
tools::parse_Rd(con, fragment = TRUE, encoding = "UTF-8")
#> \sQuote{\{}]
```

<sup>Created on 2022-04-08 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by hadley** [comment]
I had a go and it looks like it's going to be hard to hack around this in roxygen2, so I filed a bug report with base R: https://bugs.r-project.org/show_bug.cgi?id=18324
