### ISSUE TITLE
Allow Manual Avoidance of Usage Section

### ISSUE THREAD

**Issue by DarioS** [r-lib/roxygen2#1302]
A popular documentation design used in the Bioconductor community for S4 classes is:

- Title
- Description
- Details
- Constructor
- Summary (i.e. the `show` method)
- Accessors

I notice that the core packages all use manually-written Rd files (e.g. [GRanges-class.Rd](https://github.com/Bioconductor/GenomicRanges/blob/master/man/GRanges-class.Rd)) to achieve this and I am trying to recreate the style using Roxygen2. But, whenever I use `@export` or `@exportMethod`, this automatically creates a Usage section, which I would like to be able to avoid, since I'm trying to copy the structure of having Constructor, Summary, Accessor sections and I want the constructor function to be in Constructor (and I don't want the S4 generic to appear in Usage, either. It could have less parameters than any defined S4 method for it).

**Comment by gaborcsardi** [comment]
Try

```r
#' @usage NULL
```

**Comment by DarioS** [comment]
Great! I couldn't find `@usage` examples in any Roxygen2 vignette, so this suggestion is invaluable.

**Comment by gaborcsardi** [comment]
If you don't mind, let's keep this open until we add this to the vignette of the Rd tags. (A PR is also welcome. :) No pressure of course.)
