### ISSUE TITLE
Circular warning when inheriting params from `pkgA::foo()` that links back to `pkgB::bar()`

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/roxygen2#1338]
If you document dplyr, you'll see warnings that look like this:

```r
> devtools::document()
ℹ Updating dplyr documentation
ℹ Loading dplyr
Writing NAMESPACE
Warning: Link to unknown topic in inherited text: dplyr::pull
Warning: Link to unknown topic in inherited text: dplyr::pull
Writing NAMESPACE
```

I've tracked this down to the fact that `pull()` has `@inheritParams tidyselect::vars_pull` to get docs for `var`, but then in the docs for `vars_pull()`, we link back to `dplyr::pull()` in two places (hence, two warnings). 

https://github.com/tidyverse/dplyr/blob/8c55a20823a394f4eba8a53f25f82871dce1cd8e/R/pull.R#L8
https://github.com/r-lib/tidyselect/blob/e2c51de4ada765efa22b620f7766fcac68d88a7f/R/vars-pull.R#L3
https://github.com/r-lib/tidyselect/blob/e2c51de4ada765efa22b620f7766fcac68d88a7f/R/vars-pull.R#L21

I've managed to reproduce this in a minimal way here:

https://github.com/DavisVaughan/testinherit
https://github.com/DavisVaughan/testinheritfrom

If you `devtools::install_github("DavisVaughan/testinheritfrom")` then fork and locally clone {testinherit}, then running `devtools::document()` with {testinherit} should show the same warnings as what we see in dplyr.

The weird part is that we are inheriting parameters, but the warnings are related to the fact that there is a link back to `pull()` in the `@description` and `@seealso` sections of `vars_pull()` (i.e. in theory those aren't related to the parameter docs)

**Comment by hadley** [comment]
This is already fixed in dev?

**Comment by DavisVaughan** [comment]
Yes it is!
