### ISSUE TITLE
Duplication of re-exports info?

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/roxygen2#1339]
If you try and document dplyr with the dev version of roxygen2, I get something like this. It looks like the reexport links are being replicated to the length of the number of functions you are reexporting from that package (i.e. there are 13 tibble reexports and it shows 13 times)

<img width="1057" alt="Screen Shot 2022-04-27 at 12 17 11 PM" src="https://user-images.githubusercontent.com/19150088/165565019-06d51528-9e52-4553-94fb-1f11947f292d.png">

**Comment by hadley** [comment]
Probably messed something up in f94f43ea44911a3e83fffacac48ed5e9d9385aa2

**Comment by hadley** [comment]
Yup
