### ISSUE TITLE
Extending roxygen2 .Rd - package documentation workflow

### ISSUE THREAD

**Issue by wilcoxa** [r-lib/roxygen2#1341]
I'm using custom tags to add new sections to package documentation similar to the @tip example in the extending roxygen2 vignette. I have 2 questions around the way to include these in the package development process.

1. What is the best way to include this in the package documentation workflow?
If I source the `roxy_tag_*` and `format.rd_section` functions into global environment and then `roxygen2::roxygenise()` then the .Rd files are built as expected, though a bit cumbersome. Ideally would like to generate with the RStudio build tools (eg. `Ctrl + Shift + D`), if I include these in an .R file in the package the new documentation sections are missing and get an unknown tag warnings. Do I need custom build script for this? What's the best approach here? 

2. Where should the `roxy_tag_*` and `format.rd_section_*` functions live in the package structure?
Relates to above, can these live in the `R` folder of the package or somewhere else

Thanks

**Comment by gaborcsardi** [comment]
> Ideally would like to generate with the RStudio build tools (eg. Ctrl + Shift + D), if I include these in an .R file in the package the new documentation sections are missing and get an unknown tag warnings. Do I need custom build script for this? What's the best approach here?

No, that should work, I think. But we could help you better if you could show us your package. 

> Where should the roxy_tag_* and format.rd_section_* functions live in the package structure?

I would put them in `R`, among the other source files, the cost for them there is usually pretty low.

**Comment by wilcoxa** [comment]
Hi @gaborcsardi,

Have put together a reprex and package here https://github.com/wilcoxa/roxydemo/

``` r
usethis::create_package("roxydemo", open = FALSE, roxygen = TRUE)
#> v Setting active project to 'C:/Users/wilcoxa/Documents/packages/prex_roxygen/roxydemo'
#> v Leaving 'DESCRIPTION' unchanged
#> Package: roxydemo
#> Title: What the Package Does (One Line, Title Case)
#> Version: 0.0.0.9000
#> Authors@R (parsed):
#>     * First Last <first.last@example.com> [aut, cre] (YOUR-ORCID-ID)
#> Description: What the package does (one paragraph).
#> License: `use_mit_license()`, `use_gpl3_license()` or friends to pick a
#>     license
#> Encoding: UTF-8
#> LazyData: true
#> Roxygen: list(markdown = TRUE)
#> RoxygenNote: 7.1.1
#> v Leaving 'NAMESPACE' unchanged
#> v Setting active project to '<no active project>'

writeLines(con = "./roxydemo/R/roxy_utils.R",
'
roxy_tag_parse.roxy_tag_tip <- function(x) {
    tag_markdown(x)
}

roxy_tag_rd.roxy_tag_tip <- function(x, base_path, env) {
    rd_section("tip", x$val)
}

format.rd_section_tip <- function(x, ...) {
    paste0(
        "\\\\section{Tips and tricks}{\\n",
        "\\\\itemize{\\n",
        paste0("  \\\\item ", x$value, "\\n", collapse = ""),
        "}\\n",
        "}\\n"
    )
}'
)

writeLines(con = "./roxydemo/R/foo.R",
"
#' Foo
#'
#' @param bar bar
#'
#' @return bar
#' @tip Here is the custom roxygen section
#' @export
#'
foo <- function(bar){
    bar
}
"
)

roxygen2::roxygenise("./roxydemo") # Generates warning @tip unknown tag
#> i Loading roxydemo
#> Warning: [C:\Users\wilcoxa\Documents\packages\prex_roxygen\roxydemo\R\foo.R:7]
#> @tip unknown tag
#> Writing NAMESPACE
#> Writing NAMESPACE
#> Writing foo.Rd
any(grepl("Tips and tricks", readLines("./roxydemo/man/foo.Rd")))
#> [1] FALSE


library(roxygen2)
source("./roxydemo/R/roxy_utils.R")
roxygen2::roxygenise("./roxydemo")
#> i Loading roxydemo
#> Warning: 
#> -- Conflicts --------------------------------------------- roxydemo conflicts --
#> x format.rd_section_tip()       masks roxydemo::format.rd_section_tip()
#> x roxy_tag_parse.roxy_tag_tip() masks roxydemo::roxy_tag_parse.roxy_tag_tip()
#> x roxy_tag_rd.roxy_tag_tip()    masks roxydemo::roxy_tag_rd.roxy_tag_tip()
#> 
#> Did you accidentally source a file rather than using `load_all()`?
#> Run `rm(list = c("format.rd_section_tip", "roxy_tag_parse.roxy_tag_tip", "roxy_tag_rd.roxy_tag_tip"))` to remove the conflicts.
#> Writing NAMESPACE
#> Writing NAMESPACE
#> Writing foo.Rd
any(grepl("Tips and tricks", readLines("./roxydemo/man/foo.Rd")))
#> [1] TRUE

```

<sup>Created on 2022-04-29 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by gaborcsardi** [comment]
Thanks! See the PRs. The second is probably more appropriate because you don't need to depend on roxygen2: https://github.com/wilcoxa/roxydemo/pull/2/files

The main difficulty is that you let R know about the S3 methods, one way or another. We could make this easier in roxygen2, and we probably should.

**Comment by wilcoxa** [comment]
Thanks @gaborcsardi that's great!

I hit an error for Fix2 the first time running it 
"Error in `FUN()`:
! `format.rd_section_tip` not found"

but can get around that by adding `registerS3method("format", "rd_section_tip", format.rd_section_tip)` as well to `.onload` the first time, once `S3method(format,rd_section_tip)` is in the namespace file it works fine.

**Comment by gaborcsardi** [comment]
Yeah, AFAIR you don't need to modify anything, just run it twice and the second time it will be good.
