### ISSUE TITLE
@details mismatched braces or quotes error is pointing to the incorrect line

### ISSUE THREAD

**Issue by billdenney** [r-lib/roxygen2#1344]
When I run devtools::document() on the attached file ([sparse.txt](https://github.com/r-lib/roxygen2/files/8611303/sparse.txt)), I get an error:

```
Warning: [C:\git\pknca\R\sparse.R:5] @details mismatched braces or quotes
Warning: [C:\git\pknca\R\sparse.R:7] @details mismatched braces or quotes
```

But, the actual issues are an extra `{` on line 71 of the file and needing a `\` before each of the percent signs on line 102. 
 There is no issue on line 5 or 7.  (Apologies that I always have difficulty making simple reprexes for roxygen issues.)

**Comment by hadley** [comment]
Have you tried the dev version

**Comment by billdenney** [comment]
The dev version points to the correct section and appears to correctly escape the % sign.  Thanks!
