### ISSUE TITLE
R6 and templates

### ISSUE THREAD

**Issue by sebffischer** [r-lib/roxygen2#1345]
roxygen2 templates don't properly work in combination with R6 class. 
Assume that there is a `.../package/man-roxygen/init.R` file with the following content: 

```r
#' @description
#' Initializes a new instance of this [R6][R6::R6Class] class.
```

I would then like to document my class `A` as follows:

```r
#' @title Class A
#' @description This class is the class A.
#' @export
A = R6::R6Class("A",
  public = list(
    #' @template init
    initialize = function() {
      print("Initialized!")
    }
  )
)
```

However, this gives me the warning "undocumented R6 methods: 'initialize' and the two @description sections (the one above the class and the one from the documentation of the initialize-method are merged, giving the following Rd documentation:

```r
% Generated by roxygen2: do not edit by hand
\name{A}
\alias{A}
\title{Class A}

\description{
This class is the class A.

Initializes a new instance of this \link[R6:R6Class]{R6} class.
}
...
```

This also is problematic when using the @param tag in the template, which is also not recognized by roxygen2

**Comment by gaborcsardi** [comment]
An alternative (that hopefully works) is to call an R function to generate the cocs:

#' @title Class A
#' @description This class is the class A.
#' @export
A = R6::R6Class("A",
  public = list(
    #' `r roxy_init()`
    initialize = function() {
      print("Initialized!")
    }
  )
)

**Comment by hadley** [comment]
I think templates are basically superseded in favour of newer techniques, so we're unlikely to make changes here.

**Comment by sebffischer** [comment]
Note that the alternative does not work unfortunately
