### ISSUE TITLE
An existing use of `@inheritParams` broke

### ISSUE THREAD

**Issue by jennybc** [r-lib/roxygen2#1347]
This may be intentional, but I want to check.

In `devtools::check_mac_release()` and `devtools::check_win()`, we have:

``` r
#' @inheritParams pkgbuild::build

<snip, snip>

check_mac_release <- function(pkg = ".", dep_pkgs = character(), args = NULL, manual = TRUE, quiet = FALSE, ...) { ... }
```

The intent and what was happening prior to roxygen2 7.2.0 is that these devtools functions would inherit the docs for `manual` from `pkgbuild::build()`, which look like:

```
#' @param vignettes,manual For source packages: if `FALSE`, don't build PDF
#'   vignettes (`--no-build-vignettes`) or manual (`--no-manual`).
```

That no longer happens (https://github.com/r-lib/devtools/commit/647db331c40e34697bfbf069a4a7d8b18b25cc12).

Is this a known breakage due to the response to #950 and devtools just can't inherit the documentation for `manual` from pkgbuild?

**Comment by hadley** [comment]
Because the inherited argument wasn't correct
