### ISSUE TITLE
Backticks in inline R not working anymore since 7.2.0

### ISSUE THREAD

**Issue by msberends** [r-lib/roxygen2#1348]
Thanks for the package.

Since updating to 7.2.0, it seems this is not supported anymore:

```r
#' The number of rows is `r paste0("``", nrow(mtcars), "``")`
```

Expected:
```r
#' The number of rows is `32`
```

We use backticks in a `paste0()` as `"``"` to have e.g. values in vectors be surrounded by backticks.

Silly example perhaps, but this kind of inline R expressions are a lot in our packages. Worked fine with 7.1.2 and lower. Is there an escape character we don't know of yet?

Might be introduced by #1179?

**Comment by hadley** [comment]
Yeah, this is deliberate to match the way you'd write this in `.Rmd`.

**Comment by msberends** [comment]
Alright :+1:
