### ISSUE TITLE
Inline rmarkdown results inserted in wrong place

### ISSUE THREAD

**Issue by hadley** [r-lib/roxygen2#1353]
Something is going wrong with the Rd snipped generated by the `link()` function:

<img width="561" alt="Screen Shot 2022-05-22 at 10 05 31" src="https://user-images.githubusercontent.com/4196/169701950-fe6046fc-2395-49cc-871a-5b7705a64e28.png">

And `message` needs to mention "v" and "!", I'd suggest something like: Elements named `"*"`, `"i"`, `"v"`, and `"x"`, "!", are formatted as regular, info, success, failure, and error bullets respectively.

**Comment by hadley** [comment]
Probably in bug in `str_set_all_pos()`. I have a vague recollection of hitting this bug elsewhere. Maybe in downlit?

...

Maybe https://github.com/r-lib/downlit/commit/3254d196879f20478d566aab0b0751fd1e5245e8 ?

**Comment by hadley** [comment]
Hmmm, I can't reprex:

``` r
library(roxygen2)

roc_proc_text(rd_roclet(), r"(
#' Topic
#' @name topic2
#' @param message foo
#'   . bar `r "\\ifelse{foo}{bar}{baz}"`.
NULL
)")[[1]]
#> % Generated by roxygen2: do not edit by hand
#> % Please edit documentation in ./<text>
#> \name{topic2}
#> \alias{topic2}
#> \title{Topic}
#> \arguments{
#> \item{message}{foo
#> . bar `r "\\ifelse{foo}{bar}{baz}"`.}
#> }
#> \description{
#> Topic
#> }
```

<sup>Created on 2022-07-06 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by hadley** [comment]
Ah, needed to force md on:

``` r
library(roxygen2)

roc_proc_text(rd_roclet(), r"(
#' Topic
#' @md
#' @name topic2
#' @param message foo
#'   . bar `r "\\ifelse{foo}{bar}{baz}"`.
NULL
)")[[1]]
#> % Generated by roxygen2: do not edit by hand
#> % Please edit documentation in ./<text>
#> \name{topic2}
#> \alias{topic2}
#> \title{Topic}
#> \arguments{
#> \item{message}{foo
#> . ba\ifelse{foo}{bar}{baz}"`.}
#> }
#> \description{
#> Topic
#> }
```

<sup>Created on 2022-07-06 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by hadley** [comment]
Somewhat simpler reprex:

``` r
library(roxygen2)

roc_proc_text(rd_roclet(), r"(
#' Title
#'
#' line1
#'    111 `r "222"` 333
#' @md
foo <- function() {}
)")[[1]]
#> % Generated by roxygen2: do not edit by hand
#> % Please edit documentation in ./<text>
#> \name{foo}
#> \alias{foo}
#> \title{Title}
#> \usage{
#> foo()
#> }
#> \description{
#> line1
#> 12222"` 333
#> }
```

<sup>Created on 2022-07-06 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

It's something to do with the leading indent — if you change the number of spaces, the corruption changes.

**Comment by gaborcsardi** [comment]
Yeah, unfortunately this seems to be a cmark bug:
```r
src <- "Title\n\nline1\n   111 `r \"222\"` 333\n"
cat(src)
```

```
Title

line1
   111 `r "222"` 333
```

```r
cat(commonmark::markdown_xml(src, sourcepos = TRUE))
```

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE document SYSTEM "CommonMark.dtd">
<document sourcepos="1:1-4:20" xmlns="http://commonmark.org/xml/1.0">
  <paragraph sourcepos="1:1-1:5">
    <text sourcepos="1:1-1:5" xml:space="preserve">Title</text>
  </paragraph>
  <paragraph sourcepos="3:1-4:20">
    <text sourcepos="3:1-3:5" xml:space="preserve">line1</text>
    <softbreak />
    <text sourcepos="4:1-4:4" xml:space="preserve">111 </text>
    <code sourcepos="4:6-4:12" xml:space="preserve">r &quot;222&quot;</code>
    <text sourcepos="4:14-4:17" xml:space="preserve"> 333</text>
  </paragraph>
</document>
```

The `sourcepos` of the last line is clearly off. Let me see if a newer cmark version fixes this.

**Comment by gaborcsardi** [comment]
Seems that the R package uses https://github.com/github/cmark-gfm, for the GFM extensions, I guess and there is no fix for this: https://github.com/github/cmark-gfm/releases

I'll report it upstream. 

As for roxygen2, let me see if we can work around this.

**Comment by gaborcsardi** [comment]
Found it in the cmark issue tracker, it does not seem like a thing that will be fixed soon: https://github.com/commonmark/cmark/issues/296
