### ISSUE TITLE
There should be full stops at the end of sentence in @param

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [r-lib/roxygen2#1360]
The following lines,
https://github.com/r-lib/roxygen2/blob/d4040c5916f9f31682c7b996655fad609e5d56f4/vignettes/roxygen2.Rmd#L64-L65
https://github.com/r-lib/roxygen2/blob/d4040c5916f9f31682c7b996655fad609e5d56f4/vignettes/roxygen2.Rmd#L86-L88
do not have full stops and do not match the guidance/example provided in [r-pkgs](https://github.com/hadley/r-pkgs/blob/abb56cde416904258d828b98bac794fc8d6a4295/man.Rmd#L53)

I can easily open a branch/pull request for this but I wanted to make sure that the change is wanted first.

**Comment by hadley** [comment]
A PR would be great, thanks!
