### ISSUE TITLE
R Code that returns character vector is treated differently

### ISSUE THREAD

**Issue by sebffischer** [r-lib/roxygen2#1361]
Previously we had something similar to: 
```r
#' @description
#' `r c("a", "b")`
add = function(a, b) a + b
```

where `"a"` and `"b"` appeared on individual lines, i.e. were combined using something like`paste(..., collapse = "\n")`

With the latest roxygen 7.2.0 release, this behaviour changed and now pastes the vectors with `", "` instead of `"\n"`

**Comment by hadley** [comment]
Minimal reprex:

``` r
library(roxygen2)

roc_proc_text(rd_roclet(), "
  #' Title
  #'
  #' `r c('a', 'b')`
  #' @md
  add = function(a, b) a + b
")[[1]]
#> % Generated by roxygen2: do not edit by hand
#> % Please edit documentation in ./<text>
#> \name{add}
#> \alias{add}
#> \title{Title}
#> \usage{
#> add(a, b)
#> }
#> \description{
#> a, b
#> }
```

<sup>Created on 2022-07-06 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by hadley** [comment]
Probably introduced in #1193

**Comment by hadley** [comment]
Given that this has affected relatively few people, I think the simplest solution is just to document this new behaviour.
