### ISSUE TITLE
7.2.0 Confusing error message thrown by `tokenize_file()`

### ISSUE THREAD

**Issue by retostauffer** [r-lib/roxygen2#1362]
Dear all,

there seems not to be an issue related to this 'problem' yet, I hope I have not overlooked anything.

**Problem/Issue:** After updating my system (Ubuntu `20.04`, R Version `4.2.0`, roxygen2 `7.2.0`) I encountered an confusing error message when documenting my package due to a syntax error in the roxygen comments. The error message:

* `Error: invalid version specification ‘0.68’`

**Origin:** I was able to track it down to `roxygen2:::tokenize_file()` (`roxygenize()` -> `parse_package()` -> `parse_file()` -> `tokenize_file()`). I could not find out where `0.68` originates from but was able to reproduce the problem with a small minimal:

* GIST: <https://gist.github.com/retostauffer/fdaca37ad1ea2f6b9aabbd509feafdb2>

The minimal writes four minimal `.R` scripts with roxygen documentation and a demo function. (1) is correct, (2) returns an readable error message, (3 & 4) return the error shown above.

Not a bug as the problem lies on my side, but the error message is confusing and it took me a while to find the issue (did not happen with R `4.1.0`; cannot tell which roxygen version I was using).

Thanks a lot!

**Comment by gaborcsardi** [comment]
What is the output of `traceback()` right after the error?

**Comment by retostauffer** [comment]
Hy @gaborcsardi 

The traceback below is based on `minimal3` ([gist](https://gist.github.com/retostauffer/fdaca37ad1ea2f6b9aabbd509feafdb2)) when calling `parse_file()`:

```
> roxygen2::parse_file(tmp)
Error: invalid version specification ‘0.68’
> traceback()
17: stop(gettextf("invalid version specification %s", paste(sQuote(unique(x[!ok]
)), 
        collapse = ", ")), call. = FALSE, domain = NA)
16: .make_numeric_version(x, strict, .standard_regexps()$valid_R_system_version,
 
        c("R_system_version", "package_version"))
15: R_system_version(paste(x[c("major", "minor")], collapse = "."))
14: package_version(list(major = 0, minor = VTE_VERSION))
13: ansi_has_hyperlink_support()
12: cli::style_hyperlink(paste0(basename(file), ":", line), paste0("file://", 
        file), params = c(line = line, col = 1))
11: paste0("[", cli::style_hyperlink(paste0(basename(file), ":", 
        line), paste0("file://", file), params = c(line = line, col = 1)), 
        "]")
10: link_to(tag$file, tag$line)
9: paste0(link_to(tag$file, tag$line), " @", tag$tag, " ", if (is.null(tag$raw))
 ("(automatically generated) "), 
       message[[1]])
8: warn_roxy_tag(x, "is not a known tag")
7: roxy_tag_parse.default(tokens[[i]])
6: roxy_tag_parse(tokens[[i]])
5: parse_tags(tokens)
4: .f(call = .l[[1L]][[1L]], srcref = .l[[2L]][[1L]], tokens = .l[[3L]][[1L]], 
       ...)
3: purrr::pmap(list(call = as.list(parsed)[has_tokens], srcref = refs[has_tokens
], 
       tokens = tokens[has_tokens]), block_create)
2: tokenize_file(file, srcref_path = srcref_path)
1: roxygen2::parse_file(tmp)
```

thanks in advance!

**Comment by retostauffer** [comment]
Thanks @gaborcsardi 

tested my minimal with the latest  [`r-lib/cli`](https://github.com/r-lib/cli)  `3.3.0.9000` (current main branch, 2022-06-17) and everything looks fine! Originally was using `cli 3.3.0` (current CRAN release).
