### ISSUE TITLE
Documentation for tags

### ISSUE THREAD

**Issue by romainfrancois** [r-lib/roxygen2#1375]
It would be useful to have some sort of documentation for each tag, so that e.g. we could show it in completion popups: 

![image](https://user-images.githubusercontent.com/2625526/176408073-27f71846-f64e-46f6-881d-5ab018a52ba0.png)

Maybe a "doc" attribute for a function related to the tag, e.g. 

```
attr(roxy_tag_parse.roxy_tag_rdname, "doc") <- "Something useful about the @rdname tag"
```

**Comment by hadley** [comment]
Also need to record whether or not they take arguments (so IDE knows whether to insert space or not), and might be worth somehow associating with a roclet so we could also use to generate an automated list for roxygen2 docs.
