### ISSUE TITLE
Can knitr code blocks preserve blank lines when rendering?

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/roxygen2#1376]
I'd like to preserve the blank lines in this code block when it gets rendered, is that possible?

```
#' ```{r}
#' 1 + 1
#'
#' 2 + 2
#' ```
```

<img width="723" alt="Screen Shot 2022-07-01 at 10 40 29 AM" src="https://user-images.githubusercontent.com/19150088/176916178-c6b277a1-e08b-4974-be05-3ec00dfeedd2.png">

**Comment by remlapmot** [comment]
I think you can get the blank line by setting the `collapse` knitr chunk option
````
#' ```{r, collapse=TRUE}
#' 1 + 1
#'
#' 2 + 2
#' ```
````

There might be a way to do it with the `strip.white` chunk option as well.

**Comment by DavisVaughan** [comment]
Yep, `collapse = TRUE` does work (just confirming, even though Hadley changed it to use this already)

<img width="628" alt="Screen Shot 2022-07-07 at 10 49 49 AM" src="https://user-images.githubusercontent.com/19150088/177803534-7c9bcdbe-39a6-4c88-904a-3fccf1e2f098.png">


I'm a bit surprised `strip.white = FALSE` didn't work, `collapse` seems like a strange argument name to make this work

<img width="602" alt="Screen Shot 2022-07-07 at 10 50 18 AM" src="https://user-images.githubusercontent.com/19150088/177803692-97fca79a-7d15-437b-9e82-a0e3078de9f4.png">
