### ISSUE TITLE
Is it possible to preserve spacing between sequential knitr code blocks?

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/roxygen2#1377]
i.e. consider these two sequential blocks of code:

```
#' ```{r}
#' 1 + 1
#'
#' 2 + 2
#' ```
#'
#' ```{r}
#' 3 + 3
#'
#' 4 + 4
#' ```
```

When they render, there is no space between them, but I'd like to preserve that if possible because I consider them separate examples 

<img width="661" alt="Screen Shot 2022-07-01 at 10 43 30 AM" src="https://user-images.githubusercontent.com/19150088/176916793-57ca2f20-7164-4526-bb52-1c05aeeca578.png">

**Comment by remlapmot** [comment]
Have you tried using `\cr` as per [here](https://stackoverflow.com/questions/18835365/roxygen2-manually-insert-line-breaks) and [here](https://cran.r-project.org/doc/manuals/r-release/R-exts.html#index-_005ccr), i.e. something like

````
#' ```{r}
#' 1 + 1
#'
#' 2 + 2
#' ```
#' \cr
#' ```{r}
#' 3 + 3
#'
#' 4 + 4
#' ```
````

**Comment by hadley** [comment]
I think this is a Rd problem, not an roxygen2 one. If I write:

```
\preformatted{a <- 1

b <- 2
}

\preformatted{c <- 3
}
```

I see

<img width="190" alt="Screen Shot 2022-07-07 at 12 44 53" src="https://user-images.githubusercontent.com/4196/177666047-b53e40c8-97f0-4a65-947f-5d393eee4ce3.png">

**Comment by remlapmot** [comment]
Great spot! Would it be acceptable to insert the `<br />` without the paragraph as follows
````
#' ```{r}
#' 1+1
#'   
#' 2+2
#' ``` 
#' \if{html}{\out{<br />}}
#' ```{r}
#' 3+3
#'   
#' 4+4
#' ```
````

**Comment by hadley** [comment]
I think the fix really needs to come in R (or maybe RStudio) itself — the `<div>` containing the sourceCode should get the same margin as `<p>`.
