### ISSUE TITLE
"strange" `is_installed()` error `Problematic names: "::"`

### ISSUE THREAD

**Issue by gwd666** [r-lib/roxygen2#1384]
Can anyone provide some more information on this type of error message popping up during package dev when running `devtools::document()` or `roxygen2::roxygenise()`

I do not really understand 
1. the error message 
```
x Problematic names:
* "::"
```
2. What to make of it since the package can be installed (via "Install and Restart" RStudio button)?
3. What to attempt to get rid of this - since it does seem to break the documentation run. 

```
==> devtools::document(roclets = c('rd', 'collate', 'namespace'))

i Updating egs.cube documentation
i Loading egs.cube
Error in `is_installed()`:
! Must supply valid package names.
x Problematic names:
* "::"
Backtrace:
     x
  1. +-base::suppressPackageStartupMessages(...)
  3. | \-base::withCallingHandlers(expr, packageStartupMessage = function(c) tryInvokeRestart("muffleMessage"))
  4. \-devtools::document(roclets = c("rd", "collate", "namespace"))
  5.   \-roxygen2::roxygenise(pkg$path, roclets)
  6.     \-base::lapply(...)
  7.       +-roxygen2 FUN(X[[i]], ...)
  8.       \-roxygen2:::roclet_process.roclet_rd(X[[i]], ...)
  9.         \-roxygen2:::topics_process_inherit(topics, env)
  10.           \-topics$topo_apply(inherits("params"), inherit_params)
 11.             \-roxygen2 fun(topic, self, ...)
 12.               \-roxygen2:::find_params(inheritor, topics, source = topic$get_name())
 13.                 \-roxygen2:::get_rd(name, topics, source = source)
 14.                   \-roxygen2:::get_rd_from_help(pkg, fun, source)
 15.                     \-rlang::is_installed(package)
 16.                       \-rlang:::pkg_version_info(pkg, version = version, compare = compare)
 17.                         \-rlang::abort(msg, call = call)
Execution halted

Exited with status 1.
```
SessionInfo: 
```
 version 4.0.5 (2021-03-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19042)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] egs.cube_0.0.1.9000 RDCOMClient_0.95-1 

loaded via a namespace (and not attached):
 [1] stringdist_0.9.8  xfun_0.31         fcuk_0.1.21       remotes_2.4.2     memuse_4.2-1     
 [6] purrr_0.3.4       vctrs_0.4.1       testthat_3.1.4    usethis_2.1.6     utf8_1.2.2       
[11] rlang_1.0.2       pkgbuild_1.3.1    pillar_1.7.0      glue_1.6.2        withr_2.5.0      
[16] sessioninfo_1.2.2 fortunes_1.5-4    prompt_1.0.1      lifecycle_1.0.1   stringr_1.4.0    
[21] commonmark_1.8.0  devtools_2.4.3    memoise_2.0.1     knitr_1.39        callr_3.7.0      
[26] fastmap_1.1.0     ps_1.7.1          parallel_4.0.5    fansi_1.0.3       clipr_0.8.0      
[31] cachem_1.0.6      desc_1.4.1        pkgload_1.2.4     fs_1.5.2          brio_1.1.3       
[36] stringi_1.7.6     processx_3.6.1    rprojroot_2.0.3   cli_3.3.0         tools_4.0.5      
[41] magrittr_2.0.3    tibble_3.1.7      crayon_1.5.1      pkgconfig_2.0.3   ellipsis_0.3.2   
[46] xml2_1.3.3        prettyunits_1.1.1 datapasta_3.1.0   reprex_2.0.1      roxygen2_7.2.0   
[51] rstudioapi_0.13   R6_2.5.1          compiler_4.0.5   
```

**Comment by gwd666** [comment]
One might like to add the fact that RDCOMClient in its current form has some NANESPACE peculiarities going on (some functions not getting "exported" correctly ie not being discoverable by other packages, despite being in the RDCOMClient NAMESPACE file, therefore my current workaround was//is to include RDCOMClient in the 'Attach:'  section of my packages DESCRIPTION, since that solves that issue) which then could potentially also cause strange behavior as in cases like this?

**Comment by hadley** [comment]
Given the traceback, there's probably something wrong with one of your `@inheritParams` tags. If you can figure out which one is the problem, I can make a reprex and then provide a more informative error for other folks in the future.

**Comment by gwd666** [comment]
Will add some more details this weekend, since now, thanks to your hint, I have a better idea what to look for. 
Thanks a lot

**Comment by lionel-** [comment]
Should roxygen be a little more defensive with its inputs here? Perhaps by checking `is_call(parsed, "::")` first and issuing a warning before exiting early if that's not the case?

```r
    parsed <- parse_expr(name)
    pkg <- as.character(parsed[[2]])
    fun <- as.character(parsed[[3]])
```

**Comment by gwd666** [comment]
I am quite sure that the error was stemming from ` @inheritParams RDCOMClient::COMCreate` in my case, since as I mentioned earlier that on-CRAN package currently is also displaying some erratic behavior, when it comes to functions or objects exported by its NAMESPACE not being visible to other package depending on it. My current workaround for that issue in RSCOMClient is to include it in the `Depends` section of my DESCCRIPTION file, but that most probably is not enough for roxygen2 to handle it correctly. 
Sadly I am currently not able to reproduce that error on my side because after trying to get things moving again I now have  new again a bit cryptic error message 
```
Error in vapply(X, FUN, FUN.VALUE = character(1), ..., USE.NAMES = USE.NAMES) : 
  values must be length 1,
 but FUN(X[[1]]) result is length 3
Calls: suppressPackageStartupMessages ... mapply -> <Anonymous> -> <Anonymous> -> vcapply -> vapply
Execution halted
```
Any hints where that thing pops up from - since I do not have a single use of `vapply`  in my pkg code?

**Comment by gwd666** [comment]
> Sadly I am currently not able to reproduce that error on my side because after trying to get things moving again I now have a new, again a bit 'cryptic' error message when running `devtools::document()`
> 
> ```
> Error in vapply(X, FUN, FUN.VALUE = character(1), ..., USE.NAMES = USE.NAMES) : 
>   values must be length 1,
>  but FUN(X[[1]]) result is length 3
> Calls: suppressPackageStartupMessages ... mapply -> <Anonymous> -> <Anonymous> -> vcapply -> vapply
> Execution halted
> ```
> 
> Any hints where that thing pops up from - since I do not have a single use of `vapply` in my pkg code?

OK FORGET THAT ONE - it seems I placed some Comment characters in a MALFORMED way in the roxygen2 comments
