### ISSUE TITLE
behaviour of roxygen2 for the first two paragraphs in an R file

### ISSUE THREAD

**Issue by maelle** [r-lib/roxygen2#1385]
I'm wondering about the behaviour of roxygen2 for the first two paragraphs in an R file, that used to be title and description (I think?)

The patterns I have in mind are

```
#' Functionname
#'  
#' What the developer might intend to be a description
```

and 

```
#' @title Functionname
#'  
#' What the developer might intend to be a description
```

?

The resulting Rd file is at the moment, for both title and description, the two lines.

```
\title{Functionname
 
What the developer might intend to be a description}
\usage{
Functionname()
}
\description{
Functionname
 
What the developer might intend to be a description
}
```

and there is no warning unless there's a non roxygen2 line after the second paragraph.

Context https://community.rstudio.com/t/one-function-giving-a-undocumented-warning/141708/2

**Comment by gaborcsardi** [comment]
Are the space characters in the second line intentional? Are they non-breaking spaces or other special spaces characters?

Maybe roxygen2 could warn for this, IDK how frequent this is TBH.

**Comment by maelle** [comment]
no not intentional, sorry

**Comment by maelle** [comment]
The example in https://r-pkgs.org/man.html#roxygen-comments also has "implicit" tags

**Comment by gaborcsardi** [comment]
To be clear, I believe those space characters cause the issue. Because of them you only have one paragraph, and not two. If there is one un-tagged leading paragraph, then roxygen will use that both for the title and the description.

**Comment by maelle** [comment]
oh ok it was the space on the empty line, I understand :woman_facepalming:

**Comment by maelle** [comment]
thank you! probably not very common indeed

**Comment by gaborcsardi** [comment]
Hopefully regular space characters do not do this. If they do, then it is worth warning for this, I think. If it only happens for non-breaking and other special Unicode spaces, then I am not sure.

We could also fix it, potentially, it might be the case that we just need a more inclusive regex.

**Comment by maelle** [comment]
:+1: I'll pay more attention to space next time I encounter this :eyes: :pray:
