### ISSUE TITLE
Typo in articles/rd.html: fix `@example` into `@examples`

### ISSUE THREAD

**Issue by ramiromagno** [r-lib/roxygen2#1414]
I think that when you mention the tag `@example` (in yellow background below) you meant `@examples`.

(_As an alternative to the screenshot, I tried to find the permalink for this piece of text in [vignettes/rd.Rmd](https://github.com/r-lib/roxygen2/blob/HEAD/vignettes/rd.Rmd) but the source Rmd and the rendered html do not seem to match..._)

![snap](https://user-images.githubusercontent.com/19862384/183317449-0da5da00-2021-4fe9-8493-f3b3af8a8407.png)

**Comment by hadley** [comment]
I don't see this text any more so it must have been fixed.
