### ISSUE TITLE
DOI handling issues

### ISSUE THREAD

**Issue by HenningLorenzen-ext-bayer** [r-lib/roxygen2#1417]
- DOI is *not* extracted from `http://dx.doi.org/<doi>`-style URLs e.g. `http://dx.doi.org/10.1000/1`
- DOI special characters are not unqoted, e.g. `https://doi.org/10.1000/456%23789` should be resolved to `doi:10.1000/456#789`

Reference:
https://www.doi.org/syntax.html

**Comment by hadley** [comment]
Could you provide some context please?
