### ISSUE TITLE
Conditional cross-references of `Suggest`ed packages

### ISSUE THREAD

**Issue by ngreifer** [r-lib/roxygen2#1424]
There are times when I want to cross-reference a help page in another package but I don't necessarily need my users to have that package installed, e.g., because the package's functions are used no where else in my package and the cross-reference is just to provide users with additional (optional) information. This suggests the package should be in my package's `Suggests`. However, CRAN requires that a package can be built without packages in `Suggests`; normally this would create a failure if the cross-referenced package is only in `Suggests` and not `Imports`. To avoid this problem, I use conditional cross-references in my packages that don't use `roxygen2`. This works using the following Rd syntax:

```
\ifelse{\Sexpr[results=rd,stage=render]{requireNamespace("foo", quietly = TRUE)}}{\code{\link[foo:bar]{foo::bar()}}}{\code{foo::bar()}}
```

So, when package `foo` is installed, this expands to `\code{\link[foo:bar]{foo::bar()}}`, a cross-reference to `foo::bar` with text that appears like `foo::bar()`, and when `foo` isn't installed, this expands to `\code{foo::bar()}`, text that appears like `foo::bar()` without a cross-reference. Because I set `stage=render`, the cross-references are checked and activated whenever the help page is loaded.

I am wondering if `roxygen2` could implement such an expansion when using, e.g., `[foo::bar()]`. For `Import`ed packages, this doesn't change anything because the package is installed. For `Suggest`ed packages, this creates a failsafe against improper cross-references to packages not installed while ensuring the correct cross-reference when the package is installed. This keeps the installation of the package lean (i.e., `foo` can be `Suggest`ed and doesn't need to be installed), staisfies CRAN's requirements for the package to be able to be built without `Suggest`ed packages installed, and still provides the user with the potential for a helpful cross-reference. In this way, it functions similarly to the `@examplesif` tag.

In my packages, I use the following macro to create `\pkgfun{}{}`, which implements the conditional cross-reference above.
```
\newcommand{\pkgfun}{\ifelse{\Sexpr[results=rd,stage=render]{requireNamespace("#1", quietly = TRUE)}}{\code{\link[#1:#2]{#1::#2()}}}{\code{#1::#2()}}}
```

I'm hoping something like this could be implemented in `roxygen2`. Thank you for considering my suggestion.

**Comment by gaborcsardi** [comment]
Unfortunately `\Sexpr` means that `R CMD build` installs the package and builds the PDF manual, which is annoying for developers, so it is unlikely that we would make `[foo::bar()]` generate a render-time `\Sexpr` expression.

**Comment by ngreifer** [comment]
I see. `devtools::submit_cran()` builds the manual anyway, so I don't think this would be a detriment to the workflow of those using `r-lib` tools. It also doesn't have to be a requirement, but perhaps it could be an option for developers to enable. For me, anyway, having to build the manual is a tiny cost for this convenience.

**Comment by gaborcsardi** [comment]
We don't only call `R CMD build` when submitting a package to CRAN, but e.g. it is called by `remotes::install_github()` and friends, and although the manual is not build by default there, the package is still installed twice. (AFAIR this is a bug that we reported.) Which might be OK for you, but I am fairly sure that it is not OK for the people installing stringi, and other packages with lots of compiled code.

I wish it was possible to avoid the special handling of the package if `\Sexpr` is only used in the HTML manual, but that's not currently the case.

A smaller, probably fixable issue is that `requireNamespace()` loads the package you are linking to, and that seems unnecessary just to create a link.

**Comment by hadley** [comment]
I don't believe that "CRAN requires that a package can be built without packages in Suggests" is true — certainly no package that uses testthat can be built without suggested packages installed.

Overall I don't think implementing this feature is worth the cost. Even though I'm closing this issue, I really appreciate the feedback, and hope you'll continue to contribute in the future 😄
