### ISSUE TITLE
inheritParams does not find doc'ed multi-params

### ISSUE THREAD

**Issue by LiNk-NY** [r-lib/roxygen2#1426]
When multiple parameters are documented in a single `@param` or `\arguments{ \item{a, b}{} }`, the referent documentation does not include the documentation of that parameter.

### Minimal example

```r
#' test function
#' This is a test function
#' @return A message
#'
#' @inheritParams testing
#'
#' @export
test <- function(b) {
    message("This is a test")
}


#' Another test function
#' @param a,b character(1) A letter, either lowercase or uppercase
#' @return Another message
#'
#' @export
testing <- function(a, b) {
    message("This is also a test")
}
```

The `test` function does not get any generated documentation for argument `b` even though it inherits the arguments of the `testing` function which are documented.

### Expected behavior

`test.Rd` should have the following included:

```Rd
\arguments{
\item{b}{character(1) A letter, either lowercase or uppercase}
}
```

### Observed behavior

The `\arguments` section is missing from the `test.Rd`.

### Roxygen version

`RoxygenNote: 7.2.1` 

### Example repository

https://github.com/Link-NY/testPkg

cc: @hadley

**Comment by hadley** [comment]
See the news:

> `@inheritParams` now only inherits exact multiparameter matches, so if you're inheriting from a function with @param x,y you'll only get the parameter documentation if your function needs docs for both x and y (#950).

And please don't `@` me unless there's some specific urgent issue that I need to be aware of. This is not such an issue.

**Comment by LiNk-NY** [comment]
Thanks Hadley. Perhaps include the note in the issue template.
