### ISSUE TITLE
Feature request: Allow additional text in function @template block

### ISSUE THREAD

**Issue by mnneely** [r-lib/roxygen2#1427]
Hello, I'd like to request that @template may be supplemented with additional text inline. This will accommodate arguments shared across functions which nonetheless may have slight differences, such as the default value of the argument.

For example, if the template mult.R file contains this:

#' @param mult Value to multiply by.

then the following roxygen2 code 

#' @template mult Default is 2.
#' @param log ...

renders as

\arguments{
\item{mult}{Value to multiply by. Default is 2.}
\item{log}{...}
}

Any text after the name of the template file, up until the next roxygen keyword, would be appended to the template for the argument in the .Rd file.

Thanks so much.

**Comment by hadley** [comment]
We are not planning to develop `@template` further. Please see https://roxygen2.r-lib.org/dev/articles/reuse.html for the approaches we now recommend.

**Comment by mnneely** [comment]
Thanks for pointing that out. It's a good solution that allows me to wrap the inserted, recycled text with custom text before and/or after. Through trial and error I learned a few things that I'll include here for posterity, or correction as the case may be. 

* My function reads the source file and returns a character vector of length one, catenating all the lines of the source file together. I left the files in the man-roxygen folder as .R files with roxygen style markup, so my function has to strip the leading "#' ". I also had problems forcing line breaks, so made a hack to replace <br> with "  \n" to force the break. I found that easier to read than putting "  \n" in the source file. 
* Markdown lists didn't seem to render so I resorted to \itemize{}, \item{} in the source files, which worked.

The function I wrote is below. 

```
template <- function(name){
  insert <- readLines(paste0("man-roxygen/", name,".R")) %>%
    stringr::str_replace("#' ","") %>%
    stringr::str_replace("<br>","  \n")
  insert <- c(insert, "  \n")
  insert <- paste(insert, collapse = " ")
  return(insert)
}
```

Example.R:

#' Some text
#' \itemize{
#' \item{first}
#' \item{second}
#' }
#' More text\<br\>
#' New line for more text
#' This text continues on the same line as the previous.


I insert inline R code in my roxygen documentation wherever I want to include templated text:
\`r template("Example")\`

Comments, suggestions welcome.

**Comment by gaborcsardi** [comment]
For the record, markdown lists definitely work, maybe you forgot to leave an empty line before the list?

``` r
fun <- function() "* it1\n* it2\n"
roxygen2::roc_proc_text(
  roxygen2::rd_roclet(), 
  "#' Name\n#'\n#' `r .GlobalEnv$fun()`\n#' @md\nf <- function() NULL\n"
)[[1]]
#> % Generated by roxygen2: do not edit by hand
#> % Please edit documentation in ./<text>
#> \name{f}
#> \alias{f}
#> \title{Name}
#> \usage{
#> f()
#> }
#> \description{
#> \itemize{
#> \item it1
#> \item it2
#> }
#> }
```

<sup>Created on 2022-09-26 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
