### ISSUE TITLE
process scripts not part of a package

### ISSUE THREAD

**Issue by ggrothendieck** [r-lib/roxygen2#1428]
There used to be a package called  [document](https://cran.r-project.org/package=document)  on CRAN and on [gitlab](https://gitlab.com/fvafrCU/document) that, given an R script with roxygen markup, would produce pdf, html and txt reference manuals.  It provided an easy path to developing a package since the same scripts could later be incorporated into an eventual package. It called the the roxygen2 package to perform the actual documentation.  That package was recently removed from CRAN.

It would be useful if this functionality were incorporated into roxygen2 itself or it could be a separate package that used roxygen2. There are likely many more people who write scripts than write packages and this would likely make roxygen2 more widely used.  Also it would provide an easy path from writing a script to an eventual package.

There still exists the [docstrings](https://cran.r-project.org/package=docstrings) package on CRAN which supports python-like docstrings within functions using roxygen markup. Like python docstrings it expects the markup to be in the function itself rather than before it and generates interactive help rather than manuals.  It has not been updated for many years.  This is actually quite a good idea and it might be nice if roxygen2 also supported docstrings.  The advantage of this is that since the roxygen is within the function the docstrings help system can find it if the function is loaded given only the function without knowing what script it came from.

There is also the [box](https://cran.r-project.org/package=box) package on CRAN which can be used for generating interactive help from roxygen markup but its focus is on modules rather than documentation and like docstrings it does not generate manuals.  

There are really several possible features here:
- generate reference manual from script
- an interactive help command that given an roxygen documented function from a script shows the help
- allow docstrings as an alternative to the existing way roxygen works and possibly have a conversion function to go back and forth.

**Comment by hadley** [comment]
Unfortunately I think this out of scope for roxygen2 because it's our belief that making a package is very simple and so we'd rather spend our limited time helping people learn to make packages rather than building tools so that they don't have to.

**Comment by ggrothendieck** [comment]
It is easy for me to create one but it is not easy for many of the people I deal with.   They know a bit of R but are not R developers and have work to do.  Figuring out how to rebuild packages and modify code that is in a package just adds another obstacle that they don't want.

Of course many people do understand that this is a problem.  That is why docstrings, box and document exist or existed.
