### ISSUE TITLE
`@includeRmd` needs to pass fixed width to `rmarkdown::render()`

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/roxygen2#1430]
And maybe other reproducible global options?

Probably around here? https://github.com/r-lib/roxygen2/blob/include-rmd-warning/R/rd-include-rmd.R#L52-L68

Context is that in vctrs @lionel- and I keep overwriting each other when we `document()` the package. In particular, files included by `@includeRmd` seem to change with respect to the width depending on who is calling `document()`. Here is an example where the git history of `theory-faq-coercion.Rd` shows us overwriting each other.
https://github.com/r-lib/vctrs/commits/main/man/theory-faq-coercion.Rd

The changes look something like this 

<img width="946" alt="Screen Shot 2022-09-19 at 11 07 55 AM" src="https://user-images.githubusercontent.com/19150088/191055872-0977142c-6997-4b4a-a937-526a64debb07.png">

**Comment by gaborcsardi** [comment]
It could certainly do that, but it'll still be annoying that when you knit the Rmd from the IDE, then `width` will not apply. (And the output of that might be cached and re-used by roxygen2.)

So I am afraid that the only reliable way to set these parameters is from the Rmd itself.

FWIW the roxygen2 default can also be set with something like this (untested) in `man/roxygen/meta.R`:
```r
list(
  markdown = TRUE,
  knitr_chunk_options = list(
    R.options = list(width = 80)
  )
)
```

(and you can remove `Roxygen:` from `DESCRIPTION`.

(It is probable that if you set `R.options` yourself in the `Rmd` for some reason, then you'll have to repeat `width = 80` there, I don't think knitr will merge the two sets of options.)
