### ISSUE TITLE
\doi{} not rendered in development mode

### ISSUE THREAD

**Issue by ramiromagno** [r-lib/roxygen2#1439]
Shift+Ctrl+L

![snap](https://user-images.githubusercontent.com/19862384/199013973-893191df-b868-435d-be32-64613f7e0a78.png)

Shift+Ctrl+B

![snap](https://user-images.githubusercontent.com/19862384/199014191-5dc034ae-1764-4707-bf87-25fbb19549ba.png)

**Comment by hadley** [comment]
You need the dev version of pkgload and RStudio if you want these to work in development mode.
