### ISSUE TITLE
`@family` creates broken links to functions

### ISSUE THREAD

**Issue by jgutman** [r-lib/roxygen2#1440]
In the [`roxygen2` vignette ](https://cran.r-project.org/web/packages/roxygen2/vignettes/rd-formatting.html#links), we see that a markdown of the format `[func()]` will be typeset in the Rd file as `\code{\link[=func]{func()}}`. 

However, when we use the `@family` tag to notate a group of related functions, these functions get marked in the generated `\seealso` section as `\code{\link{func}()}` instead of `\code{\link[=func]{func()}}`. When these are rendered to HTML in sites like https://rdrr.io/, the generated links do not appear to work because of the extra parentheses within the link target. 

Expected behavior

```
#' @family My family of functions
#' @export
func1 <- function(....

#' @family My family of functions
#' @export
func2 <- function(....
```

generates 

```
\seealso{
My family of functions
\code{\link[=func1]{func1()}}
\code{\link[=func2]{func2()}}
}
```

**Comment by gaborcsardi** [comment]
I guess `@family` could include the `()` in the link text, just like `[func()]` links do. (Or maybe `[func()]` should omit the `()` from the link?) 

But AFAICT `@family` does not create broken links, the links work just fine in the HTML documentation, and also in pkgdown. So in the end this is a bug in rdrr.io.

**Comment by jgutman** [comment]
Okay, that definitely could be the case, I just noticed the format was different from links generated with `[func()]` so wasn't sure if that was the problem. Thanks!

**Comment by hadley** [comment]
Yeah, I think this is an rdrr problem 😄
