### ISSUE TITLE
The specified file is not readable

### ISSUE THREAD

**Issue by kongdd** [r-lib/roxygen2#1443]
I am using windows. `kong-nas` is my Internet drive `Z`. 

`Roxygen2` automatically convert the path `Z:` into the internet path `kong-nas\CMIP6`. After that, `Roxygen2` can not recognize the internet path, and give me an error:

```R
devtools::document()
ℹ Updating ET.evaluation documentation
ℹ Loading ET.evaluation
Error: The specified file is not readable: \\kong-nas\CMIP6\Researches\ET_evaluation\NAMESPACE
```

Actually, the correct path of NAMESPACE should be `Z:/Researches/ET_evaluation/NAMESPACE`. 

Any idea how to solve this issue?

**Comment by gaborcsardi** [comment]
What is the output of `traceback()` right after the error happens?

**Comment by kongdd** [comment]
Thanks for your quick response. 
```R
traceback()
11: stop(txt, obj, call. = FALSE)
10: .errorhandler("The specified file is not readable: ", object,
        mode = errormode)
9: check_file(object, errormode)
8: digest::digest(file = path)
7: same_contents(path, contents)
6: write_if_different(NAMESPACE, results, check = TRUE)
5: roclet_preprocess.roclet_namespace(X[[i]], ...)
4: FUN(X[[i]], ...)
3: lapply(roclets, roclet_preprocess, blocks = blocks, base_path = base_path)
2: roxygen2::roxygenise(pkg$path, roclets)
1: devtools::document()
```

I can prove `NAMESPACE` is readable:

``` r
setwd("Z:/Researches/ET_evaluation")
getwd()
#> [1] "Z:/Researches/ET_evaluation"

library(magrittr)

f = fs::path_real(".") %>% paste0("/NAMESPACE")
print(f)
#> [1] "//kong-nas/CMIP6/Researches/ET_evaluation/NAMESPACE"

strs = readLines(f)
print(head(strs))
#> [1] "# Generated by roxygen2: do not edit by hand"
#> [2] ""                                            
#> [3] "S3method(as.Date,PCICt)"                     
#> [4] "S3method(as.data.table,SpatRaster)"          
#> [5] "export(as.SpatRaster.SpatialPixelsDataFrame)"
#> [6] "export(as_SpatialPixelsDataFrame)"
```

<sup>Created on 2022-11-16 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by kongdd** [comment]
The error originates from `digest::digest`:

``` r
library(magrittr)
library(fs)

# `devtools::document` used the function `fs::path_real`
f = fs::path_real("Z:/Researches/ET_evaluation") %>% paste0("/NAMESPACE")
print(f)
#> [1] "//kong-nas/CMIP6/Researches/ET_evaluation/NAMESPACE"

digest::digest(file = f)
#> Error: The specified file is not readable: //kong-nas/CMIP6/Researches/ET_evaluation/NAMESPACE
```

<sup>Created on 2022-11-16 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

So, should I transfer my issue into digest?

**Comment by gaborcsardi** [comment]
We could use another MD5 implementation, there is `tools::md5sum()` (although it also does not work well on Windows on older R versions but there is a workaround), and there is `cli::hash_file_md5()` in the new version of cli. Hopefully one of these will work on network drives:
```r
❯ digest::digest(file = "works/cli/DESCRIPTION")
[1] "c8b6e7fbd3f9d93ad18d77f4f0358242"

❯ tools::md5sum("works/cli/DESCRIPTION")
             works/cli/DESCRIPTION
"c8b6e7fbd3f9d93ad18d77f4f0358242"

❯ cli::hash_file_md5("works/cli/DESCRIPTION")
[1] "c8b6e7fbd3f9d93ad18d77f4f0358242"
```

**Comment by kongdd** [comment]
Thanks. I can help to test the new function. Waiting for your good news. 
> PS: I am using the latest R, v4.2.2.

**Comment by gaborcsardi** [comment]
Can you try running `tools::md5sum()` and `cli::hash_file_sha256()` on the network path, to see if they work? Thanks! (This does not need dev cli.)

**Comment by kongdd** [comment]
Sorry. On the way to home. Just arrived.
Those two options all work well.

**Comment by gaborcsardi** [comment]
Just remembered that there is also `rlang::hash_file()`, can you please try that one as well when you have time. Thanks again!

**Comment by kongdd** [comment]
`rlang::hash_file()` also works

**Comment by gaborcsardi** [comment]
Will be fixed here: https://github.com/r-lib/roxygen2/pull/1444

OTOH we just had a roxygen2 release, so this won't be in a CRAN release soon, probably, sorry. Nevertheless, you can install the branch that fixes it.

**Comment by kongdd** [comment]
Got it. Thanks for your time and quick action.
