### ISSUE TITLE
Extending roxygen vignette should mention how to add your extension to your workflow

### ISSUE THREAD

**Issue by hughjonesd** [r-lib/roxygen2#1447]
I've been playing with a [small package to write doctests in roxygen](https://github.com/hughjonesd/doctest). The "extending roxygen" vignette has been very helpful. One thing I missed was some guidance on how to add a new roclet to your workflow.

Something like this:

```

## Adding a roclet to your workflow

To use a roclet when developing a package, call

    ```r
    roxygen2::roxygenize(roclets = "yourPackage::roclet")
    ```

where `yourPackage::roclet` is the function which creates the roclet.

You can also add the roclet to the target package DESCRIPTION file, like:

    ```r
    Roxygen: list(roclets = c("collate", "rd", "namespace", "yourPackage::roclet")) 
    ```

You can also optionally add your roclet package to the target package as a Suggests dependency:

    ```r
    usethis::use_dev_package("yourPackage", type = "Suggests", remote = "yourGithubID/yourPackage")
    ```

You don't have to do this, but it will help other developers working on the target package.
```

I can provide a PR if you want.

**Comment by hadley** [comment]
A PR would be great if you're still interested.

**Comment by hughjonesd** [comment]
First draft...
