### ISSUE TITLE
Exclude a package or import from the `NAMESPACE` file.

### ISSUE THREAD

**Issue by nick-robo** [r-lib/roxygen2#1448]
# Description
In some cases, it is desirable to exclude a function from the namespace while still having it documented in the doc string. In particular, this may be necessary to resolve conflicts between two functions with the same name. This can lead to errors in automated code checks. For example, in the case of Bioconductor publication, reviewers tend to be highly inflexible to any warnings being present.

# Issue
As it works currently, this involves manually deleting the entry from namespace each time it is regenerated. As long as a function is utilised in the form `package::function` and it is imported in the `DESCRIPTION` file, it doesn't cause any problems. 

# Possible Solution
Would it be possible to include a tag somewhere indicating that the import or package should not be included in the namespace. Is there a preferable way to deal with this case?

# Note
For completeness, the two functions that caused the issue for me are `ensembldb::select` and `dplyr::select`. They are both used in the same function.

**Comment by gaborcsardi** [comment]
If you don't want to import a function, then just remove the corresponding `@import` or `@importFrom` tag. roxygen2 does not look at fully qualified `::` calls at all, these have nothing to do with roxygen2.

**Comment by nick-robo** [comment]
The problem with your suggestion is that the Bioconductor review also requires that all external functions be documented in the doc string. It seems like I can't win:
- I include the roxygen import tag ⇾ two functions with the same name necessarily overwrite each other ⇾ warning during import about overwriting ⇾ my package doesn't get reviewed.
- I omit the roxygen import tag ⇾ warning about undocumented functions being used ⇾ my package doesn't get reviewed.

Is there any work around in this situation?

**Comment by gaborcsardi** [comment]
> warning about undocumented functions being used

If Bioconductor requires you to import every function you use, which I doubt, that's not something that roxygen2 can help with. Can you please point me to this requirement?

> Is there any work around in this situation?

Any chance that you can show us the source code of your package?

**Comment by nick-robo** [comment]
Turns out I was labouring under the false assumption that everything must be documented. 

To me, it seems like a sane practice, so I try to implement it wherever I can. 

An example of where including in namespace by default may cause issues is [this](https://github.com/SydneyBioX/scFeatures/blob/a40fddce4b7b7a7a1d1d23a3873f6325a70154a2/R/helper_pathway.R#L8). This is where the problem was occurring. I solved it by removing all roxygen that referred to importing `ensembldb::select`.

**Comment by gaborcsardi** [comment]
I don't entirely follow this, the function you are linking to does not have any roxygen2 comments at all. 

If the issue being able to use both `ensembldb::select()` and `dplyr::select()` in the same package, then yes, you cannot import both of them. This does not have much to do with roxygen2, but it is just how R packages work. An import is for the whole package, not a single function.

The solution is to import only one of them (or none is even better!) and use the explicit `::` notation. (`::` calls are independent of imports.)

Note that imports are also completely independent of documentation. You can still document every function if you like, even internal ones (see e.g. https://blog.r-hub.io/2019/12/12/internal-functions/#how-to-document-internal-functions). 

Just do not import two functions with the same name, from two different packages. That is not allowed in R packages.
