### ISSUE TITLE
Writing a function to insert param

### ISSUE THREAD

**Issue by bryanhanson** [r-lib/roxygen2#1456]
Trying to stop using the `@template` approach.  So I wrote:

```
#' @param `r .write_param_radius()`
```
and the function looks like this:

```
#' @noRd
.write_param_radius <- function() {
  value <- "radius Numeric.  A value on `[0, 1]`."
  return(value)
}
```

but this produces the following in the Rd file, which is not parsed correctly:

```
\arguments{
\item{`r}{.write_param_radius()`}
}
```

I can successfully write analogous functions for other tags but `@param`  is giving me trouble, and I can't find any relevant examples on the internet.  I've tried splitting the pieces out but to no avail.  Suggestions appreciated.

**Comment by gaborcsardi** [comment]
Can you please try to create a reproducible example, either as described in https://github.com/r-lib/roxygen2/blob/main/.github/SUPPORT.md or by linking to a repository of yours that demonstrates this? Thank you!

**Comment by bryanhanson** [comment]
Of course, thanks for the pointer as to how.

```
.write_param_radius <- function() {
  value <- "radius Numeric.  A value on `[0, 1]`"
  return(value)
}

library("roxygen2")

roc_proc_text(rd_roclet(), "
#' Title
#' @param `r .write_param_radius()`
foo <- function(radius) print(radius)
")
```

Which results in:
```
$foo.Rd
% Generated by roxygen2: do not edit by hand
% Please edit documentation in ./<text>
\name{foo}
\alias{foo}
\title{Title}
\usage{
foo(radius)
}
\arguments{
\item{`r}{.write_param_radius()`}
}
\description{
Title
}
```

**Comment by gaborcsardi** [comment]
Yes, I am afraid that you cannot generate two roxygen tag parameters with a single `` `r ` `` block. Moreover the first parameter, the argument name does not support markdown, so that cannot be generated with code. Something like this should work for the description, though:
```r
.write_param_radius <- function() {
  "Numeric.  A value on `[0, 1]`"
}
```

```r
#' Title
#' @md
#' @param radius `r .write_param_radius()`
```

**Comment by bryanhanson** [comment]
Great thanks.  Thought I had tried that but apparently not.  Much appreciated.
