### ISSUE TITLE
`document()` should signal duplicated `@importFrom`

### ISSUE THREAD

**Issue by DanChaltiel** [r-lib/roxygen2#1462]
Hi,

Consider the following `roxygen2` template:
```r
#' @importFrom stats filter
#' @importFrom dplyr filter
NULL
```

Running `devtools::document()` with this one will cause a duplicate `importFrom()` statement in `NAMESPACE`, which in the end causes a warning when loading the package:

```r
devtools::load_all(".")
#i Loading my_pkg
#Warning message:
#replacing previous import ‘dplyr::filter’ by ‘stats::filter’ when loading ‘my_pkg’ 
```

Obviously, I figured this out by mistake and this was easy to correct, but it might have been nice that `document()` had thrown an error or a warning when generating `NAMESPACE`.

**Comment by hadley** [comment]
And folks do sometimes put in front of each function that uses it. So I don't think it's worth changing.

**Comment by DanChaltiel** [comment]
@hadley I'm not 100% sure that you understood the issue.

In https://r-pkgs.org/dependencies-in-practice.html#in-code-below-r, you state as a "reasonable location" for `@importFrom`: 

>As close as possible to the usage of the external function. With this mindset, you would place `@importFrom` in the roxygen comment above the function in your package where you use the external function.

In that fashion (which I prefer myself), you can totally put `@importFrom stats filter` and `@importFrom dplyr filter` in indifferent R files and forget about it. 

The `NAMESPACE` file will then make no sense importing the same function from 2 different packages, and one will mask the other unpredictably.

I totally agree this should be very uncommon and might probably not be worth changing though, as the warning is somehow informative enough :-)
