### ISSUE TITLE
Documentation for package name only disappearing after devtools::install()

### ISSUE THREAD

**Issue by beginb** [r-lib/roxygen2#1464]
Hi,

I've finished writing the package documentation for all the functions. In a separate Rd file I wrote the documentation for the package name. It is in the man folder only as an Rd file. Before I carry out the command devtools::install(), the documentation works and it shows up. However, after I carry out the command devtools::install(), it disappears, saying that there is no documentation for the package name. Two things I have done already is made sure there are no errors in the format of the documentation, and I have done it multiples times. 

Thanks

**Comment by gaborcsardi** [comment]
Can you please show us your package? That would potentially help us telling you what is going wrong. Thanks!
