### ISSUE TITLE
lists within tables causing LaTeX error

### ISSUE THREAD

**Issue by schradj** [r-lib/roxygen2#1479]
Disregard the horrible documentation here, this isn't the actual function nor is it the actual documentation but a simple example which contains the same issue.  
I have function that runs a query for the user and returns the resulting data frame.  I have included within the documentation for the function a description of each of the fields in the table.  In some cases, i list the possible values for a specific column by including a bulleted list in the second column of the table in documentation which describes each field.  

I am using roxygen2 to create the documentation and all of the documentation is generated without any errors when I buiild the package.  The documentation for the function appears with the correct formatting when you run help() on the function.  If you pull this .rd down below into RStudio, you can hit the preview button at the top and see that it displays correctly.

```
% Generated by roxygen2: do not edit by hand
% Please edit documentation in R/getData.R
\name{GetData}
\alias{GetData}
\title{Retrieves Data Frame}
\usage{
GetData()
}

\value{
A data frame
}
\description{
Returns your data frame 
}
\section{Table Fields}{

The fields in this table are as follows:\tabular{ll}{
   Field \tab Description \cr
   Field1 \tab Description1 \cr
   Field2 \tab Possible Values: \itemize{ \item B \item R \item N} \cr
\cr
}
}
```

However, I get an error when I run devtools::build_manual()

Running  ``` callr::rcmd("Rd2pdf", cmdargs = c("--output=test.pdf", "test.Rd")) ```,
I get the following error....

```
Converting Rd files to LaTeX ...\nError in texi2dvi(file = file, pdf = TRUE, clean = clean, quiet = quiet,  : \n  Running 'texi2dvi' on 'Rd2.tex' failed.\nLaTeX errors:\n! LaTeX Error: Something's wrong--perhaps a missing \\item.\n\nSee the LaTeX manual or LaTeX Companion for explanation.\nType  H <return>  for immediate help.\n ...  
```

As soon as I remove the bulleted list from the documentation, it generates the pfd without error.

**Comment by hadley** [comment]
That sounds like an Rd issue, not a roxygen2 issue, so there's not much we can do about it, sorry.
