### ISSUE TITLE
Need context information for errors in roclet_process

### ISSUE THREAD

**Issue by ralmond** [r-lib/roxygen2#1490]
This issue is inspired by #1421, I was having a similar problem, and in entering the debugger, I noticed that the `block` data element in the function call `block_to_rd` had information about the file and line number that was being processed at the time.  This information needs to be added to any error message which is thrown by `block_to_rd`

My suggested fix would be to have `roclet_process.roclet_rd()` (possibly other `roclet_process` messages catch errors from calls to `block_to_rd()`, add the file and line number to the error message, and then rethrow the error.  This is robust to even unexpected error types.

**Comment by hadley** [comment]
Can you please provide a reprex that illustrates the problem?

**Comment by ralmond** [comment]
``` r
roxygen2::roxygenise("/home1/ralmond/Projects/Foo")
#> ℹ Loading Foo
#> Error in rd_section_minidesc(name = object_name(block$object), desc = tag$val$description, : is_string(name) is not TRUE
```

<sup>Created on 2023-06-22 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
Here is the minimal project.

[Foo.zip](https://github.com/r-lib/roxygen2/files/11840734/Foo.zip)

NOTE BENE!   This issue is NOT about the specific error being generated, the other issue covers that.  This issue is about the fact that uncaught exceptions, such as this one, give no information about where the error occurs, not even the name of the file, or the block being operated on.

**Comment by hadley** [comment]
Thanks!
