### ISSUE TITLE
Unfriendly error for '@include zoo' instead of '@import zoo'

### ISSUE THREAD

**Issue by MichaelChirico** [r-lib/roxygen2#1497]
The logic for processing `@include` could go for a sanity check. Using `@include zoo` by mistake gives some hard-to-trace error:

```
Warning in normalizePath(file.path(path, "R", collate)) :
  path[3]="...R/zoo": No such file or directory
Warning in file(con, "r") :
  cannot open file '...R/zoo': No such file or directory
Error in file(con, "r") : cannot open the connection
Calls: Main ... parse_package -> lapply -> FUN -> read_lines -> <Anonymous> -> file
In addition: Warning message:
'Collate' must contain a list of .R files
```

In retrospect this makes sense, but it took quite some time to debug. Is it valid to `@include` a non-R file? Couldn't we check `file.exists()` for `@include` directives to prevent this with a friendlier error?

**Comment by hadley** [comment]
Yup, could definitely do better here.

**Comment by hadley** [comment]
This is a little trickier than I had thought because `@include` is handled specially (since it needs to be run before loading the package). Will need some custom code in `generate_collate()` to detect files that aren't found in `R/`, warn, and drop from the collate.

**Comment by hadley** [comment]
Whoops, accidentally committed part of an experiment in #1293
