### ISSUE TITLE
deps unavailable (stringi, stringr)

### ISSUE THREAD

**Issue by musvaage** [r-lib/roxygen2#1506]
R version 4.3.1

running `install.packages("roxygen2")` failed

ERROR: dependency 'stringi' is not available for package 'stringr'

ERROR: dependencies 'stringi', 'stringr' are not available for package 'roxygen2'

Warning messages:
1: In install.packages("roxygen2") :
  installation of package 'stringr' had non-zero exit status
2: In install.packages("roxygen2") :
  installation of package 'roxygen2' had non-zero exit status

**Comment by musvaage** [comment]
@gaborcsardi 

Time permitting have you any insight into cause of the ERRORs?

**Comment by gaborcsardi** [comment]
They are certainly available, so check your setup, e.g. `getOption("repos")`:
https://cran.rstudio.com/web/packages/stringi/
https://cran.rstudio.com/web/packages/stringr/index.html

**Comment by musvaage** [comment]
On Aug 18, 2023, I had made several attempts at running `install.packages("roxygen2")` which all failed.

My recollections from that day was that the downloads occurred but the cited ERRORs showed up during the build.

Today I again ran `install.packages("roxygen2")` which completed successfully. 

```
$ R --no-echo -e 'getOption("repos")'
                              CRAN 
"https://mirrors.dotsrc.org/cran/" 
$ 
```
