### ISSUE TITLE
_PACKAGE sentinel: URL in DESCRIPTION that are separated by spaces are not parsed correctly

### ISSUE THREAD

**Issue by daattali** [r-lib/roxygen2#1507]
According to [R-exts](https://cran.r-project.org/doc/manuals/R-exts.html#The-DESCRIPTION-file):

> The ‘URL’ field may give a list of URLs separated by commas or whitespace

However, I noticed that if I use multiple URLs in DESCRIPTION with a space delimeter and then document using `_PACKAGE`, the resulting help file doesn't parse out the space and the resulting link is a (broken) concatenation of both URLs.

If I separate the URLs with a comma, then everything works as intended.

**Comment by hadley** [comment]
I think commas are so radically more common than whitespace, I'm happy to leave this as is minor infelicity of roxygen2.
