### ISSUE TITLE
Use of `@import` or `@importFrom` where the package is to be archived

### ISSUE THREAD

**Issue by rsbivand** [r-lib/roxygen2#1509]
In working on retiring `rgdal`, `rgeos` and `maptools`, which will be archived from CRAN in October 2023 (see https://r-spatial.github.io/evolution/ for details), I have found a clear regularity that users of `roxygen2` use `@import` very often without actually using any functionality from the imported package.

Many of the packages that have not yet taken steps to avoid problems from October have stale `@import` markup. 

While I realize that many package maintainers just run `devtools::document`, it seems possible that some steps, such as showing package startup messages, might be taken to indicate that attention is required. I have had to explain to maintainers that imports will not go away from description and namespace files if the import markup is still in place. 

I cannot see that any messages are issued either if imported packages are not available on the repositories listed in options.

Can you offer any help? I still have roughly 160 packages to assist, of which 120 with github issues, many have stale roxygen2 markup.

**Comment by hadley** [comment]
I'm not sure what we can do to help here. What were you thinking?

**Comment by rsbivand** [comment]
The difficulty was maintainers not finding stale markup for unavailable packages (locally, and/or on listed repos), which led to NAMESPACE continuing to import even if DESCRIPTION had been edited correctly. I'm not sure that anything can be done here or in `devtools::document`, but if there was a tool to check whether the output NAMESPACE contained references to unavailable packages, possibly local packages, that might have helped me advise the maintainers. Instead I most often grepped their source for traces and pointed them to file and line to remove. So maybe this issue could be closed; the r-spatial infrastructure packages are now archived and CRAN has stabilized.

**Comment by hadley** [comment]
If this ever happens again, you might find a GitHub search like https://github.com/search?q=org%3Acran+maptools+path%3ANAMESPACE&type=code to be helpful. The github cran org mirrors CRAN packages, making it easy to search them all.

**Comment by rsbivand** [comment]
Yes, but I had the source code locally from "most" rev-dep checks, so that let me customise the searches to packages failing CMD check when the retiring packages were not on the library path ("strong" plus insufficiently conditioned "weak"). The main "culprits" were not following your advice to prefer `@importFrom` before `@import` and had used the latter liberally, including in files from which all use of the previously `@import`-ed had been dropped, leaving relict `@import` mark-up. Might a "clean-up" utility re-examine the output `NAMESPACE` file and list the files+lines responsible for inclusion in `NAMESPACE`? Anyway, some tool to make it easier for maintainers to find possibly stale mark-up.
