### ISSUE TITLE
Problem using openxlsx2::wb_workbook with roxygen2

### ISSUE THREAD

**Issue by sbgraves237** [r-lib/roxygen2#1510]
How can I use the R6 coding in package openxlsx2 with roxygen2?  
Function 

[print.FCCquery in GitHub package sbgraves237/broadcastPower](https://github.com/sbgraves237/broadcastPower/blob/main/R/print.FCCquery.R)

includes 

`require(openxlsx2)`

with 

`wbO2 <- wb_workbook(title=xNm)
wbO2$add_worksheet(sheet='data.frame')`

This works when I source and test it locally, but GitHub Action complains:

'library' or 'require' call not declared from: ‘openxlsx2’ ... Please use :: or requireNamespace() instead.

The NAMESPACE file begins, "# Generated by roxygen2: do not edit by hand
".  I don't know how to fix this.  

When I tried, 

wbO2$openxlsx2::add_worksheet(sheet='data.frame')

document() 

gave

Error in `load_all()` ... unexpected '::'
66:   class(xdf) <- 'data.frame'
67:   wbO2$openxlsx2::
                    
What do you suggest?  Thanks, Spencer Graves

**Comment by gaborcsardi** [comment]
I don't think that this is not a roxygen2 issue. Instead of `library()` calls, import the needed objects in the `NAMESPACE` file.

**Comment by sbgraves237** [comment]
Hi, Gábor:


	  How can I edit the NAMESPACE file?


	  The NAMESPACE file begins, "# Generated by roxygen2: do not edit by 
hand".  I don't know how to fix this.


	  Thanks,
	  Spencer Graves

**Comment by gaborcsardi** [comment]
See the docs about importing objects here: https://roxygen2.r-lib.org/articles/namespace.html#imports

I.e. 
```
#' @importFrom pkg fun
```

**Comment by sbgraves237** [comment]
Hi, Gábor et al.:


	  Got it.  Thanks.


	  Spencer Graves


p.s.  I searched for things like that but missed the keyword "importFrom".
