### ISSUE TITLE
Add `import()` and `useDynLib()` directives first to `NAMESPACE`

### ISSUE THREAD

**Issue by krlmlr** [r-lib/roxygen2#1516]
Occasionally, I find the need to start with an empty `NAMESPACE` file so that it is recreated from scratch. (Example: methods removed.) In many packages, `load_all()` does not work with an empty `NAMESPACE` because the package code requires imported functions or dynamic libraries.

If the `import()` and `useDynLib()` (and perhaps `importFrom()`) directives came first, it would be easier to keep those and delete everything else. Perhaps this could also be an automated way of resolving those conflicts -- if loading fails, try to load with a `NAMESPACE` that only has imports and `useDynLib()` ?

**Comment by hadley** [comment]
I'd prefer to fix this properly, as in #1516.
