### ISSUE TITLE
Setting environment variable during `roxygenise()`

### ISSUE THREAD

**Issue by sebffischer** [r-lib/roxygen2#1517]
First and foremost, thank you for the great package and your efforts! :)

In the `mlr3` project we currently have some issues for which it would help if `roxygenise()` would set a global environment variable during its lifetime, similar to how pkgdload does it here: https://github.com/r-lib/pkgload/blob/681b36370887b5925304373edbb5e9ea9a87a6dd/R/load.R#L131

We need this environment variable to disable an optimization mechanism we have implemented during package loading, as it prevents the correct generation of R6 docs.

**Comment by mllg** [comment]
I would also appreciate this, especially since I see no downside for roxygen2 and the environment variable might also prove useful for future problems.

**Comment by hadley** [comment]
Yeah, seems reasonable given that we have so many similar env vars for testthat.
