### ISSUE TITLE
Weird bug: one file is not documented

### ISSUE THREAD

**Issue by RMHogervorst** [r-lib/roxygen2#1518]
I have a very weird bug. 
One of my files in a package is not picked up by roxygen2. 

And I can't figure out why?

The class is actually created and exported. but there is no documentation.

It is this file https://github.com/ropensci/charlatan/blob/feat/rearrange_locale/R/person-provider.R

```r
#' @title PersonProvider
#' @details Methods for Persons, methods for generating names.
#' @inherit BaseProvider note
#' @family ParentProviders
#' @export
#' @returns A PersonProvider object that can create names. 
PersonProvider <- R6::R6Class(
	...
```

What have I tried:
- changing the name of the file to `personprovidert.R` _(because maybe the name is special?)_
- copying the roxygen from another function and changing the names _(because maybe I mistyped something?)_
- checked the .Rbuildignore and .gitignore
- used `@rdname` in stead of `@title`
- moved from R 4.2.2 to R 4.3.1 with the latest version of Roxygen2
- Roxygen: list(markdown = FALSE) from TRUE

**Comment by gaborcsardi** [comment]
You have a `noRd` here: https://github.com/ropensci/charlatan/blob/abe58cadf0a3fa9f97b045f6c004115ae86ca762/R/person-provider.R#L85 

`@noRd` applies to the whole manual page.

**Comment by RMHogervorst** [comment]
Thank you so much! I never thought about looking further in the file!

**Comment by gaborcsardi** [comment]
roxygen2 parses the `#'` comments until the end of the function (or object) definition. This can be quite handy when you want to keep the a piece of the manual page close to the code it documents. E.g. this is an example I like: https://github.com/r-lib/cli/blob/d8883112a8060c1f011cccc9147dd35db03bb9c6/R/num-ansi-colors.R#L37
