### ISSUE TITLE
[Feature request] Allow renaming of a section when using the @inheritSection / @inherit tag

### ISSUE THREAD

**Issue by sebffischer** [r-lib/roxygen2#1519]
I find the  `@inheritSection` and `@inherit` tags quite convenient! However one restriction that they have is that it is not possible to change the name of the section that is inherited. It would be great if this was possible.

Let's say I have some documentation as below:

```r
#' @title Hello world
#' @description
#' Greets the world
#' @export
hello_world = function() {
  print("Hello world!")
}
```

I would like to be able to create another function `g` that inherits the roxygen2 @description content from function `f`, but under a different (section) name. I image this to work something like below:

```r
#' @title Hello world
#' @description
#' Calls function `hello_world`, see section *hello world* for more information.
#' @inherit hello_world description: hello world 
#' Greets the world
#' @export
g = function() {
  hello_world()
}
```

**Comment by hadley** [comment]
This sounds like a useful feature, but I think implementing it is going to be quite hard, and unfortunately I don't think it'll ever make it to the top of our to do list. Even though I'm closing this issue, I really appreciate the feedback, and hope you'll continue to contribute in the future 😄
