### ISSUE TITLE
Uncaught 'warnings' in test suite

### ISSUE THREAD

**Issue by MichaelChirico** [r-lib/roxygen2#1526]
Seen here:

https://github.com/r-lib/roxygen2/actions/runs/6736859738/job/18313066358?pr=1458

```
Warning:  Duplicate link reference '[roxygenize()]' at file10a052a396d2.knit.md line 8 column 1
Warning:  Duplicate link reference '[stringr::str_length()]' at file10a052a396d2.knit.md line 9 column 1
```

Better to mark these with `expect_warning()` or capture the warnings in a snaphot.

**Comment by hadley** [comment]
My recollection is that those are emitted by pandoc, and are hard to eliminate for some complicated reason.

**Comment by hadley** [comment]
These have now disappeared, because we've switched to parallel tests. Because they're omitted to some output stream we have no control over, they don't get passed back to the main testing thread.
