### ISSUE TITLE
Broken support for `#' @importFrom` with backticks not documented

### ISSUE THREAD

**Issue by krlmlr** [r-lib/roxygen2#1570]
roxygen2 7.3.0 fails for several of my packages. The only vaguely related NEWS entry I found is

> - `@importFrom` throws a friendlier error if you try and import a non-existing functions (@MichaelChirico, #1409).

Is the new behavior intended, is it worth waiting for a fix?

## roxygen2 7.3.0

``` r
library(roxygen2)

roc_proc_text(namespace_roclet(), "
  #' @importFrom purrr `%>%`
  NULL
  ")
#> ✖ <text>:2: @importFrom Excluding unknown export in from purrr: `` `%>%` ``.
#> [1] "importFrom(purrr,)"

roc_proc_text(namespace_roclet(), "
  #' @importFrom purrr %>%
  NULL
  ")
#> [1] "importFrom(purrr,\"%>%\")"
```

<sup>Created on 2024-01-14 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

## roxygen2 7.2.3

``` r
library(roxygen2)

roc_proc_text(namespace_roclet(), "
  #' @importFrom purrr `%>%`
  NULL
  ")
#> [1] "importFrom(purrr,`%>%`)"

roc_proc_text(namespace_roclet(), "
  #' @importFrom purrr %>%
  NULL
  ")
#> [1] "importFrom(purrr,\"%>%\")"
```

<sup>Created on 2024-01-14 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by MichaelChirico** [comment]
I confirm from `git bisect` 38166f0a97aeb57e2ddc695aa6dcddcdeb917e8c is the culprit

**Comment by dchiu911** [comment]
I am also getting similar errors when replacing backticks with quotations
```
#' @importFrom magrittr "%>%"
#' @importFrom purrr "%||%"
```

```
@importFrom Excluding unknown export in from magrittr: `"%>%"`.
@importFrom Excluding unknown export in from purrr: `"%||%"`.
```

**Comment by jdblischak** [comment]
Try `#' @importFrom magrittr %>%`. This should work with roxygen2 7.2.3 and 7.3.0

**Comment by klmr** [comment]
I think this is also responsible for the ‘box’ build failures: https://github.com/klmr/box/actions/runs/7535202942

**Comment by MichaelChirico** [comment]
@klmr I believe yours is related to this NEWS bullet:

https://github.com/r-lib/roxygen2/blob/767ec1b1c4dc43b4245ed4ee2334445968768f17/NEWS.md?plain=1#L16-L20

**Comment by klmr** [comment]
@MichaelChirico Thanks, but the warning isn’t the issue I am concerned about, although it a bit confusing, and in my case incorrect: you do *not* need to declare methods in `NAMESPACE`, even in R >3.6, for an internally defined generic as long as it is only used internally! Unfortunately I also can’t silence the warning in a backwards-compatible way: adding `#' @exportS3Method NULL` causes a different warning on previous versions of ‘roxygen2’. :-(

I am talking about the bug described in #1575.

**Comment by hadley** [comment]
And now on CRAN 😄
