### ISSUE TITLE
Checking for missing S3 method exports hangs "forever" if you have large data objects in the package

### ISSUE THREAD

**Issue by jranke** [r-lib/roxygen2#1593]
In package yet unpublished I have a large data object (the `.rda` file has about 6 MB). With current roxygen versions, the namespace roclet hangs here

https://github.com/r-lib/roxygen2/blob/main/R/namespace.R#L402

This is apparently very inefficient if you have large objects in `s3objects`. If I remove the data object from the package, namespace generation proceeds swiftly as usual.

**Comment by alexpghayes** [comment]
I'm running into this as well with https://github.com/alexpghayes/latentnetmediate and it's pretty debilitating. Downgrading to version 7.2.0 resolved my issue temporarily.

**Comment by jranke** [comment]
Hi, I wonder if noone with commit rights for roxygen is affected by this bug? What about @krlmlr or @DavisVaughan , could you maybe have a look?
