### ISSUE TITLE
`\usage()` length

### ISSUE THREAD

**Issue by olivroy** [r-lib/roxygen2#1624]
Related to #1617, but different.

For functions with many arguments, roxygen2 places all the arguments on different lines.

However, since R 4.2, there is html support in help files, which means you can scroll horizontally to see arguments if needed.

My point is that you have to scroll down a lot to see documentation of arguments.

See example for `tmap::tm_text()`.
![image](https://github.com/r-lib/roxygen2/assets/52606734/a47cffad-400f-4953-b9cc-68fd849f772c)

When functions are documented together, this makes it even worse in my opinion.

I am also not convinced spaces between documented functions together are necessary, especially when there are more than 4-5 functions documented together.

See `?gert::git_commit`

In help, it just reduces the amount of information you can see in a single screen

![image](https://github.com/r-lib/roxygen2/assets/52606734/b9b7a3e3-61ab-457c-93e1-a71e784cb747)

It would be good to have usage store 2-3 arguments on the same line whenever possible + reudce space when many functions are documented together

**Comment by hadley** [comment]
Unfortunately I don't think you'll be able to persuade me that this is a good idea 😄 IMO the problem here is documenting too many functions in the same file.
