### ISSUE TITLE
Chaining @inheritParams together

### ISSUE THREAD

**Issue by dougmitarotonda** [r-lib/roxygen2#189]
It was not clear to me in reading the documentation that one could not chain `@inheritParams` together. For example, the following does not work:

```
#' @title Foo
#' 
#' @inheritParams bar
foo <- function(value){ bar(value) } ;

#' @title Bar
#' 
#' @inheritParams baz
bar <- function(value){ baz(value) } ;

#' @title Baz
#' 
#' @param value A scalar
baz <- function(value){ value } ;
```

You get an error of `Error in rep.int(params, reps) : unimplemented type 'NULL' in 'rep2'`.

However, linking everything back to the original function does work, i.e., changing `#' @inheritParams bar` to `#' @inheritParams baz`.

My preference would be to add the functionality to chain the depths. In my real code, there are times where it makes sense to have depths of pass-through. From an architecture perspective, I like the idea of only having to worry about inheriting from the functions that are called inside of the each function, rather than tracking the tree all the way down to the node. 

If adding this functionality is not possible, perhaps we can update the documentation to notify that this is not possible and provide an error message that is a little more obvious.

**Comment by daroczig** [comment]
This seems to work fine now with `roxygen2_4.1.1`. Is it really possible or did I have too much coffee today?
