### ISSUE TITLE
Deprecate @s3method

### ISSUE THREAD

**Issue by hadley** [r-lib/roxygen2#198]
Since it's no longer needed.

**Comment by joshuaulrich** [comment]
Please note that you have removed the functionality, not deprecated it. Please [deprecate](https://en.wikipedia.org/wiki/Deprecation) *before* removing so users aren't forced to change their code to update to the latest package.

**Comment by hadley** [comment]
Yes, I deprecated it over 18 months ago. And now it's gone.

**Comment by joshuaulrich** [comment]
Where is the commit that deprecated it?  I see a commit that removed it, and no releases since then.

**Comment by hadley** [comment]
The commit that is linked above.

**Comment by joshuaulrich** [comment]
Ugh, I'm dense, sorry. I didn't notice that `ns_S3method` is throwing a warning and then still calling `export_s3_method`.  Sorry for the noise.
