### ISSUE TITLE
Cryptic error messages "Skipping invalid path:  .." does not identify the where the problem occurred

### ISSUE THREAD

**Issue by ctbrown** [r-lib/roxygen2#216]
More of a FR than a bug.  

When there are multiple definitions with the same `@alias` tag.  The notification seems to be  "Skipping invalid path:  formula.parts"

This is with roxygen2-4.0.0

**Comment by gerwathome** [comment]
When trying to understand an occurrence of the "Skipping invalid path" error message, I found this discussion on [bioc-devel](https://stat.ethz.ch/pipermail/bioc-devel/2014-October/006496.html).  In this case (and also my case) it wasn't really an error, but just a rather cryptic message about a function starting with a period and also having some roxygen style documentation.  Here a less cryptic message might have been something like "Skipping documentation for un-exported function".
