### ISSUE TITLE
Support 'proto' package syntax

### ISSUE THREAD

**Issue by cbielow** [r-lib/roxygen2#259]
When using the proto package, roxygen stumbles upon

```
require(proto)

someClass <- proto()

#' Some doc
#'
#' @export
#'
someClass$new = function(.) {
  # C'tor  
  proto(.)
}
```

resulting in 

```
Error: Failure in roxygen block beginning proto.R:11
Missing name
```

If I omit the roxygen doc entriely, I can at least avoid the error. But I'd like to document the function.
Could you fix the parser (or for short-term solution) is there a way to work around this?

```
> sessionInfo()
R version 3.1.0 (2014-04-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] proto_0.3-10 Rcpp_0.11.2 

loaded via a namespace (and not attached):
 [1] devtools_1.5   digest_0.6.4   evaluate_0.5.5 formatR_0.10   httr_0.3       knitr_1.6      memoise_0.2.1  parallel_3.1.0 RCurl_1.95-4.1
[10] roxygen2_4.0.1 stringr_0.6.2  tools_3.1.0    whisker_0.3-2 
```

**Comment by klmr** [comment]
The workaround via `@name` notwithstanding would it be possible to reopen this issue and to implement this in Roxygen (I’d provide a pull request were I more familiar with the Roxygen codebase)? Amongst other things, the workaround requires manually specifying the `@usage`, which is also missing.

Furthermore, the problem isn’t restricted to Proto, it’s a general problem for code that does not follow the simple pattern `name = function (…) …`, and there are some interesting use-cases for this:

1. I’m using the Python-like syntax

    ```r
    decorator %@%
    name = function (…) …
    ```

    To imbue functions with extra functionality (see [[1]]); the classical real-world example would be for memoisation:

    ```r
    cache %@%
    fib = function (n)
        if (n < 2) 1 else fib(n - 1) + fib(n - 2)
    ```

2. It’s a very likely syntactic candidate for marking exported functions in ‹modules› 1.0 [[2]]:

    ```r
    #' An example function
    export$
    inner_product = function (a, b)
        (a %*% b)[1, 1]
    ```

    At the moment, exports are done implicitly but there’s a good case for the above, as it mirrors the syntax chosen in JavaScript.

[1]: https://github.com/klmr/decorator
[2]: https://github.com/klmr/modules
