### ISSUE TITLE
Add support for single files

### ISSUE THREAD

**Issue by klmr** [r-lib/roxygen2#273]
At the moment roxygen2 seems to only work for packages. However, not all code comes in the form of packages. Even though there’s an overwhelming consensus to use packages even for small analysis projects, it seems unnecessary to push this preference onto the user, since roxygen2 contains all the necessary functionality already, it just needs to expose it in its API.

There are at least two concrete use-cases for this (the second being relevant for me):
- [Single-file one-off Markdown reports](http://stackoverflow.com/q/18923405/1968) generated with [knitr](/yihui/knitr) or Sweave. Even though such reports can generally live without documentation, having it would still help during writing, and would promote writing better code from the start, which could later be put into a package
- [modules](/klmr/modules), a modern alternative to conventional R packages, which organises reusable code units in a fashion similar to Python and [JavaScript](http://nodejs.org/api/modules.html). The feature most sorely lacking from modules at the moment is support for documentation, and it would not make sense to reinvent the wheel, when there’s a perfectly fine tool out there.

**Comment by klmr** [comment]
… and now Roxygen2 breaks ‹modules› because `roxygen:::parse_file` was removed. 👎

**Comment by misterhenson** [comment]
In fact this is highly useful, if you have to do technical documentation on a project, just saying.

**Comment by klmr** [comment]
@misterhenson If you’re interested in this, see #634, especially the links to code in the comments there, where I’m implementing this.
