### ISSUE TITLE
Automatically merge identical @param calls

### ISSUE THREAD

**Issue by thomasp85** [r-lib/roxygen2#282]
If multiple methods or functions are collected in one Rd file there will probably be some overlap in the parameters. At the moment each @param call will insert a new parameter description resulting in a warning if the same parameter is described twice (or more). This can be circumvented by only putting a @param call in one of the oxygen comments but this counters the strength of oxygen namely that the documentation is right above the code. 

Would it be possible that identical parameters are merged to one during Rd creation?

**Comment by krivit** [comment]
Merging the chunks of text a la `@description` would be very helpful, I think. When documenting a class, each constructor requires a different argument and therefore a different description of the argument, and similarly when documenting methods for a class. In particular, many generics have `x` or `object` as their first argument, and documenting them separately in the same Rd creates multiple entries for the same argument, unless one does as suggested and documents them all in one place, which is suboptimal.
