### ISSUE TITLE
Documentation for R6 methods

### ISSUE THREAD

**Issue by hadley** [r-lib/roxygen2#388]
Should look something like this:

---
# Methods
## Method 1

```
class$method(a, b, c = 12)
```

Description.
### Parameters
- Param 1
- Param 2
- Param 3
### Returns

What the method returns
### Example

``` R
a <- 10
b <- 5
a + b
#> [1]
```

---

Rd would look something like:

``` latex
\section{Methods}{
\subsection{\code{method1}}{

\code{class$method1(a, b, c = 12}

\subsection{Parameter}{

}
}
```

and similarly for fields. 

Parameters, returns, and methods would be optional. If no methods use them, just list usage + (optional) description with bullets.  Can also use top-level `@examples` if you want to put all examples in one place.

**Comment by hadley** [comment]
It's going to be a lot of work to fix this, and it's an incredibly special case, so I'm closing because realistically this will never get to the top of my todo list.

**Comment by krlmlr** [comment]
How about also parsing roxygen comments *inside* the objects that are documented? They seem to be available in the [`parsed` list](https://github.com/klutometis/roxygen/blob/1b8ea387dacc22d023a108a219f6614e76469df6/R/parse.R#L24). Would be useful also for DBItest.

**Comment by krlmlr** [comment]
Why not one `.Rd` file per method? The list of methods could be autogenerated, with links to detailed methods documentation if available.

```
\section{Public methods}{
  \itemize{
    \item{\code{initialize(a, b, c = 2)}
    \item{\code{\link[=Class$method1]{method1}(d, e)}: Title of method documentation
  }
}
```

**Comment by hadley** [comment]
I don't think you want want file per method, because with this style of OO you tend to have lots and lots of little methods. Most docs for js, ruby, python, and java document all methods on a single page.

**Comment by Enchufa2** [comment]
Hi! If I may make a couple of suggestions, it would be great something like this (I don't know if I'm defining too many subsections):

# Class
## Description
blablabla
## Inherits
BaseClassLink
## Usage
Class$new(param1, ...)
## Arguments
* param1
* ...

## Public attributes
* attr1
* ...

## Public methods
your structure here
## Active bindings
### ActiveBinding1
```R
class$activebinding1
class$activebinding1 <- value
```
Description.
#### Parameters
* value

etc. (same structure as methods)

## Details
details

## References
refs

## See also
blablabla

## Examples
General examples

**Comment by levithatcher** [comment]
Sorry to bug, but is there anyone actively working on this? I love roxygen2 and R6 and would very much love and appreciate built-in documentation for my methods (and not just their class). Overall, thanks for the wonderful work you've already done!

**Comment by hhoeflin** [comment]
The docstrings from #465 allow also for \code, but you need to escape the \, so use a \\code. I agree this is a little annoying. I used it as it is similar to how Reference classes are implemented, and expanded from there. An alternative would be to have an R-comment right after the top of the function. When sourcing the code for processing, the comments could be extracted.

**Comment by epicfarmer** [comment]
@hhoeflin Right, that makes sense.  I would say that a #' comment right after the start of the function would be better if possible.

I've edited the above to also document inherited methods recursively if they are not overwritten.  I'm not sure exactly how to go about submitting a pull request.  Should I do it directly here, or as a modification of @hhoeflin 's repository first?

Additionally, it seems that this code meets all of the ideas above except:

- Documenting class$method rather than just method.
- Documenting the inheriting class with a link.
- Separating Methods from Active Bindings.

@hadley Do you think the documentation specified above is adequate, or are you hoping for more discussion about how R6 classes should be documented?

**Comment by hadley** [comment]
@epicfarmer what is "this code" that you are talking about? 

Before you implement a pull request, I think you need to write up an overall design document that describes how documenting R6/RC classes would work, fleshing out the sketches described above.

**Comment by hhoeflin** [comment]
@epicfarmer Yes - it doesn't separate active methods from regular ones - but it does label active methods as such. There is certainly quite a few things to be improved from my original implementation. I intended it as a first start towards a discussion.

**Comment by epicfarmer** [comment]
@hadley: Sorry, by I edited the code from pull request in #465 .  Do you have an example design document from a previous addition?

@hhoeflin:  That makes sense.

Starting with methods as using the same documentation as functions makes sense.  However, I think it might be good to additionally have optional fields @references and @mutates to document members of the class which are used and modified respectively.

**Comment by hadley** [comment]
I don't — but I'd recommend using google docs so that it's easier to comment/collaborate.

**Comment by epicfarmer** [comment]
https://drive.google.com/open?id=0BzaZpCcBss4Jd2twbDhNTUdMczA

Is something like this what you had in mind?

**Comment by hhoeflin** [comment]
@epicfarmer 

Thanks for putting up the design document. Regarding the suggestion of a "mutate" keyword, could you describe its use more closely? Usually for me, accessor methods are defined in OOP in order to abstract away the internal structure of an object. To me, documenting how an accessor method changes internal fields (especially private ones as in your example) seems to be counter to that approach of hiding the internal implementation from the user.

**Comment by epicfarmer** [comment]
@hhoeflin 

So, the example was written quickly, and so might not be adequate.  I think that you're right in that documenting the internals of the class is not really what we want to do.

The original idea behind the mutate keyword, was that we needed a separate field from `@param` and `@return` to correspond to members of the object.  `@reference` and `@mutate` are places in the object where input and output go respectively.  I think that if a method modifies a public field or active binding, then that should be documented:  So for example:
```{r}
  private = list(
     #' Hidden inner workings
    .a = 0
  ),
  public = list(
    incrementA = function(){
      #' Function which modifies hidden inner workings
      #' @reference a (Not sure if this should be here or not...)
      #' @mutate a Increases a by 1
      self$a = self$a+1
    }
  ),
  active = list(
    a = function(value){
      #' public interface to hidden workings
      if(missing(value)){
        return private$a;
    },
   private$.a = value
)
```

**Comment by hhoeflin** [comment]
@epicfarmer 

Thanks - yes certainly makes sense to document changes to public fields.

**Comment by hadley** [comment]
I think that is out-of-scope for now. It would be better to get something minimal working before adding rarely needed features.

**Comment by epicfarmer** [comment]
@hadley Getting something minimal working should definitely come first.  If you get a chance, could you glance at the document and make sure its what you had in mind.

@hhoeflin Since you already made most of the changes to the code, could you modify the document to include an overview of how you did what you already did?  I'm not familiar enough with the structure of roxygen to do it.

I've added all the roxygen keywords that seem remotely relevant.  I think most of them are out of scope for right now, but I've marked a few that aren't.

**Comment by hadley** [comment]
It would be easier to read/comment if it was a properly styled shared google document, not an Rmd uploaded to google drive.

**Comment by epicfarmer** [comment]
I forgot that the markdown interface isn't normally part of google documents.

[https://docs.google.com/document/d/1y8jNDX6tcdWXP4yXNHvwtygYrqoZqSMcHkPheh2pMGY/edit?usp=sharing](url)

I'll remove the other one then, so there isn't any confusion.

**Comment by epicfarmer** [comment]
As far as documenting methods, perhaps something like this for the Rd:

https://docs.google.com/document/d/1axFKclZ5Zf5eX2hnLpLZA0sQh7OACMmmXpP2YT7KJo0/edit?usp=sharing

To clarify, for R6Class documentation to be implemented which of the following (or perhaps other things) are needed:

how to go from commented R code to Rd documents
designing the desired Rd documents (this is what the google doc addresses)
Dealing with R6 specific structures (inheritance, active bindings, private methods/members)

**Comment by hadley** [comment]
I was thinking more like:

```latex
\itemize{\code(method1(arg1, arg2, ...))}{
  Descriptive stuff and such
  \methodtable{Arguments}{
    \methoditem{arg1}{...}
    \methoditem{arg2}{...}
    \methoditem{\dots}{...}
  }
  
  \bold{Return value}: something returned
}
```

**Comment by jkamins7** [comment]
The reason I was thinking of allowing more than one return was so that people could document behaviour where methods store results as members of the class.  For example:

```
R6Class(
    public = list(
        member1 = 1,
        member2 = 2,
        method = function(x,y){
            #' @return self$member1 ...
            #' @return self$member2 ...
            self$member1 = x
            self$member2 = y
        }
    )
)
```

With R6 classes, its important to be able to document this sort of behaviour somehow, because its important for users to know where the results are stored in the event that they aren't returned.  It would make sense to give it its own section, or to put it with returns, but I think not documenting it at all would be a mistake.

**Comment by hadley** [comment]
Abusing return to document in-place mutation seems like a bad idea to me.

**Comment by epicfarmer** [comment]
Agreed.  I would ideally like another section structured like params for it
and a different keyword, perhaps `@mutate`.  You said it was out of scope
for now, so I will let it go.

With this in mind, the changes you made are reasonable.  What's the next
step?

**Comment by hadley** [comment]
I think the next step is to document a couple of real R6 classes by hand, and see how it looks.

**Comment by epicfarmer** [comment]
So, I have a couple of hand documented R6 classes.  What is the best way to share them?

**Comment by hadley** [comment]
A gist + screenshot of rendered html?

**Comment by epicfarmer** [comment]
The gist is that:
Its hard to tell different methods apart at a glance.  Also, too many methods clogs up the screen quickly (its even worse in Rstudio).  This is with subsection, but the itemize version makes it even harder to tell methods apart easily.  It might be better to change the Arguments and Return Value pieces to italics instead of bold?

![generic](https://cloud.githubusercontent.com/assets/1825051/23974373/56ae9364-09b1-11e7-8fe2-50f117506d8b.png)
![matrixmetadata1](https://cloud.githubusercontent.com/assets/1825051/23974388/62c784d0-09b1-11e7-9736-ad7a9194a705.png)
![matrixmetadata2](https://cloud.githubusercontent.com/assets/1825051/23974389/62c9dffa-09b1-11e7-9995-d8a5d51b87b4.png)
![metadatacontainer](https://cloud.githubusercontent.com/assets/1825051/23974390/62cc9b32-09b1-11e7-9207-e1bc664a2114.png)

**Comment by epicfarmer** [comment]
I've made some changes to the document

https://docs.google.com/document/d/1axFKclZ5Zf5eX2hnLpLZA0sQh7OACMmmXpP2YT7KJo0/edit?usp=sharing

I wanted to avoid using horizontal spacing, but I think its unavoidable.  It seems much easier to read the output this way.

![generic](https://cloud.githubusercontent.com/assets/1825051/24113731/151421fa-0d74-11e7-8938-4be95899bb37.png)
![matrixmetadata-1](https://cloud.githubusercontent.com/assets/1825051/24113734/15194aae-0d74-11e7-8c9d-4b0e20d65c54.png)
![matrixmetadata-2](https://cloud.githubusercontent.com/assets/1825051/24113733/15151718-0d74-11e7-8bcb-d59f9d9c36d7.png)
![matrixmetadata-3](https://cloud.githubusercontent.com/assets/1825051/24113732/1514a602-0d74-11e7-8e7c-5985f33cf9bb.png)

Does this seem ok to you?

**Comment by hadley** [comment]
I think using non-semantic markup in that way is a bad idea. It would be better to keep thinking how we can using existing markup without too many additional hacks.

**Comment by epicfarmer** [comment]
By non-semantic markup, are you referring to the switch from subsection to bold with carriage returns, or the use of verb for a tab, or both?

**Comment by hadley** [comment]
Both

**Comment by epicfarmer** [comment]
In that case, I think the original is the way to go with \bold change to
\emph.  Its not visually appealing, but I think its the best we're going to
get in terms of obeying Rd standards.  Unless you know of some
non-sectioning keywords that I don't know about?

**Comment by jkamins7** [comment]
I've updated the document:  https://docs.google.com/document/d/1axFKclZ5Zf5eX2hnLpLZA0sQh7OACMmmXpP2YT7KJo0/edit?usp=sharing

This acheives a similar effect to the previous pictures, but is less of a hack. @hadley , are there any other parts that feel hacked, which I should try to remove?

**Comment by manumart** [comment]
Hi everybody,
as others, I love using R6 classes but am wondering how I should/could get them documented (especially methods). Are there any guidelines around so far about how this is to be done?

Cheers,              Manuel

**Comment by hadley** [comment]
More detailed sketch with @wch:

```

\section{Methods and fields}{

\subsection{Whatever you want}{

Some text here. Followed by list of methods.

\describe{
  \item{\code{$get(key)}}{Gets a single value}

  \item{\code{$set(key, value)}}{

  Gets a single value

  \tabular{ll}{
  \code{key} \tab name of key \cr
  \code{value} \tab new value \cr
  }
  }

  \item{\code{$set(key, value)}}{

  Gets a single value

  \itemize{
  \item \code{key}: name of key
  \item \code{value}: new value
  }
  }

  \item{\code{$set(key, value)}}{

  Gets a single value

  \describe{
  \item{\code{key}}{name of key}
  \item{\code{value}}{new value. This is a long sentence which is going to
    span multiple lines.This is a long sentence which is going to
    span multiple lines.}
  }
  }

  \item{\code{$set(key, value)}}{

  Gets a single value

  — \code{key}: name of key

  — \code{value}: new value. This is a long sentence which is going to
    span multiple lines.This is a long sentence which is going to
    span multiple lines.
  }

  \item{\code{$set(key, value)}}{

  Gets a single value

  \code{key} — name of key

  \code{value} — new value. This is a long sentence which is going to
    span multiple lines. This is a long sentence which is going to
    span multiple lines.

  Returns: self, invisibly.

  }



}
}
}
```

**Comment by hhoeflin** [comment]
Is there a way to also cover the $set method? I make very heavy use of it to emulate multiple inheritance. So far i have used a method similar to the one implemented for rcclasses using strings and this also works with "set" (see https://github.com/hhoeflin/roxygen). 

For an example where it is used, see https://github.com/hhoeflin/hdf5r

One option maybe to also support strings at the beginning of the function instead of or in addition to the comments before the function definition?

**Comment by jkamins7** [comment]
@hadley I'm a bit confused by your example in the first part.  It seems like you documented the two methods in a few different ways.  Are you asking for feedback?  (If you are, I think i prefer the nested `\describe` )

As far as the scoping goes, this seems like a fine place to start.  Do you still need more complete examples before moving on?  Also, in general, how can I help move this forward?

**Comment by hadley** [comment]
I'm not asking for feedback, I'm just dumping my notes. Unfortunately I don't think there's any way for someone else to push this forward - I want to have a solid mental model of the problem before implementing anything.

**Comment by jeffwong-nflx** [comment]
Bumping this thread. As an outsider I would love to see resolution on this topic; it has lots of value to the community

**Comment by jkamins7** [comment]
As an update, the package I was originally wanting this for is released on cran as ForecastFramework.  I have a workaround for documentation that uses roxygen-like syntax, and parses to Rd.  I would like to be able to convert that to roxygen if/when this is implemented. It would be helpful if you could keep us updated on your thoughts about which tags will mean what, even if they are currently not implemented.  I've been using [this post](https://github.com/klutometis/roxygen/issues/388#issuecomment-333396112) as a guide more or less.

**Comment by gaborcsardi** [comment]
Hi all, I opened a PR for R6 support: #922. It is a draft, and some things are still coming, but if you give it a try, then feedback is appreciated. Thanks!

**Comment by universe77** [comment]
Hi all,
I use R6 class for my package and have a few functions which were added by using $set method. I wonder if there is any updates on the documentation for the $set method? It would be much appreciated if you could help me find a solution for this. 
Looking forward to hearing from you. Thanks!

**Comment by gaborcsardi** [comment]
See https://github.com/r-lib/roxygen2/issues/931.

**Comment by kainhofer** [comment]
Thanks for implementing R6 support in roxygen2. Works quite well, except for one feature I have not yet been able to do: How do I link to one particular methods of an R6 class? 

```r
#' Test R6 class
#' @export
TestR6 = R6Class(
    "TestR6",
    public = list(
        #' @description Example method
        myMethodA = function() {1:10}
    )
);

#' Test function
#' 
#' This function is a wrapper for [TestR6$myMethodA()] or [TestR6#method-myMethodA]
#' or [TestR6#method-myMethodA()], but neither of these links work....
#' @export
myMethodB = function(r) { r$myMethodA() }
```

Neither of the links in the documentation of `myMethodB` appear to correctly link to the TestR6$myMethodA() method, just to the general TestR6 class.... For classes with potentially dozens of methods, this is not very user-friendly.

What is the correct way to link to one particular method?

**Comment by hongyuanjia** [comment]
Hi @kainhofer, I have the same question before. Please see https://github.com/r-lib/roxygen2/issues/955. Basically, it is only possible in HTML output.

**Comment by gaborcsardi** [comment]
@kainhofer Can you please open a separate issue? We'll be working on R6 again soon, and since I have seen R-core and packages relying on the structure of the help files, we can consider adding proper support for in-page links.
