### ISSUE TITLE
Dynamic registration of S3 methods

### ISSUE THREAD

**Issue by lionel-** [r-lib/roxygen2#623]
cf discussion in https://github.com/hadley/dtplyr/pull/42

**Comment by hadley** [comment]
We should at least provide:

```R
register_s3_method <- function(pkg, generic, class, fun = NULL) {
  stopifnot(is.character(pkg), length(pkg) == 1)
  envir <- asNamespace(pkg)

  stopifnot(is.character(generic), length(generic) == 1)
  stopifnot(is.character(class), length(class) == 1)
  if (is.null(fun)) {
    fun <- get(paste0(generic, ".", class), envir = parent.frame())
  }
  stopifnot(is.function(fun))


  if (pkg %in% loadedNamespaces()) {
    registerS3method(generic, class, fun, envir = envir)
  }

  # Always register hook in case package is later unloaded & reloaded
  setHook(
    packageEvent(pkg, "onLoad"),
    function(...) {
      registerS3method(generic, class, fun, envir = envir)
    }
  )
}
```

If we wanted to make a roxygen tag, it could generate a `utils-s3-dynamic.R` file which would include a `register_s3()` function.  Would probably need to inline `register_s3_method()` (to avoid a run-time dependency on roxygen) and we'd need to figure out how to make sure it's called automatically on load.

**Comment by wch** [comment]
The `register_s3_method` function shouldn't call `asNamespace(pkg)` early on. See hadley/dtplyr#60.

**Comment by krlmlr** [comment]
This might be fixed now in `vctrs::s3_register()` .

**Comment by hadley** [comment]
This function can't live in roxygen2 because it would make a roxygen2 a run-time dependency, and a better version is now available in [vctrs](https://vctrs.r-lib.org/reference/s3_register.html). Generating the new syntax for 3.6 is discussed in #796
