### ISSUE TITLE
Tag for side effects

### ISSUE THREAD

**Issue by hadley** [r-lib/roxygen2#660]
Useful to document side-effects in the same way that we document return values.

Probably call it `@effect` so it has the same number of letters as `@return`

Part of #388 but useful generally.

**Comment by hadley** [comment]
My sense now is that this is not much more useful than `@section Side effects:`.

**Comment by daattali** [comment]
@hadley I came to this repo to make this suggestion. IMO a dedicated tag for side effects would make it more widely used than relying on developers to create a custom section tag. 

Technically many tags *could* get away with using a section tag instead, but by having an explicit tag it means that when someone is ready to write documentation for their function and they type `@`, the autocomplete would show this tag. Without seeing this tag, the vast majority of people wouldn't even think of adding side effect information, but if you see this tag as a possibility you might think to add it. 

I'd like to formally ask you to reconsider :)
