### ISSUE TITLE
If a project defines a collation, but does not contain any include directives generation fails.

### ISSUE THREAD

**Issue by jimhester** [r-lib/roxygen2#692]
This might be by design, however in https://github.com/r-lib/fs I originally had a include directive, then later removed it. This caused my `DESCRIPTION` to have a `Collate:` section, however roxygen could no longer manage it because there were no include directives.

Ideally it would do one of the following in this case.

1. Emit a warning about lack of include directives.
2. Update the collation with the default sorting for the locale.
3. Delete the collation section entirely.

2 and 3 could be problematic for packages that use a manually modified collation I guess, so likely 1 is the only one we could use.

**Comment by hadley** [comment]
I don't see how we can distinguish a manually supplied collation from one that was previously automatically generated, this is a fairly rare failure mode, and roxygen2 has already significant development debt, so I'm going to close this issue.
