### ISSUE TITLE
Add plain "-method" alias to documentation for S4 methods

### ISSUE THREAD

**Issue by krlmlr** [r-lib/roxygen2#702]
Use case: https://github.com/r-dbi/DBI/issues/162

Then, the package that defines a generic can use a `methodName-method` link to point users to all available implementations. Unfortunately, `R CMD check` then warns for the package that defines the generic that the link `methodName-method` points to nowhere. This can be alleviated by a reexports-like "landing page" for all such links.

Example:

- *DBI* defines a `dbConnect()` generic
    - In the documentation for that method, *roxygen2* creates a section "Implementations" that contains a link to `dbConnect-method`
    - A file `methods.Rd` is created, aliased to `dbConnect-method` (to satisfy `R CMD check`); a bullet point mentioning `dbConnect()` is created there, perhaps with relevant links. This file also contains a message like "if you see this page, you may need to load more packages"
- *RSQLite* implements a `dbConnect()` method
    - The help page for that method is aliased to `dbConnect-method`
    - In the documentation, *roxygen2* creates a section "Generic" that contains a link to `dbConnect`

**Comment by hadley** [comment]
This method feels a bit convoluted. Don't we have a better approach now using `\Sexpr`?
