### ISSUE TITLE
Add GitHub links in don't edit

### ISSUE THREAD

**Issue by hadley** [r-lib/roxygen2#706]
Currently:

```
% Generated by roxygen2: do not edit by hand
% Please edit documentation in R/complete.R
```

Could be:

```
% Generated by roxygen2: do not edit by hand
% Please edit documentation in [R/complete.R](https://github.com/klutometis/roxygen/edit/master/R/complete.R)
```

Idea from @jennybc

**Comment by jennybc** [comment]
I also meant that, when viewing the help as a normal user, what if there was an "edit me" link?

Along these lines:

http://happygitwithr.com/repo-browsability.html#let-people-correct-you-on-the-internet

Example of a link that invokes the GitHub workflow for editing a file in the browser:

```
[CLICK HERE to suggest an edit to this page!](https://github.com/jennybc/happy-git-with-r/edit/master/32_workflow-make-github-repo-browsable.Rmd)
```

**Comment by hadley** [comment]
Or do you mean in RStudio?

**Comment by jennybc** [comment]
I guess it comes down to whether one would want this link in "normal" R help. In which case it would be a job for roxygen2. Or if we wanted it only in pkgdown sites, then pkgdown.

It's possible I don't understand you. But I was thinking ... something like a `@editme` tag in roxygen that inserts such a link when producing the Rd.

**Comment by hadley** [comment]
Oh in the literal generated Rd, I wasn't thinking of that, but it makes sense.

**Comment by jennybc** [comment]
It's possible it would attract too many off-base PRs. But it could be good for typo fixes or even adding examples.

**Comment by hadley** [comment]
I now feel that this belongs most naturally in pkgdown.
