### ISSUE TITLE
Implicit dependence on 'stats' and 'methods'

### ISSUE THREAD

**Issue by grayclhn** [r-lib/roxygen2#72]
roxygenize uses the 'setNames' function from stats and 'setPackageName' from methods, but stats and methods are not listed in the package dependencies. They are both loaded anyway when using R interactively, but not when Rscript is used, i.e.:

$ Rscript --default-packages=roxygen2 -e 'roxygenize("simplebreak.source", "simplebreak")'

gives the error:

Error in read.description(DESCRIPTION) :
 could not find function "setNames"
Calls: roxygenize -> read.description
Execution halted

but

$ Rscript --default-packages=roxygen2,stats,methods -e 'roxygenize("simplebreak.source", "simplebreak")'

works fine. This is in R version 2.14.1 beta (r57866).

**Comment by giupo** [comment]
I still have the same issue reported by @grayclhn; I see that in the commit 1ab13d5f9a0d53f12a56a1076a7bda4eaed16b2e (if I'm not wrong or I've missed something...) the dependency on `stats` has been removed although the method `stats::setNames` is still used today

If I add `stats` dependency to my projects, everything goes right. Shouldn't `roxygen2` declare a dependency on `stats`?
