### ISSUE TITLE
Better output for "reexports" help page

### ISSUE THREAD

**Issue by krlmlr** [r-lib/roxygen2#765]
Example from dplyr:

```
magrittr

> %>%

tibble

> data_frame, data_frame_, as_data_frame, lst, lst_, add_row, type_sum, glimpse, frame_data, tribble, tibble, as_tibble, trunc_mat, tbl_sum

tidyselect

> contains, ends_with, everything, matches, num_range, one_of, starts_with
```

I assumed alphabetic order and clicked on "tibble" when I wanted to click "tribble". Perhaps we could turn this into a bullet list, ordered alphabetically and grouped by help page?

```
magrittr

    - %>%

tibble

    - add_row
    - as_tibble, as_data_frame
    - data_frame, data_frame_, lst, lst_, tibble
    - tbl_sum
    - tribble, frame_data
    - trunc_mat
    - type_sum, glimpse, 

tidyselect

    - contains, ends_with, everything, matches, num_range, one_of, starts_with
```

CC @TSchiefer.

**Comment by hadley** [comment]
I looked into this a bit — it's not too hard to do, but it's a bit fiddly and requires looking up the alias, and I don't think it's particularly important. So I'm going to settle for just ordering alphabetically.
