### ISSUE TITLE
indent not preserved within Markdown code chunks in some cases

### ISSUE THREAD

**Issue by kevinushey** [r-lib/roxygen2#789]
Reprex:

```R
code <- "
#' Function
#'
#' Description.
#'
#' ```R
#' foo <- function(...) {
#' 
#'   code
#'     
#' }
#' ```
#' 
#' @export
foo <- function() {}
"

parsed <- roxygen2:::parse_text(code, global_options = list(markdown = TRUE))
writeLines(parsed[[1]]$details)
```

Output:

```
> writeLines(parsed[[1]]$details)
\preformatted{foo <- function(...) {

code
    
}
}
```

Note that the indent prior to `code` is lost.

The issue goes away if there are no blank lines in the example code, e.g.

`````
#' ```R
#' foo <- function(...) {
#'   code
#' }
#' ```
`````

so it's something specific to empty lines in code chunks.

<details>
> devtools::session_info()
Session info -------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.5.1 (2018-07-02)
 system   x86_64, darwin15.6.0        
 ui       RStudio (1.2.959)           
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       America/Los_Angeles         
 date     2018-09-07                  

Packages -----------------------------------------------------------------------------------------------
 package    * version    date       source                             
 backports    1.1.2      2017-12-13 CRAN (R 3.5.0)                     
 base       * 3.5.1      2018-07-05 local                              
 commonmark   1.5        2018-04-28 CRAN (R 3.5.0)                     
 compiler     3.5.1      2018-07-05 local                              
 datasets   * 3.5.1      2018-07-05 local                              
 devtools   * 1.13.6     2018-06-27 CRAN (R 3.5.0)                     
 digest       0.6.16     2018-08-22 CRAN (R 3.5.1)                     
 evaluate     0.11       2018-07-17 CRAN (R 3.5.1)                     
 graphics   * 3.5.1      2018-07-05 local                              
 grDevices  * 3.5.1      2018-07-05 local                              
 htmltools    0.3.6      2017-04-28 CRAN (R 3.5.0)                     
 httpuv       1.4.5      2018-07-19 CRAN (R 3.5.1)                     
 knitr      * 1.20.8     2018-07-12 Github (yihui/knitr@89b34a6)       
 later        0.7.4      2018-08-31 CRAN (R 3.5.1)                     
 magrittr     1.5        2014-11-22 CRAN (R 3.5.0)                     
 memoise      1.1.0      2017-04-21 CRAN (R 3.5.0)                     
 methods    * 3.5.1      2018-07-05 local                              
 mime         0.5        2016-07-07 CRAN (R 3.5.0)                     
 packrat      0.4.9-12   2018-08-31 Github (rstudio/packrat@eaf4435)   
 promises     1.0.1      2018-04-13 CRAN (R 3.5.0)                     
 purrr        0.2.5      2018-05-29 CRAN (R 3.5.0)                     
 R6           2.2.2      2017-06-17 CRAN (R 3.5.0)                     
 Rcpp         0.12.18    2018-07-23 CRAN (R 3.5.1)                     
 rlang        0.2.2      2018-08-16 CRAN (R 3.5.0)                     
 rmarkdown  * 1.10       2018-06-11 CRAN (R 3.5.0)                     
 roxygen2   * 6.1.0.9000 2018-09-07 Github (klutometis/roxygen@7032ed1)
 rprojroot    1.3-2      2018-01-03 CRAN (R 3.5.0)                     
 shiny      * 1.1.0      2018-05-17 CRAN (R 3.5.0)                     
 stats      * 3.5.1      2018-07-05 local                              
 stringi      1.2.4      2018-07-20 CRAN (R 3.5.1)                     
 stringr      1.3.1      2018-05-10 CRAN (R 3.5.0)                     
 testthat   * 2.0.0      2017-12-13 CRAN (R 3.5.0)                     
 tools        3.5.1      2018-07-05 local                              
 utils      * 3.5.1      2018-07-05 local                              
 withr        2.1.2      2018-03-15 CRAN (R 3.5.0)                     
 xfun         0.3        2018-07-06 CRAN (R 3.5.0)                     
 xml2         1.2.0      2018-01-24 CRAN (R 3.5.0)                     
 xtable       1.8-3      2018-08-29 CRAN (R 3.5.1)   
</details>

**Comment by gaborcsardi** [comment]
This seems related to roxygen parsing in general, it is not markdown specific. At least this is wrong as well:

```r
code <- "
#' Function
#'
#' Description.
#'
#' \\preformatted{
#' foo <- function(...) {
#'
#'   code
#'     
#' }
#' }
#' 
#' @export
foo <- function() {}
"

parsed <- roxygen2:::parse_text(code, global_options = list(markdown = FALSE))
writeLines(parsed[[1]]$details)
```

```
\preformatted{
foo <- function(...) {

code

}
}
```

Removing the first empty line fixes it here as well.

**Comment by hadley** [comment]
Looks like the problem is in the description block parser — whitespace is preserved if you use `@details`:

```` r
code <- "
#' Function
#'
#' Description.
#'
#' ```R
#' foo <- function(...) {
#' 
#'   code
#'     
#' }
#' ```
foo <- function() {}
"

parsed <- roxygen2:::parse_text(code, global_options = list(markdown = FALSE))
cat(parsed[[1]]$details)
#> ```R
#> foo <- function(...) {
#> 
#> code
#>     
#> }
#> ```

code <- "
#' Function
#'
#' @details
#' ```R
#' foo <- function(...) {
#' 
#'   code
#'     
#' }
#' ```
foo <- function() {}
"

parsed <- roxygen2:::parse_text(code, global_options = list(markdown = FALSE))
cat(parsed[[1]]$details)
#> ```R
#> foo <- function(...) {
#> 
#>   code
#>     
#> }
#> ```
````

<sup>Created on 2019-08-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
