### ISSUE TITLE
devtools::document() Error in .f(.x[[i]], ...) : attempt to apply non-function

### ISSUE THREAD

**Issue by pwildenhain** [r-lib/roxygen2#803]
I recently updated from `roxygen2` version 6.0.1 to 6.1.0. I went to document some newly added functions and received the following error message:  
```
> devtools::document()
Updating package documentation
Loading package
Error in .f(.x[[i]], ...) : attempt to apply non-function
```
I'm was using R version 3.4.4 (2018-03-15). I was able to solve the problem by updating my R version to 3.5.1. 

Do you know why the combination of an older version of R with the newest version of `roxygen2` would produce this error?

**Comment by hadley** [comment]
Can you provide a reprex?

**Comment by hadley** [comment]
I've closed this issue due to lack of requested reprex. If you still care about this bug, please open a new issue with a reprex.
