### ISSUE TITLE
@family should return links to `fn()` not `fn`

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/roxygen2#815]
Currently, the family tag returns:

```
Other great functions: fn1, fn2
```

To be in line with [the tidyverse style guide](http://style.tidyverse.org/documentation.html#r-code), it might be useful to return:

```
Other great functions: fn1(), fn2()
```

The change could be made here, I believe:
https://github.com/klutometis/roxygen/blob/be3ef309381923e64337c3324510746990fde62f/R/rd-family.R#L18

Edit) I am not sure if the family tag is ever used to link to things other than functions, but that might be something to consider as a reason not to do this.

**Comment by gaborcsardi** [comment]
Yeah, for the proper solution, we would need to check whether the linked thing is a function or not. Roxygen know it, so it is not hopeless.
