### ISSUE TITLE
New roxygen behavior around author

### ISSUE THREAD

**Issue by leepface** [r-lib/roxygen2#831]
I just noticed that the new release of roxygen2 introduces a new behavior for the handling of author fields. Specifically, it now draws author information from the DESCRIPTION and puts it into Rd files. This is, however, the wrong use of the `\author{}` field.

According to [Writing R Extensions](https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Rd-format), this field refers to the author of the specific documentation file not the package:

> \author{…}
Information about the author(s) of the Rd file. Use \email{} without extra delimiters (such as ‘( )’ or ‘< >’) to specify email addresses, or \url{} or \href{}{} for web pointers.

As such this is incorrect behavior. Can you please revert? Thanks!

**Comment by hadley** [comment]
What do you mean?

**Comment by hadley** [comment]
I can't figure out what you're referring to, unless it's the automatic addition of author information to the package documentation file, which seems fine to me. Happy to look into this if you can provide more details.
