### ISSUE TITLE
LaTeX Text in Default Arguments Is Interpreted

### ISSUE THREAD

**Issue by billdenney** [r-lib/roxygen2#837]
When LaTeX is in the default arguments for a function, the code is interpreted which makes the documentation not match the default formal arguments.

An example is:
https://github.com/billdenney/TopicLongTableR/blob/1338116767d90e8211533cb6e7db5ef30368dc33/R/topic_long_table_header_footer.R#L20

Which yields:
https://github.com/billdenney/TopicLongTableR/blob/1338116767d90e8211533cb6e7db5ef30368dc33/man/topic_long_table_header.Rd#L10

Which gives the following warning with `devtools::check()`:
```
checking for code/documentation mismatches ... WARNING
Codoc mismatches from documentation object 'topic_long_table_header':
topic_long_table_header
  Code: function(x, col_names = NULL, above_col_names = "\\hline",
                 below_col_names = "\\hline",
                 subsequent_page_notification = "\\ldots continued",
                 latex_header = NULL)
  Docs: function(x, col_names = NULL, above_col_names = "\\hline",
                 below_col_names = "\\hline",
                 subsequent_page_notification = "\... continued",
                 latex_header = NULL)
```

I'm not sure, but I think that the solution is to add more protection to the \s when generating the roxygen or perhaps wrapping the arguments in some form of verbatim block (if it's available).

**Comment by hadley** [comment]
Is this specific to `\ldots`?

**Comment by billdenney** [comment]
I don’t know all the code that is translated, but I would guess is is for any translated LaTeX.

**Comment by hadley** [comment]
But hline isn’t affected?

**Comment by billdenney** [comment]
No, hline doesn't appear to be affected.  (I don't know why.)

**Comment by hadley** [comment]
I'm pretty sure it's just `ldots`, and I suspect it might not be roxygen2 at fault. Roxygen2's conversion of `\\ldots` to `\\\\ldots` looks correct to me.

**Comment by hadley** [comment]
roxygen2 doesn't contain "ldots" in the source code, so I think this is an Rd problem.

**Comment by billdenney** [comment]
It is an Rd problem found and described by Georgi Boshnakov (https://stat.ethz.ch/pipermail/r-package-devel/2019q3/004288.html).
