### ISSUE TITLE
Source of a bug in devtools::document?

### ISSUE THREAD

**Issue by ramiromagno** [r-lib/roxygen2#843]
hi

I think this issue: https://github.com/r-lib/devtools/issues/1984 comes from assuming that this subsetting is always possible: https://github.com/klutometis/roxygen/blob/be3ef309381923e64337c3324510746990fde62f/R/object.R#L71

and that is not true for functions whose body is empty, thus explaining that Orwellian issue in `devtools`.

**Comment by hadley** [comment]
Fixed as part of #847
