### ISSUE TITLE
package docs when the package has a function with the same name

### ISSUE THREAD

**Issue by jimhester** [r-lib/roxygen2#861]
Currently the `"_PACKAGE"` package doc generation generates an alias entry with the package name. This causes issues when the package also has documentation with that same name for a function.

In this case ideally roxygen would omit the alias entry.

You can currently work around the issue by using an explicit alias tag with just the `pkgname-package` alias, e.g.

```r
#' @aliases foo-package
"_PACKAGE"
```

**Comment by hadley** [comment]
I can't recall if roxygen has the data needed to do this automatically, but at a minimum it should be documented somewhere.

**Comment by hadley** [comment]
The aliases is added by `object_defaults.package()` which only has a single argument, the object from `object_from_call()`. This means that there's no easy way to do this automatically so we just need to document somewhere.

**Comment by hadley** [comment]
The Packages section in `vignette("rd")` seems like the right place.  It currently claims:

> This also works if there's already a function called `pkgname()`.
