### ISSUE TITLE
Preserve order of @example and @examples

### ISSUE THREAD

**Issue by HenrikBengtsson** [r-lib/roxygen2#868]
I'd like to propose a new tag `@import` that takes a file as input.  It reads the content of that file and injects it as is.

One use case would be to allow for something like (just a toy example):
```r
#' @examples
#' \dontshow{
#' oopts <- options()
#' }
#' @import incl/my_fcn.R
#' \dontshow{
#' options(oops)
#' }
```
The above allows you to keep a standalone, syntax-valid file `incl/my_fcn.R` that can be `source()`:ed while still having additional Rd markup in the `example()` code.

**Comment by gaborcsardi** [comment]
```
#' @example filename
#' @examples
#' code
```
almost does that, `@examples` and the code in `filename` will be put in the `\examples`.

**Comment by HenrikBengtsson** [comment]
Thanks.  I didn't know that this was possible.  However, did you mean that "almost" to be emphasized?  I just tried with:
```r
#' @examples
#' \dontshow{
#' ## BEFORE
#' }
#' @example incl/my_fcn.R
#' @examples
#' \dontshow{
#' ## AFTER
#' }
```
and that ends up putting all the `@examples` code at the top and the `@example` content at the bottom;
```r
\examples{
\dontshow{
## BEFORE
}
\dontshow{
## AFTER
}
y <- my_fcn(42)
y <- my_fcn(3.14)
```

**Comment by gaborcsardi** [comment]
> and that ends up putting all the @examples code at the top and the @example content at the bottom

yes, that's what I meant by _almost_, sorry.

**Comment by HenrikBengtsson** [comment]
No worries. Thxs for confirming.

**Comment by gaborcsardi** [comment]
It is a bit hard to keep the order internally, because roxygen collates all `@examples` block previously, before putting that and the `@example` files together. 

Also, CRAN do not like this, potentially, depending on what you put in the setup and teardown chunks.

**Comment by hadley** [comment]
Looking at `topic_add_examples()`, I don't think it should be too hard to interleave `@example` and `@examples` in the order that they're encountered, rather than in individual blocks.
