### ISSUE TITLE
Missing @inherit leads to uninformative error

### ISSUE THREAD

**Issue by msberends** [r-lib/roxygen2#874]
When I update the documentation of my package, `roxygen2` can't seem to find the tags related to my parameters. The error message is too uninformative to be able to debug this problem:

```
==> devtools::document(roclets = c('rd', 'collate', 'namespace'))

Updating [mypackagename] documentation
Loading [mypackagename]
Error in get_tags(x, "\\arguments")[[1]] : subscript out of bounds
Calls: suppressPackageStartupMessages ... fun -> find_params -> topic_params -> topic_params.Rd
Execution halted

Exited with status 1.
```

The error is *probably* due to a type error in a parameter, but I can't find it and my package has over 50 functions with a total of hundreds of parameters.
The problem arises in the first line of this function:
https://github.com/klutometis/roxygen/blob/f298e96f2ee83fd8d9f71b0fbb9156ef0bf81a66/R/rd-inherit.R#L118-L126

So I guess `x` has length 0, but can't figure out why! :weary:

Might be related to #869, although I checked that there're no empty `@param`s.

```r
packageVersion("devtools")
#> [1] ‘2.0.2’
packageVersion("roxygen2")
#> [1] ‘6.1.1’
```

**Comment by msberends** [comment]
Found it!

This caused the error:
```r
#' @inherit tibble::as.tibble
```
The function `as.tibble()` is no longer exported by package `tibble`. Downside of being dependent on the work of others.

This issue holds though. Would it be possible to create an error like this?

```
Updating [mypackagename] documentation
Loading [mypackagename]
Error in get_tags(x, "\\arguments")[[1]] : function as.tibble is not exported by package tibble
Execution halted
```

**Comment by hadley** [comment]
Can you have a go at creating a reprex as below? My reprex illustrates a problem (too many warnings!) but that seems different to your case:

``` r
library(roxygen2)
out <- roc_proc_text(rd_roclet(), "
  #' Title
  #' @inherit tibble::accumulate
  #'
  #' @export
  foo <- function(x, y) {}"
)
#> Warning: Failed to find topic 'tibble::accumulate'
#> Warning: Failed to find topic 'tibble::accumulate'
#> Warning: Failed to find topic 'tibble::accumulate'
#> Warning: Failed to find topic 'tibble::accumulate'
#> Warning: Failed to find topic 'tibble::accumulate'
#> Warning: Failed to find topic 'tibble::accumulate'
#> Warning: Failed to find topic 'tibble::accumulate'
#> Warning: Failed to find topic 'tibble::accumulate'
```

<sup>Created on 2019-07-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hadley** [comment]
I've closed this issue due to lack of requested reprex. If you still care about this bug, please open a new issue with a reprex.
