### ISSUE TITLE
Fail to extract data from qualified methods::setMethod()

### ISSUE THREAD

**Issue by ramiromagno** [r-lib/roxygen2#880]
Not sure if this can be considered a bug, but here it is for future reference.

![snap](https://user-images.githubusercontent.com/19862384/61547532-7856dc80-aa43-11e9-9169-cf18c353a805.png)

```
==> devtools::document(roclets = c('rd', 'collate', 'namespace'))

Updating rapiens documentation
Writing NAMESPACE
Loading rapiens
Warning: generics-linkage_disequilibrium.R:60: Missing name
Writing get_ld_variants.Rd
Writing NAMESPACE
Documentation completed
```
roxygen2 version: 6.1.1.

**Comment by hadley** [comment]
`find_parser()` needs to handle namespaced function calls
