### ISSUE TITLE
Extending roxygen2 vignette

### ISSUE THREAD

**Issue by hadley** [r-lib/roxygen2#882]
Document how to create your own tag, or your own roclet.

**Comment by mikldk** [comment]
I might be able to give this a try. Or is anybody else working on it now?

**Comment by hadley** [comment]
That’d be great! I’m not aware of anyone else working on it.

**Comment by mikldk** [comment]
Do you have a specific example of a tag/roclet in mind that would make a good example?

**Comment by hadley** [comment]
I don't; my sense would be that it would be best to construct something simple, specifically for teaching.

**Comment by mikldk** [comment]
@hadley I made a suggestion. See [here](https://github.com/mikldk/roxygen2/commit/231018c62a0ea8684e41df2f474095e1cd898484). Not sure what's easiest: to just view my commit or to create a PR? I just didn't think it was worth a PR before you had a look and I heard your thoughts on the examples (probably still a lot of work before a PR is relevant). Let me know what you think; both about the examples and about how it's easiest for you to view it.

**Comment by hadley** [comment]
@mikldk sorry I missed this — that looks like a great start, and I think it's worth turning into a PR. I think it's useful enough to merge with a minimum of work, and then we can continue to build it out over time. Thanks for your help!

**Comment by mikldk** [comment]
@hadley no worries. I have now created the PR. Thanks for all yours!

**Comment by mamueller** [comment]
Thanks a lot for addressing this issue. (I was the person who asked for it).
I found the vignette already helpful.
Thanks
