### ISSUE TITLE
Unable to document certain functions e.g. %!in%

### ISSUE THREAD

**Issue by adam52** [r-lib/roxygen2#890]
I have a very simple function that returns elements of `a` that are not in `b`.

    #' @title a not in b
    #'
    #' @description
    #' Tests whether values in a are not in b. 
    #' @param x value to test
    #' @param y Values that may or may not contain x
    #' @export
    #' @examples
    #' a %!in% b

    '%!in%' <- function(x,y)!('%in%'(x,y))

When I run `install()` R complains that:

    \name should not contain !, | or @

Short of re-defining my function, what can I do about this?

**Comment by hadley** [comment]
Can you please [provide a reprex](https://github.com/r-lib/roxygen2/blob/master/.github/SUPPORT.md#making-a-reprex)?

**Comment by adam52** [comment]
Please see the code above. Thanks.

**Comment by hadley** [comment]
Please create a reprex using `roc_proc_text()`, as described in the link I provided above.

**Comment by adam52** [comment]
@title a not in b

@description
Tests whether values in a are not in b.
@param x value to test
@param y Values that may or may not contain x
@export
@examples
a %\!in% b

``` r
'%!in%' <- function(x,y)!('%in%'(x,y))
```

<sup>Created on 2019-08-14 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hadley** [comment]
Here is a minimal reprex:

``` r
library(roxygen2)
roc_proc_text(rd_roclet(), "
  #' A not in b
  `%!in%` <- function(x, y) x
")[[1]]
#> % Generated by roxygen2: do not edit by hand
#> % Please edit documentation in Rtmpbbfe7x/file71ee6faa7ffb
#> \name{\%!in\%}
#> \alias{\%!in\%}
#> \title{A not in b}
#> \usage{
#> x \%!in\% y
#> }
#> \description{
#> A not in b
#> }
```

<sup>Created on 2019-08-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Note that the `\name{}` field contains  `!`, which is not allowed:

>  To avoid problems with indexing the package manual, it may not contain ‘!’ ‘|’ nor ‘@’, and to avoid possible problems with the HTML help system it should not contain ‘/’ nor a space

I don't see an obvious way for roxygen2 to handle this automatically (since you need to propose your own alternative name), so you'll need to use `@name` yourself:

``` r
library(roxygen2)
roc_proc_text(rd_roclet(), "
  #' A not in b
  #' @name notin
  `%!in%` <- function(x, y) x
")[[1]]
#> % Generated by roxygen2: do not edit by hand
#> % Please edit documentation in RtmpWUGYE0/file7239d4d970a
#> \name{notin}
#> \alias{notin}
#> \alias{\%!in\%}
#> \title{A not in b}
#> \usage{
#> x \%!in\% y
#> }
#> \description{
#> A not in b
#> }
```

<sup>Created on 2019-08-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by adam52** [comment]
Thanks Hadley. Had no idea that there was a `\name{}` attribute!
