### ISSUE TITLE
macro error when using Greek letters in equations

### ISSUE THREAD

**Issue by iembry** [r-lib/roxygen2#893]
Hi, I am using the following equation to document a function in my R package:

`#' \deqn{Re = \frac{\rho RV}{\mu}}`

For that equation, I am getting the following error:

`unknown macro '\rho'`

I am also getting errors for these other 2 Greek letters, but not all Greek characters:

`\deqn{\tau_0 = {\gamma}{RS}}`

`unknown macro '\gamma'`
`unknown macro '\tau'`

What's the best way to use those Greek characters in equations to avoid the error message?

Thank you.

**Comment by hadley** [comment]
Can you please [provide a reprex](https://github.com/r-lib/roxygen2/blob/master/.github/SUPPORT.md#making-a-reprex)?

**Comment by hadley** [comment]
I've closed this issue due to lack of requested reprex. If you still care about this bug, please open a new issue with a reprex.
