### ISSUE TITLE
preserve order with @inheritSection

### ISSUE THREAD

**Issue by the-knife** [r-lib/roxygen2#900]
Sections inherited from other functions are placed after "simple" sections in the rd file, even if they are declared before in the R file :

```
#' @inheritSection foo Foo
#'
#' @section Bar: bar
```

Bar is displayed first in the documentation. Is it an intended behavior? (if yes, is there a workaround to have foo displayed first?)

**Comment by hadley** [comment]
Unfortunately, due to the way that sections are inherited, I think this is basically impossible to implement.

**Comment by olivroy** [comment]
is there a workaround for this?
