### ISSUE TITLE
Roxygen changes DESCRIPTION RoxygenNote

### ISSUE THREAD

**Issue by stefanoborini** [r-lib/roxygen2#905]
Although I am aware this is by design, I might want to voice that this is a considerable annoyance: when I build a package on my local machine, the DESCRIPTION file gets updated with the roxygen version on my local machine. When my collaborator does the same, he modifies the files with his version. When the deployment machine builds the package, it also modifies DESCRIPTION. This leads to constant conflicts or faulty pulls and constant modification of the file for no real reason, and it would become massively inconvenient and error prone if a large group were to work on the package at the same time. 

Roxygen is a documentation extractor and generator. It should have the objective of extracting the documentation and create the .rD files with no other side effect. If the RoxygenNote information is required (I fail to understand why, as the document generation should be idempotent), DESCRIPTION is probably not the best place for it.

**Comment by gaborcsardi** [comment]
> when I build a package on my local machine, the DESCRIPTION file gets updated with the roxygen version

How do you build a package? `R CMD build` does not run roxygen, so building a package should not update `DESCRIPTION`.

**Comment by hadley** [comment]
This was a deliberate decision to force you to resolve the exact situation you describe — if you're collectively developing a package, and you're not using the same version of roxygen2, it's possible that you'll get different Rd output. To make that obvious, and to force you to resolve it, roxygen2 writes its version to disk.

**Comment by stefanoborini** [comment]
@gaborcsardi can at least have an option to disable it?

**Comment by WerthPADOH** [comment]
I know this has been closed, but I'd also like the option to disable it.  I don't often collaborate on packages, and never commit generated manual files for my own packages, so this is just a bother.

**Comment by gaborcsardi** [comment]
> never commit generated manual files for my own packages

So then you probably use a build script on a CI or something similar. You can easily add a line to your script that removes the `RoxygenNote` line from `DESCRIPTION` I suppose.
