### ISSUE TITLE
Simple caching

### ISSUE THREAD

**Issue by lorenzwalthert** [r-lib/roxygen2#912]
When roxygen is used as a [pre-commit hook](https://github.com/lorenzwalthert/pre-commit-hooks), it's relatively slow. Do you think it makes sense implement a simple caching mechanism? One could do it like this: 

- of all files in R / Rd and DESCRIPTION, find the timestamp of the one that was last changed.
- check if the timestamp of that last changed file is different form the one in the cache (`tryCatch()` reading cache).
- if yes, run a full `roxygen2::roxygenize()` and put the timestamp into the cache (replace old).
- if no, return.

This only helps if we run `roxygen2::roxygenize()` twice without chaning any files. This is the typical case with pre-commit, i.e. first roxygenize, then commit (which runs roxygen another time to make sure nothing changes). 

I know this request quite tailored to pre-commit so I understand if you don't want to support it. I cannot implement it in pre-commit-hooks easily because `roxygen2::roxygenize()` is once called interactively and once with my script. Also, I think it's not too complex to implement here (if you already have a temp dir where you store stuff) and benefits arise in other scenarios too.

Related: https://github.com/r-lib/roxygen2/issues/887.

**Comment by gaborcsardi** [comment]
One way to do this without roxygen2 changes, is to write a roclet that updates the cache, and then you can opt in via specifying this roclet in `DESCRIPTION`, to run the caching roclet after the Rd roclet.

**Comment by hadley** [comment]
Unfortunately this feel like it's out of scope for roxygen2, especially since you can implement your approach outside of roxygen2.

**Comment by gaborcsardi** [comment]
@lorenzwalthert yeah, I guess you can use a wrapper to `roxygenize()` to check/create the time stamp, as needed.

**Comment by lorenzwalthert** [comment]
The problem is that the usual workflow is: 

- user changes files in `R/`.
- user manually runs `roxygen2::roxygenize()`.
- user runs `git commit ...`, which triggers [pre-commit script](https://github.com/lorenzwalthert/pre-commit-hooks/blob/master/bin/roxygenize) which calls `roxygen2::roxygenize()`.

Hence, the wrapper approach does not work (because I have only control over the second call) , or it only works if the pre-commit script is run twice, i.e. the user does not manually run `roxygen2::roxygenize()` but attempts to commit right away, knowing that roxygen will be run.

**Comment by gaborcsardi** [comment]
Yeah, you'll have to tell the users to call your wrapper, I am afraid.

**Comment by lorenzwalthert** [comment]
I don't think that's worth it. But maybe I can try to convince the users to not do anything the hooks do, i.e. styling, roxgen, spell check and other things, just leaving it to the hooks.
