### ISSUE TITLE
Add support for rendering tables

### ISSUE THREAD

**Issue by michaelquinn32** [r-lib/roxygen2#920]
jeroen/commonmark has support for converting tables written in markdown.
https://github.com/jeroen/commonmark/blob/180a91b4c5e093241e2b3e8b76b695cd9bc5fad4/R/extensions.R#L8

Writing out the table will require iterating through the generated xml fields, but it should follow similar patterns in markdown.R

Supporting the extension helps documenting data within a package, where the author might show some or all of the data in a table. Another common use case is providing a table of package metadata in a -package.Rd file.
https://github.com/cran/ChannelAttribution/blob/fcdde7fc48863acf79ceb10b220bf8fabad539d7/man/ChannelAttribution-package.Rd#L17

**Comment by gaborcsardi** [comment]
This looks promising: 
```r
❯ xml <- commonmark::markdown_xml(extensions = "table", "| foo | bar |
+ | --- | --- |
+ | baz | bim |")

❯ cat(xml)
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE document SYSTEM "CommonMark.dtd">
<document xmlns="http://commonmark.org/xml/1.0">
  <table>
    <table_header>
      <table_cell>
        <text xml:space="preserve">foo</text>
      </table_cell>
      <table_cell>
        <text xml:space="preserve">bar</text>
      </table_cell>
    </table_header>
    <table_row>
      <table_cell>
        <text xml:space="preserve">baz</text>
      </table_cell>
      <table_cell>
        <text xml:space="preserve">bim</text>
      </table_cell>
    </table_row>
  </table>
</document>
```

The current syntax (https://github.github.com/gfm/#tables-extension-) looks easy enough to transform to `\tabular{}`.
