### ISSUE TITLE
Inherited docs gaining a spurious link

### ISSUE THREAD

**Issue by jennybc** [r-lib/roxygen2#925]
Document bigrquery with dev roxygen2. It inherits lots of docs from DBI and a reference to (base) `data.frame` in DBI is somehow acquiring a link to DBI. I'll make a PR to bigrquery so I can show the exact problem.

**Comment by jennybc** [comment]
See here:

https://github.com/r-dbi/bigrquery/pull/349/files#r331302553

**Comment by hadley** [comment]
`\link{data.frame}` is being translated to `\link[DBI]{data.frame}` — so need to check that the function being linked to aren't in the base packages.

**Comment by gaborcsardi** [comment]
I think one easy workaround, and maybe even good practice, is to link as `[base::data.frame]`.

**Comment by gaborcsardi** [comment]
Btw. not just base packages, Rd picks it up from anywhere AFAIR. That's why it is good to qualify links to other packages.

**Comment by hadley** [comment]
@gaborcsardi this is from my code that attempts to translate local links when you inherit documentation from elsewhere. I now check that the topic exists in the external package, before adding it to the link.

**Comment by gaborcsardi** [comment]
@hadley Right, makes sense.
