### ISSUE TITLE
How to disable pkgload

### ISSUE THREAD

**Issue by jeroen** [r-lib/roxygen2#927]
Unfortunately, pkgload does not work for packages that require initialization of an external library. For example it consistently crashes with the V8 package.

To reproduce you need libv8:

```sh
brew install v8
```

And then you see this: https://youtu.be/vL-kXDEaC4A

It crashes quite frequently for me with c/c++ packages, but V8 is the most reproducible.

**Comment by hadley** [comment]
https://github.com/r-lib/roxygen2/blob/master/NEWS.md#code-loading 😉

**Comment by jeroen** [comment]
Thanks!

**Comment by jeroen** [comment]
Btw, an option to globally opt-out of all pkgload everywhere is very high on my wish list :)

**Comment by hadley** [comment]
Is it possible to fix the underlying problem in pkgload?

**Comment by jeroen** [comment]
I don't know exactly how pkgload works and what it does wrong. In general, unloading and reloading of symbols from dll's is very tricky and OS specific, I think it is very hard to do this reliably.

Maybe pkgload should only be used for packages without compiled code, or perhaps packages with compiled code but without a `Makevars` so that it only uses the default compiler and linker flags.
