### ISSUE TITLE
Exporting S3 methods with hyphens

### ISSUE THREAD

**Issue by Bisaloo** [r-lib/roxygen2#930]
In pavo, we're defining a S3 method for `magick-image` class objects:

```r
`as.rimg.magick-image` <- function() { }
```

Until now, it was exported fine and roxygen generated the following line in `NAMESPACE`:

> S3method(as.rimg,"magick-image")

But with roxygen dev version, it now prints:

> S3method(as.rimg,magick-image)

which obviously causes issues (NOTE and WARNINGs). Please let me know if you'd like me to paste them here.

I'm open to a change on our side but I'm not sure how we could fix this.

cc @jeroen since this seems quite specific to magick.

**Comment by hadley** [comment]
Oh hmmm, I need to rethink my strategy for this. If you need to, you can work around with `@exportS3Method as.rmg "magick-image", but this is a roxygen2 bug.
