### ISSUE TITLE
Request: Option to disable full list of R6 methods of superclass

### ISSUE THREAD

**Issue by coolbutuseless** [r-lib/roxygen2#932]
I've just converted [minihtml](https://github.com/coolbutuseless/minihtml) over to latest roxygen2 from github to test out the R6 support and it's working pretty well.
 
In my particular case, displaying the full list of inherited methods (over 100 methods) is a bit too much, and all the "noise" detracts from this particular class's documentation.   Would it be possible/feasible to just have a single link to the superclass documentation instead of the exhaustive list of all methods?

Extreme Example: Here is a link to the online docs for `minihtml::HTMLDocument`, where the ~100 methods on the superclass really obscure the documentation of this class: 
https://coolbutuseless.github.io/package/minihtml/reference/HTMLDocument.html

---
Sidenote: Whether or not it's a good idea to generate a method for each of the ~100 HTML tags for `HTMLElement` class is a different conversation :)

**Comment by gaborcsardi** [comment]
Well, there is a single link in the 'Super class' section. The methods of the superclass are only added in HTML, not in PDF and text. How about we put them in a `<details>` tag if there are too many of them?

**Comment by coolbutuseless** [comment]
Putting them in a `<details>` tag would work for me.

**Comment by gaborcsardi** [comment]
Also, the links do not work in pkgdown, so I guess we should teach pkgdown to handle them?

**Comment by gaborcsardi** [comment]
@coolbutuseless shall we always put them in `<details>`? Or only if there are more then (say) 10 of them?

**Comment by coolbutuseless** [comment]
I would say "always use `<details>`" - but I realise I'm a sample size of 1 with a freakishly large inheritance list. Other packages might want them all displayed by default?

**Comment by gaborcsardi** [comment]
Yeah, it seems to me that when I am looking at a class, it is useful to get a sense of all available methods, inherited or not. Often the fact that a method is inherited is more of an implementation detail. The current list also smartly omits overridden methods, etc. 

I think what I'll start with is a `<details>` tag that is open by default if you have less than 5 methods in the list? We'll see what other people think.
