### ISSUE TITLE
Non-syntactic function names escaped incorrectly in usage

### ISSUE THREAD

**Issue by NikKrieger** [r-lib/roxygen2#940]
In my package "projects" I make the function `%in%` generic. There is a method called `%in%.projects_author` that I have `@export`ed. The resulting .Rd file is unable to be parsed:

```
Warning in parse_Rd("/home/kriegen/Projects/projects/man/projects_author.Rd", : newline within quoted string at projects_author.Rd:32 Error in parse_Rd("/home/kriegen/Projects/projects/man/projects_author.Rd", : Unexpected end of input (in " quoted string opened at projects_author.Rd:130:51) Execution halted
```

I believe it's because roxygen writes the line:
```
"%in%.projects_stage"(x, table)
```

Instead of the line:

```
"\%in\%.projects_stage"(x, table)
```

**Comment by hadley** [comment]
Could you please provide a reprex as outlined at https://github.com/r-lib/roxygen2/blob/master/.github/SUPPORT.md#making-a-reprex

**Comment by NikKrieger** [comment]
Create a new package, roxygenize the code below, and attempt to preview the resulting .Rd file.

```
#' @export
methods::setGeneric('%in%')

#' A class
#'
#' @param x x
#' @param table table
#'
#' @rdname foo_bar
#' @export
methods::setClass("foo_bar")

#' @rdname foo_bar
#' @export
`%in%.foo_bar` <- function(x, table) {}

#' @rdname foo_bar
#' @export
methods::setMethod(
  '%in%',
  methods::signature(x = 'foo_bar'),
  `%in%.foo_bar`
)
```

**Comment by gaborcsardi** [comment]
``` r
out <- roxygen2::roc_proc_text(roxygen2::rd_roclet(), "
#' A class
#'
#' @rdname foo_bar
#' @export
methods::setClass(\"foo_bar\")

#' @rdname foo_bar
#' @export
`%in%.foo_bar` <- function(x, table) {}

#' @rdname foo_bar
#' @export
methods::setMethod(
  '%in%',
  methods::signature(x = 'foo_bar'),
  `%in%.foo_bar`
)
")
#> Creating a generic function for '%in%' from package 'base' in package 'roxygen_devtest'
cat(out[[1]]$get_rd("usage"))
#> \usage{
#> "%in%.foo_bar"(x, table)
#> 
#> \S4method{\%in\%}{foo_bar}(x, table)
#> }
```

<sup>Created on 2019-10-08 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hadley** [comment]
The chief problem is that `%in%` isn't a generic when `%in%.foo_bar` is documented. If you make it a generic first, you should hit a tested path that correctly escapes the `%`.

But it looks like there's a regression in the case of a function that contains `%` but is not an infix function:

``` r
library(roxygen2)

roc_proc_text(rd_roclet(), "
#' Title
`%foo%bar` <- function(x, table) {}
")[[1]]
#> % Generated by roxygen2: do not edit by hand
#> % Please edit documentation in ./<text>
#> \name{\%foo\%bar}
#> \alias{\%foo\%bar}
#> \title{Title}
#> \usage{
#> "%foo%bar"(x, table)
#> }
#> \description{
#> Title
#> }
```

In the CRAN version I see the correct `"\%foo\%bar"(x, table)`

**Comment by NikKrieger** [comment]
Yes, the CRAN version works, but the improvements contained in the development version are necessary for me for other reasons.

In the non-`reprex` reprex that I posted, I did indeed make `%in%` a generic before `%in%.foo_bar` was documented. @gaborcsardi excluded that line from his `reprex` reprex, though I thank him nonetheless for implicitly teaching me what `roxygen2::roc_proc_text()` does. 

So here's an updated `reprex` reprex that makes `%in%` a generic before `%in%.foo_bar` is documented. Still doesn't work right.

``` r
out <- roxygen2::roc_proc_text(roxygen2::rd_roclet(), "
#' @export
methods::setGeneric(\"%in%\")

#' A class
#'
#' @rdname foo_bar
#' @export
methods::setClass(\"foo_bar\")

#' @rdname foo_bar
#' @export
`%in%.foo_bar` <- function(x, table) {}

#' @rdname foo_bar
#' @export
methods::setMethod(
  '%in%',
  methods::signature(x = 'foo_bar'),
  `%in%.foo_bar`
)
")
cat(out[[1]]$get_rd("usage"))
#> \usage{
#> "%in%.foo_bar"(x, table)
#> 
#> \S4method{\%in\%}{foo_bar}(x, table)
#> }
```

<sup>Created on 2019-10-09 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
