### ISSUE TITLE
Clarifying extending roxygen vignette "a new roclet ... does anything you like"

### ISSUE THREAD

**Issue by nteetor** [r-lib/roxygen2#941]
The portion in question from the extending roxygen vignette, 

https://github.com/r-lib/roxygen2/blob/2cc946ede93e954c06e4f21b821cdced22076317/vignettes/extending.Rmd#L19-L23

I was looking to create a `@demo` tag. The tag would function like a code block, but would also include the output of the block. The demo tag is part of its parent section, so it doesn't make sense to create a top-level section. If I understand correctly, this means I do not implement a `roxy_tag_rd.roxy_tag_demo` method. 

I believe that leaves creating a roclet. However, the example memo roclet from the vignette only touches on a side-effect feature. The example `roclet_process_roclet_memo()` method creates a separate list of items handled by the corresponding `roclet_output` method. Could we instead implement a `roclet_process` method which updates blocks or tags? I feel like such behaviour might belong in the pre-process step. However, in the case of `@demo`, I need the package environment loaded to evaluate the demo's code. Once I can generate the demo output all I hope to do is add an `\out{}` section after the demo's code block. 

Is creation of such a `@demo` tag possible? If one can create such a tag I would also like to update the extending vignette. At the very least revise the line about roclets doing anything.

**Comment by gaborcsardi** [comment]
I _think_ you can do this without a new roclet. Your `roxy_tag_parse()` method will just call `tag_examples()` and your `roxy_tag_rd()` method will put the output into `\details{}`, always: `rd_section("details", ...)`.

Tags cannot be nested currently, so I don't see an easy way to put the demo wherever it appears, i.e. in details, or a section, etc.

**Comment by gaborcsardi** [comment]
Btw. you might be interested in the new `includeRmd()` tag, which is similar to `@demo`, in that it includes both the input and the output in the docs. It needs an external `.Rmd` file, though, with the benefit that you can use knitr caching, simply with `cache=TRUE` in the `.Rmd.

**Comment by nteetor** [comment]
Okay, I will try out the `rd_section("details", ...)` and the `@includeRmd` approaches. Thank you.
