### ISSUE TITLE
Unknown Roxygen options wrap.

### ISSUE THREAD

**Issue by tbates** [r-lib/roxygen2#947]
```R
devtools::document(pkg = "~/bin/umx")
Writing NAMESPACE
Loading umx
For an overview type '?umx'
Writing NAMESPACE
Warning messages:
1: Unknown Roxygen options wrap.
Supported options: roclets, load, old_usage, markdown, package 
```

This is with `packageVersion("roxygen2")`  ‘6.1.99.9001’

Also, the bug where the package is not reloaded after building it appears to be back again...

**Comment by hadley** [comment]
See the news for the details about `wrap`; it hasn't worked for a long time so it's been removed.

Please file a new issue with a reprex for the package reloading problem.
