### ISSUE TITLE
markdownified-sections not encoding properly

### ISSUE THREAD

**Issue by trestletech** [r-lib/roxygen2#948]
I'm noticing a couple of important differences when I generate the Shiny docs in one file on roxygen 6.1.1 from CRAN vs the current tip of master (ae4e1205e58426d6f92fc06fadc7729935c4d011 , at the time of writing).

When transitioning from CRAN to GitHub build, I see the following diff in `man/shinyOptions.Rd`.

![Screen Shot 2019-10-24 at 4 37 10 PM](https://user-images.githubusercontent.com/1593639/67527597-e2b49400-f6a6-11e9-93cc-38d1e035a22b.png)

I believe that both of these changes are bugs and they trigger a variety of failures in R CMD check because the Rd is now invalid:

<details>

```
   Warning: /private/var/folders/tn/j9x7l20x5zn3984w3jy23sc40000gn/T/RtmpuG5uyJ/Rbuild9ff728f05cf3/shiny/man/shinyOptions.Rd:59: unknown macro '\item'
   Warning: /private/var/folders/tn/j9x7l20x5zn3984w3jy23sc40000gn/T/RtmpuG5uyJ/Rbuild9ff728f05cf3/shiny/man/shinyOptions.Rd:62: unknown macro '\item'
   Warning: /private/var/folders/tn/j9x7l20x5zn3984w3jy23sc40000gn/T/RtmpuG5uyJ/Rbuild9ff728f05cf3/shiny/man/shinyOptions.Rd:65: unknown macro '\item'
   Warning: /private/var/folders/tn/j9x7l20x5zn3984w3jy23sc40000gn/T/RtmpuG5uyJ/Rbuild9ff728f05cf3/shiny/man/shinyOptions.Rd:69: unknown macro '\item'
   Warning: /private/var/folders/tn/j9x7l20x5zn3984w3jy23sc40000gn/T/RtmpuG5uyJ/Rbuild9ff728f05cf3/shiny/man/shinyOptions.Rd:71: unknown macro '\item'
   Warning: /private/var/folders/tn/j9x7l20x5zn3984w3jy23sc40000gn/T/RtmpuG5uyJ/Rbuild9ff728f05cf3/shiny/man/shinyOptions.Rd:74: unknown macro '\item'
   Warning: /private/var/folders/tn/j9x7l20x5zn3984w3jy23sc40000gn/T/RtmpuG5uyJ/Rbuild9ff728f05cf3/shiny/man/shinyOptions.Rd:76: unknown macro '\item'
   Warning: /private/var/folders/tn/j9x7l20x5zn3984w3jy23sc40000gn/T/RtmpuG5uyJ/Rbuild9ff728f05cf3/shiny/man/shinyOptions.Rd:78: unknown macro '\item'
   Warning: /private/var/folders/tn/j9x7l20x5zn3984w3jy23sc40000gn/T/RtmpuG5uyJ/Rbuild9ff728f05cf3/shiny/man/shinyOptions.Rd:80: unknown macro '\item'
   Warning: /private/var/folders/tn/j9x7l20x5zn3984w3jy23sc40000gn/T/RtmpuG5uyJ/Rbuild9ff728f05cf3/shiny/man/shinyOptions.Rd:84: unknown macro '\item'
   Warning: /private/var/folders/tn/j9x7l20x5zn3984w3jy23sc40000gn/T/RtmpuG5uyJ/Rbuild9ff728f05cf3/shiny/man/shinyOptions.Rd:86: unknown macro '\item'
   Warning: /private/var/folders/tn/j9x7l20x5zn3984w3jy23sc40000gn/T/RtmpuG5uyJ/Rbuild9ff728f05cf3/shiny/man/shinyOptions.Rd:90: unknown macro '\item'
   Warning: /private/var/folders/tn/j9x7l20x5zn3984w3jy23sc40000gn/T/RtmpuG5uyJ/Rbuild9ff728f05cf3/shiny/man/shinyOptions.Rd:97: unknown macro '\item'
   Warning: /private/var/folders/tn/j9x7l20x5zn3984w3jy23sc40000gn/T/RtmpuG5uyJ/Rbuild9ff728f05cf3/shiny/man/shinyOptions.Rd:102: unknown macro '\item'
   Warning: /private/var/folders/tn/j9x7l20x5zn3984w3jy23sc40000gn/T/RtmpuG5uyJ/Rbuild9ff728f05cf3/shiny/man/shinyOptions.Rd:107: unknown macro '\item'
   Warning: /private/var/folders/tn/j9x7l20x5zn3984w3jy23sc40000gn/T/RtmpuG5uyJ/Rbuild9ff728f05cf3/shiny/man/shinyOptions.Rd:109: unknown macro '\item'
   Warning: /private/var/folders/tn/j9x7l20x5zn3984w3jy23sc40000gn/T/RtmpuG5uyJ/Rbuild9ff728f05cf3/shiny/man/shinyOptions.Rd:115: unknown macro '\item'
   Warning: /private/var/folders/tn/j9x7l20x5zn3984w3jy23sc40000gn/T/RtmpuG5uyJ/Rbuild9ff728f05cf3/shiny/man/shinyOptions.Rd:121: unexpected section header '\examples'
   Warning: /private/var/folders/tn/j9x7l20x5zn3984w3jy23sc40000gn/T/RtmpuG5uyJ/Rbuild9ff728f05cf3/shiny/man/shinyOptions.Rd:127: unexpected END_OF_INPUT '
```
</details>

I bisected this back and found a couple a few milestones:
 - a7a771 - works
 - 57ca40 - missing whole section
 - 46484f - missing whole section
 - 3d680 - missing whole section
 - 81b27fc - missing whole section
 - c7754e7 - missing whole section
 - 8c82a07 - broken

So it's not totally clear from the bisect given that there was a period in which the whole section that we defined in this markdown block had disappeared. But it appears that 8c82a07 is the commit in which this became broken in the way that we're seeing now.

Admittedly, we're doing some screwy stuff in this file. https://github.com/rstudio/shiny/blob/d3f15a58fcd13665e70a41c67730090a7571d55e/R/shiny-options.R#L37 We have a `\describe{}` block embedded in the markdown for this function and -- just to make your life miserable -- even have a % sign in it that needs escaping.

~~We had some odd failures when transitioning these docs to markdown that required escaping certain % signs (but not all, if I remember correctly). Anyways, we settled on something that's been stable for the past few months but now appears to no longer work on master. I don't know what the right behavior is for % sign escaping, but on master right now, if I have `100%` in my .R file, it renders literally which clips the rest of the line of in the rendered docs. Or if I have `100\%` it renders as `100\\%` in the Rd which causes the same problem.~~ EDIT: as Gabor points out below, these are automatically escaped which is an intended change.

You can see how it currently renders here: https://github.com/rstudio/shiny/blob/d3f15a58fcd13665e70a41c67730090a7571d55e/man/shinyOptions.Rd#L68

The branch on which I'm playing with all this is here: https://github.com/rstudio/shiny/compare/jeff/int-test-docs#diff-fd8d97b2078c4dcd25669c4bf2b3cc7b

**Comment by gaborcsardi** [comment]
See https://github.com/r-lib/roxygen2/blob/ae4e1205e58426d6f92fc06fadc7729935c4d011/NEWS.md#breaking-changes

> Rd comments (%) are automatically escaped. This is a backward incompatible change because you will need to replace existing uses of \% with % (#879).

I believe this is only true in markdown mode, though. Please try to replace all `\%` with `%` and see if you still have problems.

**Comment by trestletech** [comment]
Perfect, thanks. I must have seen it wrong originally. Just pushed a commit to the linked branch above that fixes that issue.

The remaining issue is just the missing }.

**Comment by gaborcsardi** [comment]
What exactly is the `}` issue?

**Comment by hadley** [comment]
The `}` is escaped to `\}` — the Rd looks ok to me (although the type of problem that would cause this issue is often subtle), so maybe it's the Rd escaping code in the markdown processor?

**Comment by trestletech** [comment]
It looks like the `}` is only escaped if there's an empty line in the `item{` block. If I remove the newlines between the paragraphs, the escaping goes away.

**Comment by trestletech** [comment]
Ok, I pulled the file into its own package and trimmed it down: https://github.com/trestletech/roxygen-example

See that `CMD check` fails after generating the docs on the current master of roxygen2 because the `\item` gets improperly parsed.

**Comment by gaborcsardi** [comment]
Here is a reprex:

``` r
rox <- roxygen2::roc_proc_text(
  roxygen2::rd_roclet(),
  "#' Title
   #'
   #' @section Options:
   #' \\describe{
   #' \\item{this}{This is a description
   #'
   #'     with indentation that will be preformatted.}
   #'
   #' \\item{that}{That is...}
   #' }
   #' @md
   #' @name foo
   NULL")[[1]]

rox
#> % Generated by roxygen2: do not edit by hand
#> % Please edit documentation in ./<text>
#> \name{foo}
#> \alias{foo}
#> \title{Title}
#> \description{
#> Title
#> }
#> \section{Options}{
#> 
#> \describe{
#> \item{this}{This is a description\preformatted{with indentation that will be preformatted.\}
#> }
#> 
#> \item{that}{That is...}
#> }
#> }
```

<sup>Created on 2019-10-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

The problem is that four indents after an empty line are interpreted as a code block in markdown. Indent less and you'll be fine:

``` r

rox <- roxygen2::roc_proc_text(
  roxygen2::rd_roclet(),
  "#' Title
   #'
   #' @section Options:
   #' \\describe{
   #' \\item{this}{This is a description
   #'
   #'  without indentation is fine.}
   #'
   #' \\item{that}{That is...}
   #' }
   #' @md
   #' @name foo
   NULL")[[1]]

rox
#> % Generated by roxygen2: do not edit by hand
#> % Please edit documentation in ./<text>
#> \name{foo}
#> \alias{foo}
#> \title{Title}
#> \description{
#> Title
#> }
#> \section{Options}{
#> 
#> \describe{
#> \item{this}{This is a description
#> 
#> without indentation is fine.}
#> 
#> \item{that}{That is...}
#> }
#> }
```

<sup>Created on 2019-10-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by trestletech** [comment]
That did the trick! Thanks for the tip. https://github.com/rstudio/shiny/commit/3f98d19bb2e8a2d24bd07e224beb735d8839f4fe

I'll leave it up to you as to whether this issue should be closed or if there's anything more we could do here. But as far as our problem is concerned, I think we're all set.
