### ISSUE TITLE
Keep argument descriptions together when inheriting

### ISSUE THREAD

**Issue by thomasp85** [r-lib/roxygen2#950]
When several arguments are documented together (`@param x,y ...`) and this argument is inherited in another markdown chunk with `@inheritParams` the arguments are split up instead of kept together. Keeping them together in instances where it is possible would make param inheritance more useful

**Comment by IndrajeetPatil** [comment]
Same issue as https://github.com/r-lib/roxygen2/issues/826

**Comment by gaborcsardi** [comment]
We will fix this, but it will not make it into 7.0.0, which is already happening. Sorry!

**Comment by hadley** [comment]
I think we'd still like to fix this one day; it comes up in quite a few places.
