### ISSUE TITLE
Escaping backslashes in backticks

### ISSUE THREAD

**Issue by jimhester** [r-lib/roxygen2#951]
```r
#' `\\foo`
```

Produces Rd that looks like

```
\verb{\\\\foo}
```

And ideally it should look like

```
\verb{\\foo}
```

``` r
roxygen2::roc_proc_text(roxygen2::rd_roclet(), "
  #' foo
  #' `\\\\foo`
  #' @md
  foo <- function(x) x")[[1]]
#> % Generated by roxygen2: do not edit by hand
#> % Please edit documentation in ./<text>
#> \name{foo}
#> \alias{foo}
#> \title{foo
#> \verb{\\\\foo}}
#> \usage{
#> foo(x)
#> }
#> \description{
#> foo
#> \verb{\\\\foo}
#> }
```

<sup>Created on 2019-10-31 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by gaborcsardi** [comment]
With a single `\` we get:

``` r
roxygen2::roc_proc_text(roxygen2::rd_roclet(), "
  #' foo
  #' `\\foo`
  #' @md
  foo <- function(x) x")[[1]]
#> % Generated by roxygen2: do not edit by hand
#> % Please edit documentation in ./<text>
#> \name{foo}
#> \alias{foo}
#> \title{foo
#> \verb{\\foo}}
#> \usage{
#> foo(x)
#> }
#> \description{
#> foo
#> \verb{\\foo}
#> }
```

<sup>Created on 2019-10-31 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by gaborcsardi** [comment]
The single escaping seems fine for me, am I missing something? What was the problem with that?

``` r
out <- roxygen2::roc_proc_text(roxygen2::rd_roclet(), "
  #' foo
  #'
  #' `\\foo`
  #' @md
  foo <- function(x) x")[[1]]

rd <- tools::parse_Rd(file = textConnection(format(out)))

tools::Rd2txt(rd)
#> _f_o_o
#> 
#> _D_e_s_c_r_i_p_t_i_o_n:
#> 
#>      \foo
#> 
#> _U_s_a_g_e:
#> 
#>      foo(x)
#> 
```

<sup>Created on 2019-10-31 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by jimhester** [comment]
Yes, you get a warning then from `R CMD check`, this is what I was trying to work around by escaping in the first place.

> Warning: .../Rbuildd16520dcf710/usethis/man/actions.Rd:87: unknown macro '\document'

`remotes::install_github("r-lib/usethis@b18b28de13e0")` should reproduce it.

**Comment by gaborcsardi** [comment]
Oh, right, got it.

**Comment by hadley** [comment]
The problem is probably the escaping conventions for markdown code chunks battling with the escaping conventions for R code. Maybe `\verb{}` needs to escape slightly differently to `\code{}`?

**Comment by gaborcsardi** [comment]
Right. So it seems that in `r-lib/usethis@b18b28de13e0` you used roxygen2 6.1.1 (https://github.com/r-lib/usethis/blob/b18b28de13e0e46a452fb052cf11f07ec9d9336b/DESCRIPTION#L55), which generates `\code{\document}` (https://github.com/r-lib/usethis/blob/b18b28de13e0e46a452fb052cf11f07ec9d9336b/man/actions.Rd#L87), and that indeed freaks out `R CMD check`.

But the new roxygen generates `\verb{\\document}` in this case, which seems to be fine which `R CMD check`.

So, I think the new roxygen escaping has already fixed this, actually.

**Comment by jimhester** [comment]
Oh, you are right! Sorry for opening the issue, I must have gotten mixed up on what roxygen version I was using.

**Comment by gaborcsardi** [comment]
No worries, that's great, then we do understand the escaping rules after all. Well, there is a chance at least. :)

**Comment by hadley** [comment]
😅
