### ISSUE TITLE
`%` not properly escaped in \dontrun{}

### ISSUE THREAD

**Issue by wch** [r-lib/roxygen2#965]
On the left is the input, on the right is the rendered help file:

![image](https://user-images.githubusercontent.com/86978/68790928-e71cfe80-060d-11ea-9024-f3b030983513.png)

This is what the .Rd file looks like:

```
mtcars \%>\% dplyr::select(wt)

\dontrun{
mtcars %>% dplyr::select(wt)
}
```

**Comment by hadley** [comment]
Do you mind making a reprex as in https://github.com/r-lib/roxygen2/blob/master/.github/SUPPORT.md#making-a-reprex ?

**Comment by wch** [comment]
```R
library(roxygen2)
roc_proc_text(rd_roclet(), "
  #' Title
  #' @examples
  #' mtcars %>% identity()
  #'
  #' \\dontrun{
  #' mtcars %>% identity()
  #' }
  foo <- function() {}")
#> $foo.Rd
#> % Generated by roxygen2: do not edit by hand
#> % Please edit documentation in ./<text>
#> \name{foo}
#> \alias{foo}
#> \title{Title}
#> \usage{
#> foo()
#> }
#> \description{
#> Title
#> }
#> \examples{
#> mtcars \%>\% identity()
#> 
#> \dontrun{
#> mtcars %>% identity()
#> }
#> }
```

**Comment by gaborcsardi** [comment]
Yes, I think I did that in #958. I apparently missed the potential issue with `%`. :(

**Comment by gaborcsardi** [comment]
TBH I am not entirely sure that escaping `%` in `\dontrun{}` is the right thing to do here, but we since it will fix the regression, we should still probably do it.
