### ISSUE TITLE
"Error: `.x` is not a vector (pairlist)" on R-3.5

### ISSUE THREAD

**Issue by alecw** [r-lib/roxygen2#966]
```
> library(roxygen2)
> sessionInfo()
R version 3.5.0 (2018-04-23)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Red Hat Enterprise Linux

Matrix products: default
BLAS/LAPACK: /broad/software/free/Linux/redhat_7_x86_64/pkgs/openblas_0.2.20/lib/libopenblas_nehalemp-r0.2.20.so

locale:
[1] C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] roxygen2_7.0.0

loaded via a namespace (and not attached):
 [1] compiler_3.5.0 R6_2.3.0       magrittr_1.5   tools_3.5.0    Rcpp_1.0.0    
 [6] xml2_1.2.0     stringi_1.2.4  stringr_1.3.1  rlang_0.3.0.1  purrr_0.2.5   
> roc_proc_text(rd_roclet(), "
+ #' @export
buggy = function(newFile) {
}")
+ + Error: `.x` is not a vector (pairlist)
```

**Comment by gaborcsardi** [comment]
```r
roc_proc_text(rd_roclet(), "
#' @export
buggy = function(newFile) {
}")
```

**Comment by sgp79** [comment]
I saw this too [Windows 7 R version 3.5.1, roxygen2 version 7.0.0].
Resolved by upgrading purrr to version >= 3.0.0
purr version does not seem to be defined in Roxygen Imports

**Comment by hadley** [comment]
@lionel- do you remember the combination of package versions that cause this problem? i.e. what version of purrr should roxygen2 require?

**Comment by sgp79** [comment]
FWIW, having realised that an upgrade to the release version of purrr (0.3.3) fixed the issue for me, I tested a few other versions (all with Windows 7, R version 3.5.1).  The latest 0.2 version in the archive (0.2.5) gave the error, the first 0.3 version (0.3.0) was fine.

**Comment by lionel-** [comment]
Pairlist support was introduced in purrr 0.3.0, but this version had bugs so it's perhaps best to depend on latest purrr.
