### ISSUE TITLE
incorrect use of backslashes in .Rd files

### ISSUE THREAD

**Issue by achubaty** [r-lib/roxygen2#967]
The latest version (7.0.0) breaks one of my `.Rd` files containing the following code in an example:

```
paths <- list("./aaa/zzz",
              "./aaa/zzz/",
              ".//aaa//zzz",
              ".//aaa//zzz/",
              ".\\aaa\\zzz",
              ".\\aaa\\zzz\\", ## <- the double backslashes should convert to quad-backslashes
              file.path(".", "aaa", "zzz"))
```

gets converted to this in the `.Rd`:

```
paths <- list("./aaa/zzz",
              "./aaa/zzz/",
              ".//aaa//zzz",
              ".//aaa//zzz/",
              ".\\\\aaa\\\\zzz",
              ".\\\\aaa\\\\zzz\\\", ## <- note the 3 trailing backslashes instead of 4
              file.path(".", "aaa", "zzz"))
```

this has the effect of escaping the closing quotation mark, which results in the warning

```
Warning: newline within quoted string 
```

As a workaround, I have commented out the offending line in the example, but this is a temporary solution.
https://github.com/PredictiveEcology/reproducible/commit/fbf8bf68d8efcab844214d13542261a02303e605

**Comment by gaborcsardi** [comment]
Thanks! Would you mind creating a reproducible example like this: https://github.com/r-lib/roxygen2/blob/master/.github/SUPPORT.md#making-a-reprex

**Comment by achubaty** [comment]
reprex:

1. create the example file (e.g., `/tmp/reprex-967.R`) containing the following:

    ```r
    paths <- list("./aaa/zzz",
                  "./aaa/zzz/",
                  ".//aaa//zzz",
                  ".//aaa//zzz/",
                  ".\\aaa\\zzz",
                  ".\\aaa\\zzz\\",
                  file.path(".", "aaa", "zzz"))
    ```

2. generate the broken Rd file:

    ```r
    library(roxygen2)
    setwd("/tmp")
    
    roc_proc_text(rd_roclet(), "
      #' Title
      #' @param x xfoo
      #'
      #' @export
      #' @example reprex-967.R
      foo <- function(x) { return(x) }
    ")
    ```

which produces:

```
$foo.Rd
% Generated by roxygen2: do not edit by hand
% Please edit documentation in ./<text>
\name{foo}
\alias{foo}
\title{Title}
\usage{
foo(x)
}
\arguments{
\item{x}{xfoo}
}
\description{
Title
}
\examples{
paths <- list("./aaa/zzz",
              "./aaa/zzz/",
              ".//aaa//zzz",
              ".//aaa//zzz/",
              ".\\\\aaa\\\\zzz",
              ".\\\\aaa\\\\zzz\\\",
              file.path(".", "aaa", "zzz"))
}
```

**Comment by gaborcsardi** [comment]
Self-contained reprex:

``` r

library(roxygen2)

tmp <- tempfile()
cat("paths <- list(\".\\aaa\\zzz\\\\\",\n \"foobar\")", file = tmp)

setwd(dirname(tmp))
roc_proc_text(rd_roclet(), sprintf("
  #' Title
  #'
  #' @example %s
  foo <- function() NULL
", basename(tmp)))
#> $foo.Rd
#> % Generated by roxygen2: do not edit by hand
#> % Please edit documentation in ./<text>
#> \name{foo}
#> \alias{foo}
#> \title{Title}
#> \usage{
#> foo()
#> }
#> \description{
#> Title
#> }
#> \examples{
#> paths <- list(".\\aaa\\zzz\\\",
#>  "foobar")
#> }
```

<sup>Created on 2019-11-14 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Inline fails as well, slightly differently, because roxygen checks for well-formed rd:

``` r
library(roxygen2)

roc_proc_text(rd_roclet(), "
  #' Title
  #'
  #' @examples
  #' paths <- list(\".\\aaa\\zzz\\\\\",
  #'               \"foobar\")
  foo <- function() NULL
")
#> Warning: [<text>:4] @examples mismatched braces or quotes
#> $foo.Rd
#> % Generated by roxygen2: do not edit by hand
#> % Please edit documentation in ./<text>
#> \name{foo}
#> \alias{foo}
#> \title{Title}
#> \usage{
#> foo()
#> }
#> \description{
#> Title
#> }
```

<sup>Created on 2019-11-14 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hadley** [comment]
Slightly more minimal reprex:

``` r
library(roxygen2)

text <- "
  #' Title
  #'
  #' @examples
  #' x <- c('\\', 'foobar')
  foo <- function() NULL
"
cat(text)
#> 
#>   #' Title
#>   #'
#>   #' @examples
#>   #' x <- c('\', 'foobar')
#>   foo <- function() NULL
roc_proc_text(rd_roclet(), text)[[1]]$get_section("examples")
#> Warning: [<text>:4] @examples mismatched braces or quotes
#> NULL
```

<sup>Created on 2019-11-20 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by gaborcsardi** [comment]
The problem is that we first escape the backslashes here:
https://github.com/r-lib/roxygen2/blob/f6b46a87a8de3964354ac199e70a85653adab9f5/R/utils-rd.R#L26
and then try to un-escape the ones within strings here:
https://github.com/r-lib/roxygen2/blob/f6b46a87a8de3964354ac199e70a85653adab9f5/R/rd-examples.R#L58-L59

However the un-escaping does not know if the backslash of `\\'` is actually part of an escaped backslash, like int the reprex.

Maybe it would be better not to touch strings at all when we escape the examples. 

(Actually, I think the ideal solution is not to escape the examples at all, but that ship has sailed.)
