### ISSUE TITLE
Teach roxygen2 about `vignette("vignette-or-article-name")`

### ISSUE THREAD

**Issue by jennybc** [r-lib/roxygen2#968]
It feels like `vignette("vignette-or-article-name")` could get better treatment by roxygen2. For pkgdown reasons (and perhaps just in general), this is the preferred way to refer to a vignette from Rd. And on pkgdown, it's a hyperlink. Could it become a hyperlink in Rd too?

The example that motivated me to open this was an *article*, so there's no local hope of viewing anyway, i.e. you have to read it on the pkgdown site. So executing `vignette("article-name")` locally wouldn't achieve anything but a hyperlink would.

**Comment by hadley** [comment]
We could easily adapt `mdxml_code()` to convert (e.g.) `vignette("x")` to `\href{"../vignettes/x"}{\code{vignette("x")}}`. 

This won't work for articles, but I worry that using `vignette("foo")` is fundamentally confusing anyway. Is there a reason you don't want to link directly to the article?

**Comment by gaborcsardi** [comment]
Would it make sense to create a new link type for this, so we could just write
```
[pkg::vignette::x][link text]
```
or something similar to link to a vignette? We could make it work for help files and also pkgdown I guess.

**Comment by jennybc** [comment]
> Is there a reason you don't want to link directly to the article?

Not a particularly good one. It's motivated by a general sense that it's better to say "link to this article for the current package" than to hard wire the URL.

**Comment by hadley** [comment]
Or maybe `[vignette("dplyr")]` would generate a link?

**Comment by gaborcsardi** [comment]
> Not a particularly good one. It's motivated by a general sense that it's better to say "link to this article for the current package" than to hard wire the URL.

What I meant is to have a `[pkg::vignette::x][link text]` notation that links to vignette x of the current package.

**Comment by hadley** [comment]
Given that there's no good R-native way to link to a vignette from an `.Rd`, and downlit takes care of this for package websites, I think we can close this issue.
