### ISSUE TITLE
@useDynLib with argument .registration=TRUE does not work properly

### ISSUE THREAD

**Issue by cbergmeir** [r-lib/roxygen2#97]
Hello,

I'm currently adapting some packages that use Rcpp from roxygen to roxygen2, and ran into the following issue:

This line:
# ' @useDynLib Rmalschains .registration=TRUE

In roxygen generated correctly in the NAMESPACE:

useDynLib(Rmalschains,.registration=TRUE)

whereas in roxygen2, it generates:

useDynLib(Rmalschains,".registration=TRUE")

The quotation marks shouldn't be there, and the result is an error when the package is built. I'm wondering if anybody else has this problem..

**Comment by pascal-niklaus** [comment]
What is the status with this? 
I encounter the same problem with a freshly install roxygen2.
