### ISSUE TITLE
Expand `@includeRmd` in the description section

### ISSUE THREAD

**Issue by lionel-** [r-lib/roxygen2#970]
From @gaborcsardi: We can't have nested roxygen tags currently, but the section to expand to could be a parameter.

**Comment by gaborcsardi** [comment]
```r
#' @includeRmd description path/to/file.Rmd
```
might work. Somewhat ambiguous, but that's probably OK.

**Comment by hadley** [comment]
Doesn't this work already?

https://github.com/r-lib/tidyselect/blob/master/R/faq.R#L1-L7 

yields

https://github.com/r-lib/tidyselect/blob/master/man/faq-external-vector.Rd#L7

**Comment by gaborcsardi** [comment]
@hadley: that's only because the Rmd starts with a `##`, which creates a subsection. If you start with `#` or with just non-heading text, that'll go into `@details` I think.

**Comment by lionel-** [comment]
@hadley I hardcoded `description` in my local roxygen.
