### ISSUE TITLE
Option to force \code{}

### ISSUE THREAD

**Issue by yutannihilation** [r-lib/roxygen2#975]
I see this diff using roxygen2 7.0

```diff
- \code{axis.line.y.left}, \code{axis.line.y.right}). \code{axis.line.*.*} inherits from
- \code{axis.line.*} which inherits from \code{axis.line}, which in turn inherits
+ \code{axis.line.y.left}, \code{axis.line.y.right}). \verb{axis.line.*.*} inherits from
+ \verb{axis.line.*} which inherits from \code{axis.line}, which in turn inherits
```
(https://github.com/tidyverse/ggplot2/pull/3630/files#diff-9f5c5fab9e6d56acc2a036749a3fb531L70-R145)

I think `\code{}` should be used here because `axis.line.*` is a symbol, not a part of code snippet. Though this doesn't seem a big issue (and I don't know well about what `\verb{}` is), I'm filing this issue just for notice. Please feel free to close if this is not a problem.

**Comment by lionel-** [comment]
See also #971.

**Comment by gaborcsardi** [comment]
> I think \code{} should be used here because `axis.line.*` is a symbol

`\code{}` must be valid R code, and `axis.line.*` is not, so according to the Rd rules, it has to be `\verb{}`. Not that it matters much for the output, because both `\verb{}` and `\code{}` are displayed the same exact way AFAIK.

**Comment by yutannihilation** [comment]
> `\code{}` must be valid R code

I'm not sure if Writing R Extension explicitly says so. In my understanding, the R code on Rd is not  necessarily valid except when it's intended to run as it says about `\examples{}`:

> Text included in \dontrun is indicated by comments in the processed help files: it need not be valid R code but the escapes must still be used for %, \ and unpaired braces as in other ‘verbatim’ text.

I'm also not sure if this applies `\code{}` or not, though.

**Comment by gaborcsardi** [comment]
> I'm not sure if Writing R Extension explicitly says so. In my understanding, the R code on Rd is not necessarily valid except when it's intended to run as it says about \examples{}:

It is in Table 3: https://developer.r-project.org/parseRd.pdf

**Comment by yutannihilation** [comment]
Thanks, probably it's just I don't understand the terminologies. Sorry for the noise...

**Comment by gaborcsardi** [comment]
Basically in that document "R-like" means syntactically valid R code. This holds for `\examples{}`, `\usage{}`, etc., and `\code{}` as well. But `R CMD check` does not enforce it for `\code{}` because many packages misuse it. That is my understanding. :)

**Comment by yutannihilation** [comment]
> But R CMD check does not enforce it for \code{} because many packages misuse it

Ah, got it! I was wondering why R CMD check didn't bite us if it's not valid... Then I totally agree  with you. Closing this now. Thanks!
