### ISSUE TITLE
.Rd files are forcibly rewritten with LF ending on Windows

### ISSUE THREAD

**Issue by krlmlr** [r-lib/roxygen2#989]
despite of what's announced in the NEWS and in #841.

To reproduce:

- Clone any package on Windows
- Run `unix2dos man/*.Rd`
- Run `devtools::document()`

I believe this is because `write_if_different()` already receives character strings with embedded newlines, and `write_lines()` doesn't convert them to the detected newlines.

**Comment by hadley** [comment]
@jimhester can you please take a look?

**Comment by kent37** [comment]
This is really annoying. For a project created on Windows, with .Rd files created by `roxygen2`, after updating to `roxygen2` 7.0.2 and running `CMD check`, all the .Rd files have new line endings.

**Comment by hadley** [comment]
@krlmlr could you please try out #1003 and see if it works for you?

**Comment by krlmlr** [comment]
Works for me, but produces bogus `Writing xxx.Rd` messages. Would you like me to look into removing these?

**Comment by sz-cgt** [comment]
Just ran `devtools::install_github("r-lib/roxygen2")` and regenerated documentation on a Windows only project.

Still seeing \n instead of \r\n in the generared .Rd files

**Comment by hadley** [comment]
@sz-cgt you'll need to install from the PR: `devtools::install_github("r-lib/roxygen2#1003")`

**Comment by sz-cgt** [comment]
Oops.  Thanks.  The PR works for me
