### ISSUE TITLE
Make "Section title spans multiple lines" more helpful?

### ISSUE THREAD

**Issue by maelle** [r-lib/roxygen2#994]
Would it make sense to replace "Section title spans multiple lines"

with something like "Section title spans multiple lines - did you forget a colon (":") at the end of the title?".

**Comment by hadley** [comment]
Sure, want to do a PR?

**Comment by maelle** [comment]
Yes, I'll do one next week!

**Comment by jtr13** [comment]
This is SO helpful. I was using an old version of roxygen2 without the updated phrasing and the multiple lines message was driving me nuts!
