### ISSUE TITLE
specify example in function body

### ISSUE THREAD

**Issue by bgctw** [r-lib/roxygen2#998]
proposed feature: new tag `@exampleFunction <functionName>`

where the body of referenced function <functionName> specifies the example code.
The approach combines several advantages:

-  specify example nearby the original code (instead of is own file with `@example`)
- use code formatting/ interactive execution and all the editor features (instead of commented
  code as with `@examples`)

This feature helps users transition to roxygen who use a similar feature a lot in their existing inlinedocs documentation.

Example:
```
#' Calculate mu and sigma of lognormal from summary statistics.
#' 
#' @exampleFunction example_getParmsLognormForModeAndUpper
getParmsLognormForModeAndUpper <- function(...){
}
example_getParmsLognormForModeAndUpper <- function(){
  # example 1: a distribution with mode 1 and upper bound 5
  (thetaEst <- getParmsLognormForModeAndUpper(1,5))
}
```

copying the lines from the body to the examples section:
```
  # example 1: a distribution with mode 1 and upper bound 5
  (thetaEst <- getParmsLognormForModeAndUpper(1,5))
```

**Comment by gaborcsardi** [comment]
> specify example nearby the original code (instead of is own file with @example)

It is already near if you use `@examples`. It is typically right above the function, within the rest of the documentation.

> use code formatting/ interactive execution and all the editor features (instead of commented code as with @examples)

Most editors help you with this. E.g. in Emacs ESS and RStudio you can easily run the examples from the roxygen comments.
